### ISSUE TITLE
CI builds are failing

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sourcelink#1044]
It appears that the [sourcelink CI build](https://dev.azure.com/dnceng/internal/_build?definitionId=576) (Microsoft internal) has been failing since May 3rd.  The latest bits are therefore not flowing into the downstream repos such as the SDK.

The first failing build was for the following changes - Clean-up sourcelink repo and remove workarounds (grouped into commits) (#1015)

```
D:\a\_work\1\s\.dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5017: Cannot create a package that has no dependencies nor content. [D:\a\_work\1\s\src\Microsoft.Build.StandardCI\Microsoft.Build.StandardCI.csproj]
##[error].dotnet\sdk\8.0.100-preview.3.23178.7\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5017: (NETCORE_ENGINEERING_TELEMETRY=Build) Cannot create a package that has no dependencies nor content.
```

cc @ViktorHofer

**Comment by MichaelSimons** [comment]
One question to answer when fixing this is why the issue that caused the CI builds to fail was not caught in PR validation.

**Comment by ViktorHofer** [comment]
Submitted https://github.com/dotnet/sourcelink/pull/1046 to fix the official builds.
