### ISSUE TITLE
"Assembly with same name is already loaded" in .NET 8 SDK when building on azure devops

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [dotnet/sourcelink#1142]
Hi,

I encountered an error when trying to build using .NET 8 SDK on azure pipelines

##[error]C:\hostedtoolcache\windows\dotnet\sdk\8.0.100\Sdks\Microsoft.Build.Tasks.Git\build\Microsoft.Build.Tasks.Git.targets(25,5): Error MSB4062: The "Microsoft.Build.Tasks.Git.LocateRepository" task could not be loaded from the assembly C:\hostedtoolcache\windows\dotnet\sdk\8.0.100\Sdks\Microsoft.Build.Tasks.Git\build\..\tools\core\Microsoft.Build.Tasks.Git.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Could you please advise what is the root cause?

Repository https://github.com/AdaskoTheBeAsT/AdaskoTheBeAsT.AutoMapper.SimpleInjector
![image](https://github.com/dotnet/sourcelink/assets/1914201/161f01a2-6e97-4361-9001-b598d6024a4a)

Failing pipeline

https://adaskothebeast.visualstudio.com/AdaskoTheBeAsT.AutoMapper.SimpleInjector/_build/results?buildId=1042&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=006e6f7c-8314-5e02-a3df-483f3a1f4cfa

**Comment by tmat** [comment]
Can you share a binlog from the build?

**Comment by AdaskoTheBeAsT** [comment]
Hi,

yes please see below

[msbuild.binlog.gz](https://github.com/dotnet/sourcelink/files/13383033/msbuild.binlog.gz)

**Comment by AdaskoTheBeAsT** [comment]
Hi any findings so far?

**Comment by tmat** [comment]
@AdaskoTheBeAsT Unfortuantely, I have trouble opening the file. Could you share the file directly (not gzip'ed). It should already be compressed.

**Comment by tmat** [comment]
Do you have PackageReference to Source Link packages in the project? Does it work if you remove them?

**Comment by AdaskoTheBeAsT** [comment]
I will remove it and check
