### ISSUE TITLE
Multiple items passed into a parameter of type 'Microsoft.Build.Framework.ITaskItem - build error ASP.NET Core

### ISSUE THREAD

**Issue by dewey-jones** [dotnet/sourcelink#1172]
This arose after I upgraded the framework of my Web API from netcoreapp7.0 to netcoreapp8.0.

I receive this build error:

"C:\Users\Dewey.nuget\packages;C:\Users\dewey.nuget\packages" is an invalid value for the "SourceRoot" parameter of the "Microsoft.SourceLink.GitHub.GetSourceLinkUrl" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem".

Here is the contents of the file in which the error occurs, C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.SourceLink.GitHub\build\Microsoft.SourceLink.GitHub.targets:

`
<Project>
  <PropertyGroup>
    <_SourceLinkGitHubAssemblyFile Condition="'$(MSBuildRuntimeType)' != 'Core'">$(MSBuildThisFileDirectory)..\tools\net472\Microsoft.SourceLink.GitHub.dll</_SourceLinkGitHubAssemblyFile>
    <_SourceLinkGitHubAssemblyFile Condition="'$(MSBuildRuntimeType)' == 'Core'">$(MSBuildThisFileDirectory)..\tools\core\Microsoft.SourceLink.GitHub.dll</_SourceLinkGitHubAssemblyFile>
  </PropertyGroup>

  <UsingTask TaskName="Microsoft.SourceLink.GitHub.GetSourceLinkUrl" AssemblyFile="$(_SourceLinkGitHubAssemblyFile)"/>
  <UsingTask TaskName="Microsoft.SourceLink.GitHub.TranslateRepositoryUrls" AssemblyFile="$(_SourceLinkGitHubAssemblyFile)"/>

  <PropertyGroup>
    <SourceLinkUrlInitializerTargets>$(SourceLinkUrlInitializerTargets);_InitializeGitHubSourceLinkUrl</SourceLinkUrlInitializerTargets>
    <SourceControlManagerUrlTranslationTargets>$(SourceControlManagerUrlTranslationTargets);TranslateGitHubUrlsInSourceControlInformation</SourceControlManagerUrlTranslationTargets>
  </PropertyGroup>

  <Target Name="_InitializeGitHubSourceLinkUrl" Outputs="%(SourceRoot.Identity)">
    
    <Microsoft.SourceLink.GitHub.GetSourceLinkUrl RepositoryUrl="$(PrivateRepositoryUrl)" SourceRoot="@(SourceRoot)" Hosts="@(SourceLinkGitHubHost)" IsSingleProvider="$(SourceLinkHasSingleProvider)">
      <Output TaskParameter="SourceLinkUrl" PropertyName="_SourceLinkUrlToUpdate"/>
    </Microsoft.SourceLink.GitHub.GetSourceLinkUrl>

    <ItemGroup>
      
      <SourceRoot Update="%(Identity)" SourceLinkUrl="$(_SourceLinkUrlToUpdate)" Condition="'$(_SourceLinkUrlToUpdate)' != 'N/A'"/>
    </ItemGroup>
  </Target>

  
  <Target Name="TranslateGitHubUrlsInSourceControlInformation">

    <ItemGroup>
      <_TranslatedSourceRoot Remove="@(_TranslatedSourceRoot)"/>
    </ItemGroup>

    <Microsoft.SourceLink.GitHub.TranslateRepositoryUrls RepositoryUrl="$(ScmRepositoryUrl)" SourceRoots="@(SourceRoot)" Hosts="@(SourceLinkGitHubHost)" IsSingleProvider="$(SourceLinkHasSingleProvider)">
      <Output TaskParameter="TranslatedRepositoryUrl" PropertyName="ScmRepositoryUrl"/>
      <Output TaskParameter="TranslatedSourceRoots" ItemName="_TranslatedSourceRoot"/>
    </Microsoft.SourceLink.GitHub.TranslateRepositoryUrls>

    <ItemGroup>
      <SourceRoot Remove="@(SourceRoot)"/>
      <SourceRoot Include="@(_TranslatedSourceRoot)"/>
    </ItemGroup>
  
</Target>

</Project>
`

**Comment by dewey-jones** [comment]
@KalleOlaviNiemitalo, no, the Nuget.Config file under AppData\Roaming has:

```
  <packageSources>
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
```

while the Nuget.Config file under C:\Program Files (x86)\NuGet\Config has:

```
  <packageSources>
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"/>
  </packageSources>
```
The environment variables you mentioned do not exist on my computer.

**Comment by dewey-jones** [comment]
That file has:

```
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <SourceRoot Include="C:\Users\dewey\.nuget\packages\" />
  </ItemGroup>
```

**Comment by tmat** [comment]
Could you please run `dotnet build -bl` and share the generated msbuild.binlog? If you don't want to share publicly feel free to create https://developercommunity.visualstudio.com/home ticket and link it to this issue.

**Comment by dewey-jones** [comment]
@tmat where is msbuild.binlog found?

**Comment by tmat** [comment]
It's output by `dotnet build -bl`

**Comment by dewey-jones** [comment]
Is the attached output file what you are expecting?
[Sourcelink problem.txt](https://github.com/dotnet/sourcelink/files/13878208/Sourcelink.problem.txt)

**Comment by tmat** [comment]
I'll need the file `msbuild.binlog` - it contains detailed log of the build.

**Comment by dewey-jones** [comment]
[msbuild.binlog.txt](https://github.com/dotnet/sourcelink/files/13923843/msbuild.binlog.txt)
(Renamed as .txt so it could be attached.)

**Comment by dewey-jones** [comment]
@tmat does that help?

**Comment by tmat** [comment]
Yes, I see the issue.

Any idea how where this file came from?
`C:\Users\dewey\OneDrive\Documents\github\crm.api\obj\crmApi.csproj.nuget.g-DESKTOP-9HQUT28.props`

Perhaps it's an artifact of OneDrive versioning? I think this might be causing the issue - it's essentially duplicating some build items. Can you try to clear the obj directory and rebuild?

**Comment by tmat** [comment]
Also, if you are building with .NET SDK 8+ you don't need Source Link PackageReferences since the SDK ships with Source Link included out of the box.

**Comment by dewey-jones** [comment]
That worked!  Thank you @tmat.  You have probably saved me from reconstructing the API as .NET 7 from scratch.

**Comment by tmat** [comment]
Glad it worked.
