### ISSUE TITLE
Multitargeting using SDK 8.0

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/sourcelink#1180]
We build and pack our nuget packages with github sourcelink support for net6.0 net7.0 and net8.0 using NET SDK 8.0
I understand NET SDK 8.0 includes sourcelink natively.
Our github repo is https://github.com/MudBlazor/MudBlazor

We currently reference 
```
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

Can we just remove this now from our csproj?
I am thinking will it affect net6.0 net7.0 targets?

**Comment by tmat** [comment]
Yes, you can remove them.  Source Link will be applied to all TFMs as long as the SDK used for the build is 8.0+

**Comment by mikes-gh** [comment]
Thanks @tmat
