### ISSUE TITLE
Question: which package should I used?

### ISSUE THREAD

**Issue by HakamFostok** [dotnet/sourcelink#1181]
Sorry but I am really confused, my company put the code and publish our package on the `https://dev.azure.com/our-company`
which package should I use?
According to the documentation, it only mention Azure Repos and Azure DevOps Server (which is used on-perm).
when I clicked on the Azure Repos link in the readme, it took me to the [Micorsoft page](https://azure.microsoft.com/en-us/products/devops/repos/) which I saw the exact same UIs that we are using, should I suppose that I am using Azure Repos?

**Comment by tmat** [comment]
Yes, Microsoft.SourceLink.AzureRepos.Git is the right Source Link package for dev.azure.com.
If you're using .NET SDK 8.0+ you don't need to add any package. Support for Azure Repos comes out-of-the box.
