### ISSUE TITLE
Central Package Management and Microsoft.SourceLink.GitHub

### ISSUE THREAD

**Issue by hisnyjb** [dotnet/sourcelink#1226]
It appears something in the source link toolchain is trying to set an explicit version which leads to an NU1008 for centrally managed packages.

error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Microsoft.SourceLink.GitHub. 

If the version for Microsoft.SourceLink.GitHub in Directory.Packages.props is set, then a warning is created:

warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.SourceLink.GitHub 1.1.1, Microsoft.SourceLink.GitHub .

Attempts to disable source link don't help.

**Comment by tmat** [comment]
Which version of .NET SDK do you use?

**Comment by hisnyjb** [comment]
8.0.202. 

We're using MSBuild with a restore, if that is useful and the problem isn't consistent across machines. One machine has begun failing to build across multiple repos while another is fine. Both seem to be on the same version of Visual Studio.

**Comment by tmat** [comment]
Source Link is included in .NET SDK 8 by default. You can remove all PackageReferences to Source Link packages.

**Comment by hisnyjb** [comment]
We don't have any references to it normally. Errors started happening on a single machine because a version was being set for source link outside of our projects. Trying include a package reference creates the warning of a conflict, but that was an addition to see if we could tease out why we were getting the NU1008 error (why something was setting an explicit source link version in a centrally managed package build). None of our projects use source link (except by automatic inclusion) and none of the ProjectReferences have a version set. 

Since it isn't consistent across machines, it appears to be a setting on one that creates this behavior, but we have yet to isolate it.

**Comment by hisnyjb** [comment]
To be very clear. Normally, our build uses Directory.Packages.props where we set PackageVersion for the whole system. All of our projects will use a PackageReference without a version. One of our machines began to have failures in its build with the NU1008 error involving Microsoft.SourceLink.GitHub. Trying to clear NuGet caches, build directories, etc. do not alleviate the problem. Visual Studio seems to be consistent across machines that work and don't.

Somehow, the build thinks that a version is being set for Microsoft.SourceLink.GitHub (even though we have no references to it) and this creates a build failure because versions are supposed to be set in Directory.Packages.props.

**Comment by tmat** [comment]
Can you build using `dotnet build /bl` and share the generated msbuild.binlog file via [VS feedback](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)? Or here, if the repository is open source.
