### ISSUE TITLE
README.md example link goes to 404

### ISSUE THREAD

**Issue by sgwatgit** [dotnet/sourcelink#129]
`You can enable SourceLink in your own project hosted on GitHub by following this example:` in the README currently goes to a 404.

I'm trying to get source link working for my .netstandard 2.0 library that I've published on Nuget.

I've gone here https://github.com/ctaggart/SourceLink looking for documentation which pointed me here. But I'm having a really hard time figuring out what the state of this package/feature is.

What's the 'real' project/source I should be looking at?
Where's the most up to date documentation?
What should I be doing as a package creator?
What should I be doing as a package consumer?

Thanks

**Comment by tmat** [comment]
> You can enable SourceLink in your own project hosted on GitHub by following this example: in the README currently goes to a 404.

Thanks for spotting it. I have updated README.md.

> What's the 'real' project/source I should be looking at?

dotnet/sourcelink is an evolution of ctaggart/SourceLink project. dotnet/sourcelink is Microsoft supported implementation.

> Where's the most up to date documentation?

The basics are summarized in https://github.com/dotnet/sourcelink/blob/master/README.md. More details are available here: https://github.com/dotnet/sourcelink/blob/master/docs/README.md.

> What should I be doing as a package creator?

Follow the instructions on  https://github.com/dotnet/sourcelink/blob/master/README.md - essentially just set a few properties and add a reference to a SourceLink package.

> What should I be doing as a package consumer?

As long as you have the latest version of Visual Studio 2017 SourceLink should just work. There are known issues with authentication to private repositories for some source control providers (e.g. https://github.com/dotnet/sourcelink/issues/135).
