### ISSUE TITLE
PublishRepositoryUrl to TRUE truncates COMMIT SHA

### ISSUE THREAD

**Issue by crystalworks** [dotnet/sourcelink#1294]
Adding sourcelink to .Net 8 project and setting PublishRepositoryUrl to TRUE truncates SHA from 40 to 10 characters. Proves to be an issue when trying to integrate into systems which expect 40 char SHA

**Comment by tmat** [comment]
Could you please share `msbuild.binlog` produced by `dotnet build -bl`?

**Comment by crystalworks** [comment]
I can but could I sent direct to you?

**Comment by crystalworks** [comment]
for additional context. This is while trying to integrate with Datadog, I suspect it could be their side but seems bizarre than once that flag is set to true, my traces/spans land in datadog with the short sha (GitCommitIdShort) instead of the long one (GitCommitId)
