### ISSUE TITLE
SourceRevisionId not set for AssemblyInformationalVersion (.NET Fx 4.0)

### ISSUE THREAD

**Issue by xied75** [dotnet/sourcelink#139]
Dear all,

Was trying to use SourceLink via nuget package _Microsoft.SourceLink.GitHub_ version="1.0.0-beta-63102-01" for a .NET Framework 4.0 library project. After build I can't see in the dll the AssemblyInformationalVersion as mentioned in the documentation here. Looking at msbuild diag info I do see  task "Microsoft.Build.Tasks.Git.GetSourceRevisionId" get called and SourceRevisionId was set with a value, but nowhere seeing this get "consumed" by anything. Any suggestions?

Best regards,

Dong

**Comment by tmat** [comment]
Does your project import .NET Core SDK as shows in the example https://github.com/dotnet/sourcelink#using-sourcelink: `<Project Sdk="Microsoft.NET.Sdk">`?

You can still use SourceLink if you can't convert your project to a .NET SDK project but it will require writing custom targets that generate AssmeblyInformationalVersion.

**Comment by xied75** [comment]
@tmat That's what I guessed. This is still a classic .NET Framework project. Moving everything onto the new SDK style is a bit rush and unrealistic. Would it be possible to include this custom target into the main release?
