### ISSUE TITLE
Mirrored repository from one service to another

### ISSUE THREAD

**Issue by LordMike** [dotnet/sourcelink#140]
So. I have a case where I develop and build my source on a Gitlab instance, but I sync the repository to a Github.com account. I'd like my Sourcelink to point to the Github.com repository.

So far, I've gone over the docs a few times, adding and removing the `Microsoft.SourceLink.GitHub` and `Microsoft.SourceLink.GitLab` packages. In all cases, I don't seem to get the Targets files included in my project, due to errors like:

```
..\ReflectedCast.csproj(30,27): error MSB4066: The attribute "Include" in element <SourceLinkGitHubHost> is unrecognized.

..\ReflectedCast.csproj(28,25): error MSB4066: The attribute "Include" in element <SourceLinkGitLabHosts> is unrecognized.

...\ReflectedCast.csproj(30,14): error MSB4066: The attribute "Update" in element <SourceRoot> is unrecognized.

...\ReflectedCast.csproj(31,14): error MSB4066: The attribute "Remove" in element <SourceRoot> is unrecognized.
```

I've messed with f.ex. the unpacked Targets files in my ".nuget" cache folder, and verified that do indeed get read (a syntax error in those files, is also a build error). What I don't get, is how those files can use f.ex. `<SourceRoot ..>`, but I can't.

**Comment by tmat** [comment]
I'm not sure I understand the setup you have. 

What are the URLs printed out when you run `git remote -vv` from the repo that you build? Do they point to github.com or a gitlab server?

Re the syntax errors: `SourceLinkGitHubHost` and `SourceRoot` are item groups, it seems like you are using them in a `PropertyGroup` instead of an `ItemGroup`.

**Comment by LordMike** [comment]
They point to the Gitlab, 

```
$ git remote -v
origin  https://scm.mbwarez.dk/mike/ReflectedCast.git (fetch)
origin  https://scm.mbwarez.dk/mike/ReflectedCast.git (push)
```

Reg. the ItemGroups ... .... You're right. Oh my ...

**Comment by LordMike** [comment]
Ok. So I have the ability to work with sourcelink, now that my blunder has been cleared up.

Now I need to figure out how to use the Github scheme, on a different repo.

**Comment by LordMike** [comment]
I have not been able to tweak the sourcelink generation to my needs. Using binlog, I was able to find out the the Identity of the `SourceRoot` elements was never a URL or a Repository, but rather the local project path. So I should be able to issue `<SourceRoot Update=".." ..´ statements, but they don't seem to catch on.. Perhaps I'm too early in the chain (given that a `<SourceRoot Remove="@(SourceRoot)" />` doesn't work either).

My csproj is as follows:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <Authors>LordMike</Authors>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ReflectedCast</PackageId>
    <Company>MBWarez</Company>
    <Product>ReflectedCast</Product>
    <RepositoryUrl>https://github.com/LordMike/ReflectedCast</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseUrl>https://github.com/LordMike/ReflectedCast/blob/master/LICENSE.txt</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/LordMike/ReflectedCast</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup>
    <!--<SourceRoot Remove="@(SourceRoot)" />
    <SourceRoot Include="https://github.com/LordMike/ReflectedCast/" RepositoryUrl="https://github.com/LordMike/ReflectedCast/"
                SourceControl="git" RevisionId="81862a60e424c1fd2c652603d208beef5fecadd6"
                SourceLinkUrl="https://raw.githubusercontent.com/LordMike/ReflectedCast/81862a60e424c1fd2c652603d208beef5fecadd6/*" />-->

    <SourceLinkGitHubHost Include="scm.mbwarez.dk" ContentUrl="https://raw.githubusercontent.com"/>
    <SourceRoot Update="C:\Users\MichaelBisbjerg\Documents\Git\ReflectedCast\" RepositoryUrl="https://github.com/LordMike/ReflectedCast.git" ScmRepositoryUrl="https://github.com/LordMike/ReflectedCast.git" />

    <PackageReference Include="JetBrains.Annotations" Version="2018.2.1" privateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta-63127-02" PrivateAssets="All" />
    <!--<PackageReference Include="Microsoft.Build.Tasks.Git" Version="1.0.0-beta-63127-02" PrivateAssets="All" />-->
  </ItemGroup>

</Project>
```

**Comment by tmat** [comment]
If I understand this right your repository is on GitLab, where you build it from and you mirror it commit by commit to GitHub?

**Comment by tmat** [comment]
I see. A similar scenario is set up in the integration tests, where we mirror from GitHub to VSTS.

This approach should work for your as well - you'll need to add package references to both GitHub and Gitlab and add a target to your projects similar to this one:

https://github.com/dotnet/sourcelink/blob/master/src/SourceLink.Git.IntegrationTests/VstsAndGitHubTests.cs#L28-L45

**Comment by LordMike** [comment]
Thanks!

I was able to make it work using the custom target, so I've ended up with this:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <Authors>LordMike</Authors>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ReflectedCast</PackageId>
    <Company>MBWarez</Company>
    <Product>ReflectedCast</Product>
    <RepositoryUrl>https://github.com/LordMike/ReflectedCast</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseUrl>https://github.com/LordMike/ReflectedCast/blob/master/LICENSE.txt</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/LordMike/ReflectedCast</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup>
    <SourceLinkGitHubHost Include="scm.mbwarez.dk" />

    <PackageReference Include="JetBrains.Annotations" Version="2018.2.1" privateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta-63127-02" PrivateAssets="All" />
  </ItemGroup>

  <Target Name="UseGithubSourcelinkRoot" AfterTargets="$(SourceControlManagerUrlTranslationTargets)">
    <ItemGroup>
      <SourceRoot Update="@(SourceRoot)">
        <ScmRepositoryUrl>https://github.com/LordMike/ReflectedCast.git</ScmRepositoryUrl>
      </SourceRoot>
    </ItemGroup>
  </Target>

</Project>
```

Note that I didn't need to replace anything dynamic, so the entire regex part has been removed. My issue was always that I was setting the values too soon in the process, or so it seems.

I'll give this a whirl. Thanks ;)

**Comment by LordMike** [comment]
It worked. "sourcelink test" produces an ok on the produced PDB, and I've had a test run of debugging which led me to the sources.

Thanks a lot @tmat !

**Comment by tmat** [comment]
Looking at the test I figured it is missing BeforeTargets:

https://github.com/dotnet/sourcelink/pull/142/commits/620bf735c4f2b9f35b61f77f3e1b59ae11a34d04

You might want to add it to your target as well. It makes sure that the target is executed before the `GenerateSourceLinkFile` target, which consumes the values.

**Comment by tmat** [comment]
Actually, it doesn't work as I would think. Looking into it.

**Comment by tmat** [comment]
This is gonna work better: https://github.com/dotnet/sourcelink/pull/142
