### ISSUE TITLE
Possible to use SourceLink with old csproj?

### ISSUE THREAD

**Issue by Snaaio** [dotnet/sourcelink#145]
If I understand correctly it is required to use the new SDK csproj style for using SourceLink (stated in https://github.com/dotnet/sourcelink/blob/master/docs/README.md#example).

However we are currently using .NET Framework with the old csproj and are migrating (slowly) from NuGet packages.config to PackageReference.

Is it in any way possible to use SourceLink without having to migrate to the new SDK csproj first?

**Comment by xied75** [comment]
It does work, I have classic .NET 4 projects currently working properly.

**Comment by Snaaio** [comment]
Ah that's great news!
Initially I tried but could not get it to work somehow. Would you be so kind as to provide me with an example?

**Comment by xied75** [comment]
Nothing special really, just nuget install with -prerelease?

I also modify my csproj file like this:

```
 <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
```

So that the pdb is embedded inside the dll, then I don't need to do extra things to get the pdb packed into nupkg.

Note: SourceLink only work when you start __Debugging__, F12 does not work currently. This made me think the same as you did before I realized that.

**Comment by xied75** [comment]
If this works please consider closing this.

**Comment by tmat** [comment]
@xied75 Source Link should work for both SDK-style projects (those that import Microsoft.NET.Sdk, e.g. like so: `<Project Sdk="Microsoft.NET.Sdk">`) and classic projects. Some features are only available to the former out-of-the box, but the basic debugging support should work for both regardless of what .NET do they target (.NET Core or desktop .NET Framework).

Please reopen if it doesn't work for you.
