### ISSUE TITLE
Document it changes: AssemblyInformationalVersionAttribute

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/sourcelink#146]
I wasn't caught by surprise when I saw the reported version include +hash.
Unless I'm missing something, this is an undocumented _feature_ which happens to be a bug for me.

I changed from `SourceLink.Create.CommandLine` as to get the `commit` on the `nuspec` file. I was unaware of this side effect.

Is it possible to disable the `AssemblyInformationalVersionAttribute` patching?

**Comment by tmat** [comment]
The feature is [documented](https://github.com/dotnet/sourcelink/tree/master/docs#example). 

You can indeed disable adding the commit sha to the attribute - see https://github.com/dotnet/sourcelink/tree/master/docs#includesourcerevisionininformationalversion

**Comment by bruno-garcia** [comment]
Thanks @tmat 
Missed that part of the doc.
