### ISSUE TITLE
buildCrossTargeting vs. buildMultiTargeting

### ISSUE THREAD

**Issue by bording** [dotnet/sourcelink#151]
Looking at the SourceLink packages, I noticed that they have `buildCrossTargeting` folders. From what I understand, that was renamed to `buildMultiTargeting` (see https://github.com/NuGet/Home/issues/4098).

Is there a reason to be using the older name?

**Comment by tmat** [comment]
No reason, other than consistency with names used by msbuild and Microsoft.NET.Sdk.

**Comment by bording** [comment]
Seems like it would eventually make sense to migrate everything to the newer name for the folder.
