### ISSUE TITLE
"Using SourceLink" in README is confusing

### ISSUE THREAD

**Issue by adamralph** [dotnet/sourcelink#152]
https://github.com/dotnet/sourcelink/tree/85db3fd12168d9c6dcca7e0960c3ae4cec046394#using-sourcelink

```xmls
<!-- Optional: Declare that the Repository URL can be published to NuSpec -->
```

- What does "published to NuSpec" mean? I'm guessing that most people recognise NuSpec as being an alternate method of packaging a project (the default being to use csproj).
- What is the difference between including this element and not including it? Does sourcelink even work without it?

```xml
<!-- Optional: Include PDB in the built .nupkg -->
```

- Is this really optional? Will sourcelink work without it? I don't understand how it could work if the PDBs are not included in the package. 😕

**Comment by dp7g09** [comment]
Extending @adamralph comment,
https://github.com/dotnet/sourcelink/tree/85db3fd12168d9c6dcca7e0960c3ae4cec046394#team-foundation-server

`<SourceLinkTfsGitHost Include="tfs-server-name" VirtualDirectory="tfs"/>`

What are these? Do we have any sample examples please. Can we update the readme please.

I keep getting 
`The value of SourceRoot.RepositoryUrl with identity 'c:\dev\something\' is invalid :'https://onprem-tfsserver/git/something'.`
And I think it is related to invalid value in SourceLinkTfsGitHost element.

And is SourceLink support for .net core only?
Possibly a simple implementation example will be useful.

**Comment by tmat** [comment]
> What does "published to NuSpec" mean? I'm guessing that most people recognise NuSpec as being an alternate method of packaging a project (the default being to use csproj).

It means it will be included in the NuSpec of the packaged generated for the csproj file. Each packages has a nuspec in it, regardless of whether it's been generated from hand-written nuspec file or a csproj file. 

> What is the difference between including this element and not including it? Does sourcelink even work without it?

Yes, SourceLink works with `PublishRepositoryUrl` = `false`. It's an optional setting. It's recommended to include the URL in the nuspec, unless the URL reveals some private information that shouldn't be revealed to the consumers of the package.

> Is this really optional? Will sourcelink work without it? I don't understand how it could work if the PDBs are not included in the package. 

It will work without it provided that the PDB is distributed via another channel, e.g. published to a symbol server.

**Comment by adamralph** [comment]
@tmat thanks for the explanation. I've raised #157 in attempt to clarify the comments.
