### ISSUE TITLE
Microsoft.SourceLink.Bitbucket.Git with ssh source support

### ISSUE THREAD

**Issue by Custodia** [dotnet/sourcelink#153]
It seems like urls are always converted to https when using `Microsoft.SourceLink.Bitbucket.Git`:

https://github.com/ctaggart/SourceLink/blob/0bf49f9f8523582a294ee5de64c945bf08ec4897/SourceLink.Create.CommandLine/BitBucketServerUrlConverter.cs#L23-L26

The problem with this is that it breaks the source link functionality if you are using bitbucket with authentication over ssh. It would be nice to be able to clone sources also over ssh.

**Comment by ctaggart** [comment]
@Custodia SourceLink allows debuggers to download the `source` code over https `links`. Authentication support just shipped with Visual Studio 2017 15.8. What version of VS are you running?

**Comment by tmat** [comment]
@Custodia BTW, https://github.com/ctaggart/SourceLink is not where the sources of Microsoft.SourceLink packages are. They are on https://github.com/dotnet/sourcelink.

As @ctaggart points out the debugger uses HTTP or HTTPS to fetch the sources. It does not clone the repository.

**Comment by Custodia** [comment]
@tmat This is posted on https://github.com/dotnet/sourcelink

I'm aware that it's not possible to fetch individual files over ssh and that that is what this does over https, there is no plan to support cloning the repository then? Cloning the repository is how I initially thought this package works and I think more intuitive and versatile because you don't have to create packages for individual git providers like github/bitbucket. Ofcourse it's more time/disk space consuming though.

Should I create a new issue for cloning support or is this feature not going to be supported?

**Comment by tmat** [comment]
We are not planning to clone the repository at this point.
