### ISSUE TITLE
TFS On-Premises implementation keeps getting invalid RepositoryUrl

### ISSUE THREAD

**Issue by dp7g09** [dotnet/sourcelink#154]
Going through ReadMe about Sourcelink on-premises TFS

https://github.com/dotnet/sourcelink/tree/85db3fd12168d9c6dcca7e0960c3ae4cec046394#team-foundation-server

<SourceLinkTfsGitHost Include="tfs-server-name" VirtualDirectory="tfs"/>

What are valid values for SourceLinkTfsGitHost, Include and VirtualDirectory? A few examples will be useful.

I keep getting
The value of SourceRoot.RepositoryUrl with identity 'c:\dev\something\' is invalid :'https://onprem-tfsserver/git/something'.
And I think it is related to invalid value in SourceLinkTfsGitHost element.

Is it possible to provide a simple working example for this? Thanks.

**Comment by tmat** [comment]
The host is a domain and optionally a port. 
VirtualDirectory is the IIS virtual directory the server is installed on.

For example,

```
<SourceLinkTfsGitHost Include="on-premtfsserver:8080" VirtualDirectory="tfs"/>
```

**Comment by robv8r** [comment]
We use `https`.  The Virtual Directory value wasn't very obvious.  The following works in our environment.

```
  <ItemGroup>
    <SourceLinkTfsGitHost Include="tfs.onpremise.com" VirtualDirectory="/" />
  </ItemGroup>
```

If you're using `http` please see the answer @tmat provided.
