### ISSUE TITLE
HTTP 401 and 404

### ISSUE THREAD

**Issue by gprossliner** [dotnet/sourcelink#156]
Hello!

I'm unable to get the correct urls emitted in my .pdb file.

### Background

Background-Information (all CAPS are replaced with symbolic names):
```
$ git remote -v
origin  https://MYSERVER/tfs/DefaultCollection/MYTEAMPROJECT/_git/MYGITREPOSITORY (fetch)
```

I use the following configuration in .csproj:
```xml
<SourceLinkTfsGitHost Include="MYSERVER" VirtualDirectory="/tfs/DefaultCollection" />
```

When creating a package, the following mapping is emitted in the .pdb:
```
"SOURCEPATH\\*":
"http://MYSERVER/tfs/DefaultCollection/MYTEAMPROJECT/MYGITREPOSITORY /_apis/git/repositories/MYGITREPOSITORY/items?api-version=1.0&versionType=commit&version=c2edeeea193f92f44bdce81c73619bdd84b407bf&path=/*
```

### 401

When I run a "StepInto specifc on a Test-Project, VS asks to download a specific file at URL from the mapping:
```
http://MYSERVER/tfs/DefaultCollection/MYTEAMPROJECT/MYGITREPOSITORY/_apis/git/repositories/MYGITREPOSTITORY/items?api-version=1.0&versionType=commit&version=c2edeeea193f92f44bdce81c73619bdd84b407bf&path=RELFILEPATH

Source Link errors:
ERROR: The request failed with code 401 : "Unauthorized".
```

Why it is Unauthorized? It should work with integrated windows authentication.

### 404

When I copy the URL to a browser, Authenication works, but I get a 404, because the URL seems to be generated incorrectly:
```
404: http://MYSERVER/tfs/DefaultCollection/MYTEAMPROJECT/MYGITREPOSITORY/_apis/...
200: http://MYSERVER/tfs/DefaultCollection/MYTEAMPROJECT/_apis/...
```

I also tried some ContentUrl settings, but the ContentUrl seems just to be prepended at the start of the generated url, resulting in a longer, not shorter one.

Any ideas?
Thanks

**Comment by tmat** [comment]
Could you try to set VirtualDirectory to just ```tfs```, instead of `tfs/DefaultCollection`?
```
<SourceLinkTfsGitHost Include="MYSERVER" VirtualDirectory="tfs" />
```

**Comment by tmat** [comment]
Any luck?

**Comment by xen22** [comment]
@tmat, I am also getting an invalid path generated in the PDB, resulting in 404, with version 1.0.0-beta2-19367-01 of Microsoft.SourceLink.Tfs.Git (see #414 ). This is the same issue as reported here a year ago with the repo name being added incorrectly before "_apis" in the generated path.

**Comment by tmat** [comment]
@gprossliner Is Source Link working for you when you set `VirtualDirectory` to `tfs`?

**Comment by gprossliner** [comment]
Hi! I managed to get around this issue, by embedding the sources directly into the .pdb. As this is superior in my case (debugable internal libraries), I took this route. So I'm not aware of recent changes regarding this issue.

See:
https://github.com/dotnet/sourcelink/blob/master/docs/README.md#embedallsources
