### ISSUE TITLE
Does sourcelink work with dotnet pack plus a nuspec file?

### ISSUE THREAD

**Issue by adamralph** [dotnet/sourcelink#158]
I create my package using `dotnet pack my.csproj`, but I need to use a nuspec file by including the `<NuspecFile>` element inside the `csproj` file. I've already noticed that `<PublishRepositoryUrl>` has no effect on the resulting nuget package. Does sourcelink even work at all in this scenario?

**Comment by adamralph** [comment]
@bording yes, I'm doing something similar: https://github.com/xbehave/xbehave.net/blob/b8f2c19d4a2466723dd0f919815208ce6a6c0249/src/Xbehave.Core/Xbehave.Core.csproj#L8-L9

@tmat thanks for the info. I guess I can get the `<repository>` element working fairly easily then. I was more concerned about whether sourcelink even works fundamentally in this scenario, i.e. does it even do it's work on the PDB? I guess the answer to that is yes. I haven't tested it yet, since that's a bit involved, but I'll do so ASAP.

**Comment by adamralph** [comment]
Good news! I managed to get everything working: https://github.com/xbehave/xbehave.net/pull/469/files

Thanks for all the help!

**Comment by christcottrell** [comment]
This is really old, but this is exactly what I needed! Hope it still works!

**Comment by christcottrell** [comment]
By the way, it didn't seem to work for anyone who reads this later. Support for a nuspec file doesn't seem to be there for Source Link.
