### ISSUE TITLE
Using SourceLink without .git directory

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/sourcelink#159]
From what I understand, the information for the remotes is being determined based on the .git directory. However, I am trying to keep my build agents "clean" by not moving the .git stuff there. I do have the commit id and remote repository url though in the variables.

Is there a way to manually override the values (e.g. a manual or command-line version) of the tooling? The only downside I foresee is that it cannot automatically translate urls from public url to raw file urls, but I can deal with that myself as well.

**Comment by Meberem** [comment]
@tmat I am in a similar situation where I do not have the remote URL in the git config. I tried the sample you provided and I get the same error message that @andrewlock encountered. I have tried various settings, changes, tweaks, etc. to no avail, would you be able to provide us some guidance with this?

**Comment by ChristianSauer** [comment]
Was there any conclusion to this?

**Comment by GeertvanHorrik** [comment]
Today I am beginning to re-investigate this. I have written a Cake build script that automatically injects the package reference and sets the required data. You can find the script here:

https://github.com/WildGums/Orc.Analytics/blob/develop/deployment/cake/components-tasks.cake#L152

During the build, I get these warnings:

```
C:\Users\geert\.nuget\packages\microsoft.sourcelink.common\1.0.0-beta-63127-02\build\Microsoft.SourceLink.Common.targets(40,5): warning : No SourceRoot i
tems specified - the generated source link is empty. [C:\Source\orc.analytics\src\Orc.Analytics\Orc.Analytics.csproj]
```

Yet it has updated my csproj correctly:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta-63127-02" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <SourceRoot Include="C:\Source\orc.analytics\" RepositoryUrl="https://github.com/WildGums/Orc.Analytics" />
  </ItemGroup>
```

In my package, it seems to embed the info correctly:

![image](https://user-images.githubusercontent.com/1246444/49867853-01ea6000-fe0c-11e8-805c-98c62cc38028.png)

Then I check the pdb files using SourceLink, and I get this output:

```
sourcelink print-json .\Orc.Analytics.pdb
{"documents":{}}
```

Any points on what could be going wrong? Could it be the wrong pdb type, or ?

This is all open source, so to repro:

1) Clone the repository
2) In the root, run this in powershell: 
```
.\build.ps1 -target buildandpackage
```

**Comment by GeertvanHorrik** [comment]
Looks like I should not mess with SourceRoot at all. Leaving it away results in valid documents, so it looks like it's working with the dynamic stuff :)

**Comment by GeertvanHorrik** [comment]
Not sure yet, looks like the tests fail:

![image](https://user-images.githubusercontent.com/1246444/49868349-7d004600-fe0d-11e8-91c2-89c75769535f.png)

**Comment by GeertvanHorrik** [comment]
The ms build log in diagnostic mode shows this:

```
SourceLinkGitHubHost
    github.com
        ContentUrl = https://raw.githubusercontent.com
SourceRoot
    C:\Source\orc.analytics\
        RepositoryUrl = https://github.com/WildGums/Orc.Analytics
```

Will try to figure out why it doesn't pick it up.

**Comment by GeertvanHorrik** [comment]
More logging info:

```
Target "InitializeSourceRootMappedPaths: (TargetId:77)" in file "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.Managed.Core.targets" from project "C:\Source\orc.analytics\src\Orc.Analytics\Orc.Analytics.csproj" (target "_InitializeSourceRootMappedPathsOpt" depends on it):
Using "Microsoft.CodeAnalysis.BuildTasks.MapSourceRoots" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll".
Task "Microsoft.CodeAnalysis.BuildTasks.MapSourceRoots" (TaskId:40)
  Task Parameter:
      SourceRoots=
          C:\Source\orc.analytics\
                  RepositoryUrl=https://github.com/WildGums/Orc.Analytics (TaskId:40)
  Output Item(s): 
      _MappedSourceRoot=
          C:\Source\orc.analytics\
                  MappedPath=C:\Source\orc.analytics\
                  RepositoryUrl=https://github.com/WildGums/Orc.Analytics (TaskId:40)
Done executing task "Microsoft.CodeAnalysis.BuildTasks.MapSourceRoots". (TaskId:40)
Removed Item(s): 
    SourceRoot=
        C:\Source\orc.analytics\
                RepositoryUrl=https://github.com/WildGums/Orc.Analytics
Added Item(s): 
    SourceRoot=
        C:\Source\orc.analytics\
                MappedPath=C:\Source\orc.analytics\
                RepositoryUrl=https://github.com/WildGums/Orc.Analytics
Done building target "InitializeSourceRootMappedPaths" in project "Orc.Analytics.csproj".: (TargetId:77)
```

**Comment by GeertvanHorrik** [comment]
This is getting interesting. When I look in the source code for `Microsoft.SourceLink.Common`, and don't append the SourceRoot with a `\`, I get an error:

```
<SourceRoot Include="C:\Source\orc.analytics" RepositoryUrl="https://github.com/WildGums/Orc.Analytics" />
```

results in 

```
Task "Microsoft.CodeAnalysis.BuildTasks.MapSourceRoots" (TaskId:40)
  Task Parameter:
      SourceRoots=
          C:\Source\orc.analytics
                  RepositoryUrl=https://github.com/WildGums/Orc.Analytics (TaskId:40)
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.Managed.Core.targets(90,5): error : SourceRoot paths are required to end with a slash or backslash: 'C:\Source\orc.analytics' [C:\Source\orc.analytics\src\Orc.Analytics\Orc.Analytics.csproj]
  Output Item(s): _MappedSourceRoot= (TaskId:40)
```

So the source roots are correctly recognized. Maybe I will just for and see how the task behaves locally.

**Comment by GeertvanHorrik** [comment]
Debugger attached, source root is specified:

![image](https://user-images.githubusercontent.com/1246444/49872049-2d734780-fe18-11e8-8365-f69014da29f1.png)

**Comment by GeertvanHorrik** [comment]
Got it working :-)

We need to specify some additional properties (figured out by decompiling `Microsoft.SourceLink.GitHub.dll`):

* SourceControl
* RevisionId

When I (dynamically) add this to my csproj:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta-63127-02" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <SourceRoot Include="C:\Source\orc.analytics\" RepositoryUrl="https://github.com/WildGums/Orc.Analytics" SourceControl="git" RevisionId="72b62c068c649df27c2e85c7bb78c3edd4616d9b" />
  </ItemGroup>
```

It all works:

![image](https://user-images.githubusercontent.com/1246444/49872709-382edc00-fe1a-11e8-926e-a8a1da71ee08.png)

@tmat , why isn't the tooling falling back to the `RepositoryType` & `RevisionId` properties that NuGet (Dotnet pack) seems to understand just fine?

To view the latest (working) scripts, see this url:

https://github.com/WildGums/Orc.Analytics/blob/develop/deployment/cake/components-tasks.cake#L208

**Comment by tmat** [comment]
I have documented the minimal required content of `.git` directory here:
https://github.com/dotnet/sourcelink/blob/master/docs/README.md#minimal-git-repository-metadata

If you want to avoid copying the full content of `.git` directory you can supply the necessary information to Source Link by creating `HEAD` and `config` file as described in the [doc](https://github.com/dotnet/sourcelink/blob/master/docs/README.md#minimal-git-repository-metadata).

Note: For Source Link version 1.0.0-beta2-19270-01 and lower empty directories `objects` and `refs` are also required under `.git` directory. Newer Source Link packages will not require them.

**Comment by dotMorten** [comment]
It's also rather problematic when people use the zip-download to grab your repo, and it won't compile because the .git folder is missing. I'm going to make the package reference conditional based on whether the folder exists, but I'd think this would be a common scenario for anyone downloading your repo (in which case you just want to disable sourcelinking).

**Comment by GeertvanHorrik** [comment]
@dotMorten I've created cakebuild scripts that automatically inject it whenever a release build is done (via cake). So this should actually only happen on build servers / agents and never by an end-user that clones the repository (so the repository is clean, it will be injected when required). So far that has worked out great, maybe you can do something similar in your situation.
