### ISSUE TITLE
The value of SourceRoot.RepositoryUrl with identity is invalid	

### ISSUE THREAD

**Issue by leotsarev** [dotnet/sourcelink#162]
Using Microsoft.SourceLink.Vsts.Git I got following error 
```
The value of SourceRoot.RepositoryUrl with identity 'C:\Users\leonid.tsarev\Source\Repos\Common\' is invalid: 'https://monopoly-dev.visualstudio.com/_git/Common'	
```
What's wrong with my repository url?

I'm using `Microsoft.SourceLink.Vsts.Git Version="1.0.0-beta-63127-02"`

**Comment by rfellers** [comment]
I'm seeing the same error with the same version of `Microsoft.SourceLink.Vsts.Git`. I tried some suggestions from #159 but wasn't able to get this working.

**Comment by tjdaniel** [comment]
It seems that the issue only occurs while building locally/on prem (dotnet build or vs). Works fine in VSTS build tasks.

**Comment by rfellers** [comment]
I am using VSTS (Azure DevOps). I was able to work around this error by changing my origin fetch/push URL format (in Team Explorer -> Settings -> Repository Settings) from `https://account.visualstudio.com/_git/repo` to 
`https://account.visualstudio.com/repo/_git/repo`.

The RepoOnly() unit test in GetSourceLinkUrlTests.cs clued me into this. Although, it seems like both versions should be valid for VSTS ...

**Comment by tjdaniel** [comment]
> `https://account.visualstudio.com/repo/_git/repo`

It may confuses, when project name equals repo name. It should read then:

`https://account.visualstudio.com/<project>/_git/<repo>`
