### ISSUE TITLE
Cannot find package PDB file when running as a unit test or console app

### ISSUE THREAD

**Issue by tfadler** [dotnet/sourcelink#163]
This may be a mistake on my end.

Environment: 
- Visual Studio 15.8.2
- .Net SDK 2.1.401
- xunit 2.4.0
- xunit.runner.visualstudio 2.4.0

Notable VS Settings Tools -> Options -> Debugging
- Disabled Enable Just My Code
- Enable Source Link Support
- Fall back to Git Credential Manager authentication for all Source Link requests
- Enable Source Server Support
- Print source server diagnostic messages to Output window

My SourceLink settings on my package:
`<PublishRepositoryUrl>true</PublishRepositoryUrl> `
`<EmbedUntrackedSources>true</EmbedUntrackedSources> `
`<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>`

And 
`
<PackageReference Include="Microsoft.SourceLink.Bitbucket.Git" Version="1.0.0-beta-63127-02">`

**Good News:**

When I run my ASP.Net Core application in debug and look at the Modules dialog it loads the PDB for my package seamlessly!  Stepping into the code works great too!

Here is the Symbol Load Information

`C:\Program Files\dotnet\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\Users\USERNAME\.nuget\packages\companyname.shared.utilstemp\1.0.17\lib\netcoreapp2.1\CompanyName.Shared.UtilsTemp.pdb: Symbols loaded.
`

**My problem:**

When run unit tests in debug and look at the Modules dialog it does not load the PDB and cannot find it without help (browsing to the pdb file manually).

Here is the Symbol Load Information:

`C:\Program Files\dotnet\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\Projects\Manager\tests\AssetTest\bin\Debug\netcoreapp2.1\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\Projects\SharedTools\src\UtilsTemp\obj\Release\netcoreapp2.1\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\WINDOWS\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\WINDOWS\symbols\dll\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\WINDOWS\dll\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\Users\USERNAME~1\AppData\Local\Temp\SymbolCache\CompanyName.Shared.UtilsTemp.pdb\971694d6c8ad48b2a8822afe53830e2effffffff\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\Users\USERNAME~1\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\CompanyName.Shared.UtilsTemp.pdb\971694d6c8ad48b2a8822afe53830e2effffffff\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\Users\USERNAME~1\AppData\Local\Temp\SymbolCache\CompanyName.Shared.UtilsTemp.pdb\971694d6c8ad48b2a8822afe53830e2e1\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
C:\Users\USERNAME~1\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\CompanyName.Shared.UtilsTemp.pdb\971694d6c8ad48b2a8822afe53830e2e1\CompanyName.Shared.UtilsTemp.pdb: Cannot find or open the PDB file.
`

For reasons I can not figure out when running as a unit test the files in .nuget\packages are not checked.

Thoughts?  

Any help would be welcomed.

**Comment by AArnott** [comment]
I hit this as well, except instead of a unit test it was a trivially simple console app. I guess the resolve package reference step only copies the .DLL from the package to the application's bin folder, and leaves the .pdb behind in the user package cache location where the debugger won't find it.

What am I missing? Do I really have to add custom build authoring to my package to copy the .pdb to the app bin folder?

**Comment by AArnott** [comment]
Just a note, this can stop reproing for a given package version after helping the debugger once, since the debugger stores the path that the user manually points it to so that it can be used next time, but this is specific to a package ID+version, so it's not a good workaround.

**Comment by AArnott** [comment]
I found [this doc](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/debugging-with-symbols-and-sources.md) which includes this guidance for the build system: 

> If a code binary is copied to a location, also copy the symbol file to the same location. In most cases, this will be to the application bin directory.

Obviously this bit isn't (yet?) being followed for .NET Framework targeted applications.

**Comment by AArnott** [comment]
@tmat is this a known issue?

**Comment by tmat** [comment]
Seems like this is the issue: https://github.com/dotnet/sdk/issues/1458

**Comment by tmat** [comment]
Tracked in .NET Core SDK repo.
