### ISSUE TITLE
Azure DevOps is unable to convert OriginalUrl

### ISSUE THREAD

**Issue by ppumkin** [dotnet/sourcelink#166]
I have (Dotnet Standard 2.0) project with
 - SourceLink.Create.CommandLine 2.8.3
- Microsoft.SourceLink.Vsts.Git beta-63127-02 

When I build in VS or run the command

`dotnet build` (with out  /p:SourceLinkCreate=true) it builds and generates the `*.sourcelink.json` in the correct obj directory

If I do however run locally  `dotnet build /p:SourceLinkCreate=true` it throws the error as below

When I do the same on Azure DevOps pipeline. The same dotnet build version. 

2018-09-14T11:15:31.5783772Z ==============================================================================
2018-09-14T11:15:31.5783772Z Task         : .NET Core
2018-09-14T11:15:31.5783772Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
2018-09-14T11:15:31.5783772Z Version      : 2.139.8
2018-09-14T11:15:31.5783772Z Author       : Microsoft Corporation
2018-09-14T11:15:31.5783772Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2018-09-14T11:15:31.5783772Z ==============================================================================
2018-09-14T11:15:35.2190721Z [command]C:\Windows\system32\chcp.com 65001
2018-09-14T11:15:35.2190721Z Active code page: 65001
2018-09-14T11:15:35.2190721Z [command]C:\agent\_work\_tool\dncs\2.1.300\x64\dotnet.exe build
2018-09-14T11:15:35.2190721Z Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
2018-09-14T11:15:35.2190721Z Copyright (C) Microsoft Corporation. All rights reserved.

The exact same version on my local machine

I get the error on Azure

`C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\sourcelink.create.commandline\2.8.3\build\SourceLink.Create.CommandLine.targets(30,5): error : unable to convert OriginUrl: https://{private}.visualstudio.com/dotNET%20Project/_git/company.cqrslite [C:\agent\_work\34\s\company.CQRSlite\company.CQRSlite.csproj]`

Also when I try to disable source linking in Azure

dotnet test /p:SourceLinkCreate=false (OK- Builds without source linking on Test projects)
dotnet pack /p:SourceLinkCreate=false  (FAIL - I need to specify SourceLinkCreate=false in additional build properties)
pulbish symbol path - Doesnt need adjustment 

-EDIT
After using the /p:SourceLinkCreate=false on my build server.. I now am getting the screen in Visual Studio to download source files when I hit a handled exception.. What is going on???

**Comment by ppumkin** [comment]
Could this be related to nuget not puliing beta packages on Azure DevOps?

Now on the project I have downaloded the my latest NuGet with the vsts.git dependency i get the error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependency 'Microsoft.SourceLink.Vsts.Git'. Source(s) used: 'nuget.org', 'Kinder', 'Microsoft Visual Studio Offline Packages'.			0	
```

It shows under dependency

![image](https://user-images.githubusercontent.com/1249683/45548976-06f43f00-b81e-11e8-925d-b3e5104f2a9f.png)
 

Does this dependency really need to be handed down to all other projects wanting to use this?

**Comment by tmat** [comment]
Could you try to remove `SourceLink.Create.CommandLine 2.8.3`? The only package reference you need to get SoruceLink working for Azure DevOps hosted repo is `Microsoft.SourceLink.Vsts.Git`. See https://github.com/dotnet/sourcelink#visual-studio-team-services

**Comment by ppumkin** [comment]
Yes - I never realised that I did NOT need the command line one.  I did read that line and assumed to not use the legacy integration ones but the new integration packages. I just thought the command line one was still required for CI build.

I raised a PR (Sorry I don't know how to automatically link PR to issues) 

https://github.com/dotnet/sourcelink/pull/170

**Comment by leqii-com** [comment]
hi, all.
我用jenkins 构建时候，提示如下错误，Tell me why？Can you help me?

 dotnet build
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/var/lib/jenkins/.nuget/packages/sourcelink.create.commandline/2.8.3/build/SourceLink.Create.CommandLine.targets(30,5): error : unable to convert OriginUrl: git@*****************:pandagp/pandaiot.git [/data/jenkins/workspace/autobuild_iotapi.*****.com/src/abpsrc/framework/src/Volo.Abp.Core/Volo.Abp.Core.csproj]

Build FAILED.

**Comment by leqii-com** [comment]
@tmat @ppumkin @ctaggart  help
