### ISSUE TITLE
Add support for iOS, Android and WebAssembly

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/sourcelink#168]
While it currently is possible to add SourceLink information into portable PDBs in (Xamarin.iOS, Xamarin.Android and WebAssembly](https://github.com/nventive/Uno/blob/8f92006851ffd21dc7c78fb5afd34c21a6ae8cea/src/Directory.Build.props#L51) projects, the Visual Studio Xamarin debugger is not using those informations to provide source code when debugging a published nuget package.

This issue is related to https://github.com/dotnet/sourcelink/issues/144 and the complexity involved into debugging published nuget packages.

**Comment by tmat** [comment]
@jamesmontemagno Is there is an issue filed on Mono Debugger to support Source Link?

**Comment by jeromelaban** [comment]
@tmat I mentioned this issue to @joj, he acknowledged it, but I don't where that went afterwards.

**Comment by joj** [comment]
This is on our side of the house, not on dotnet. We have it on the backlog.

**Comment by jeromelaban** [comment]
Thanks @joj! Is this something that can be tracked publicly?

**Comment by joj** [comment]
No, sorry. The mono debugger is not open source, and we track user stories and bugs for non open-source projects in our internal tracker.

**Comment by knocte** [comment]
Mono Debugger not opensource? https://github.com/mono/sdb

I thought that the one that is not opensource is the .NET Core one.

**Comment by knocte** [comment]
So, is SourceLink for Xamarin in the roadmap? Is there an item in https://developercommunity.visualstudio.com tracking this?

**Comment by joj** [comment]
No, we track issues for the debugger integration internally. That said, there is a new feature in developer community for suggestions. If you want to open a suggestion and link it here I'll follow up on interest to move the priority of our internal item. Supporting source link is not a minor effort and it may impact performance slightly. We're considering it but carefully.

**Comment by jimbernstein** [comment]
Please go and vote for this Developer Community suggestion: https://developercommunity.visualstudio.com/idea/649946/add-source-link-support-when-debugging-xamarin-app.html

**Comment by jamesmontemagno** [comment]
Looks like it is supported in VS for Mac now :) <3

**Comment by tranb3r** [comment]
Any progress ? Is there any plan to support source link for xamarin in visual studio 2019 ?
