### ISSUE TITLE
Support to view source code

### ISSUE THREAD

**Issue by HaoLife** [dotnet/sourcelink#169]
Is it possible to support viewing the source code, similar to Java's download sources.

**Comment by tmat** [comment]
@chuckries

**Comment by chuckries** [comment]
@HaoLife Can you explain what Java's download sources is? Source Link allows C# debugger (such as Visual Studio) to download source code during a debug session.

**Comment by ctaggart** [comment]
@chuckries It should also be possible in Visual Studio to "Navigate to Source" or something along those lines from the editor. Visual F# Power Tools added this feature back in SourceLink v1 (source indexing) days. https://fsprojects.github.io/VisualFSharpPowerTools/navigatetosource.html

Before that, ReSharper also had the ability to view the source from the Object Browser if symbols were available and source indexing was set up.

These would be awesome to see in Visual Studio. I'd prefer the source be brought up directing in Visual Studio. @HaoLife, is this kind of what you are looking for?

**Comment by tmat** [comment]
SourceLink support for Go To Definition is tracked here: https://github.com/dotnet/roslyn/issues/24349

**Comment by HaoLife** [comment]
@ctaggart Yes, we need a tool that navigates directly to the source in the IDE so that we can analyze the underlying implementation and debug the current code directly at run time.
Java in the IDE to download the source code, can be directly in the current project to view the source code, such as the JDK source code, observe these implementations, can improve their development capabilities, and. NET to view the source code is complex, we need to use the Anti-compilation tool (Ilspy) or from git to get the source code

I think it has a positive effect on the development of the community and can benefit more. NET Developers

**Comment by athinboy** [comment]
https://github.com/dotnet/sourcelink

**Comment by athinboy** [comment]
oh my god! It is true, definitely true!  It is so obviously!

"
@chuckries Java in the IDE to download the source code, can be directly in the current project to view the source code, such as the JDK source code, observe these implementations, **### can improve their development capabilities, and. NET to view the source code is complex,** we need to use the Anti-compilation tool (Ilspy) or from git to get the source code

I think it has a positive effect on the development of the community and can benefit more. NET Developers

"

**Comment by tmat** [comment]
Closing as external to Source Link - once the library has Source Link or embedded sources, the IDEs can certainly provide a rich source browsing experience.
