### ISSUE TITLE
Unable to locate repository with --no-build

### ISSUE THREAD

**Issue by ctaggart** [dotnet/sourcelink#173]
I wasn't expecting to run into this error with `--no-build` specified.
```
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error : Unable to locate repository containing directory '/src'. [/src/Deadbolt-Net.fsproj]
```

It fails because the `.git` folder isn't mounted:
``` bash
cd $HOME/ProjectName
docker run --rm -v $PWD:/src -w /src \
    microsoft/dotnet:2.1-sdk /bin/bash -ec \
    "dotnet restore; dotnet pack --no-build -c Release /p:Version=${VERSION}"
```

Easy workaround:
``` bash
cd $HOME
docker run --rm -v $PWD:/src -w /src \
    microsoft/dotnet:2.1-sdk /bin/bash -ec \
    "cd ProjectName; dotnet restore; dotnet pack --no-build -c Release /p:Version=${VERSION}"
```

**Comment by tmat** [comment]
Can you pass `/bl:log.binlog` and share it? You can check in the log what is triggering `InitializeSourceControlInformation` target.

**Comment by tmat** [comment]
>  It is likely NuGet Pack target which is trying to get commit sha and repository url to store in NuSpec.

Assuming this is the case I'm gonna close this as "by-design".
