### ISSUE TITLE
SourceRoot.SourceLinkUrl is empty?

### ISSUE THREAD

**Issue by twann503** [dotnet/sourcelink#174]
I'm confused on how to set this up. So my repo is a VSTS git and I installed the sourcelink nuget package for my project, but once I build it, it displays SourceRoot.SourceLinkUrl is empty. I do not see this mentioned anywhere on the readme can anyone clarify?

**Comment by tmat** [comment]
can you run `msbuild /bl:log.binlog MyProj.csproj` from command line and share the log file?

**Comment by twann503** [comment]
Ah nevermind, I solved the issue.
