### ISSUE TITLE
Source Link errors: This request was sent without authentication

### ISSUE THREAD

**Issue by twann503** [dotnet/sourcelink#176]
So i'm getting this error, is there a way to make the source link tool to pass the authentication when requesting for the source file? My visual studio has access to this since it has the required certs used for cloning a repo.

An embedded document was not found.
Looking for source using Source Link (https://tfs.... this path is correct)
Source Link errors:
This request was sent without authentication. If the server requires authentication, this may be the reason why the request fails.
ERROR: The request failed with code 401 : "Unauthorized".

**Comment by tmat** [comment]
What version of VS do you have?

@chuckries

**Comment by twann503** [comment]
Professional 2017, 15.8.5

**Comment by Igorbek** [comment]
I am also experiencing difficulties in stepping into sources of nuget libs conatining SourceLink information.

Verified with the following:
- visual studio enterprise 15.8.5
- nuget contains pdb
- pdb is correctly loaded
- pdb contains sourcelink document
- sourcelink info is pecked up by visual studio
- sources are on https://dev.azure.com
- **here -->** visual studio is unable to retreive content from git repo. the error is `Source Link Error: git-credential-manager.exe: Could not obtain credentials. Process failed with exit code -1. ERROR: The request failed with code 401 : "Unauthorized". Source Link URL: https://dev.azure.com/...`
- the 'authenticate' link is used and credentials enetered correctly. it has no effect on the result - same session and any other next sessions also fail to get sources
- the source url is correctly loading if I open it up in the browser, after manual authentication
- devops account also is entered into visual studio

**Comment by ctaggart** [comment]
The version of Git & GCMW may also be helpful. See https://github.com/dotnet/sourcelink/issues/175#issuecomment-424444395

**Comment by Igorbek** [comment]
@ctaggart yes, I just have seen the same comment and updated GCMW, then restarted VS and result is the same.

- `git version 2.17.1.windows.2`
- `Git Credential Manager for Windows version 1.17.2`

**Comment by axelheer** [comment]
Same problem here.

I've just noticed that Visual Studio / git stores the git credentials for our on-prem TFS under the correct port without any explicit username and it just works. But using SourceLink safes the credentials without our port but with username and it won't work.

![image](https://user-images.githubusercontent.com/3988385/46279884-a9285c80-c56a-11e8-9dc6-11562aae569b.png)

- I deleted both credentials
- Did a git sync, which created the 8443 credentials
- Tried to debug using SourceLink, which created the other credential entry

No idea, what that may or may not mean...

**Comment by jeroenlandheer** [comment]
Same issues here. Using a TFS On premise, on HTTPS. GCM is set to 'Integrated' authentication, which works fine for all the other git tools, but not for Source Link in Visual Studio 2017.8.6

`git-credential-manager.exe: Could not obtain credentials. Unexpected output: 'protocol=https
host=___________________
path=
username=
password=
ERROR: The request failed with code 401 : "Unauthorized".`

git version 2.17.1.windows.2
Git Credential Manager for Windows version 1.18.0

We use 
`git config --global credential.[our-server-name-here].authority Integrated`
for configuring GCM

**Comment by ohelin2** [comment]
Same issue for us with TFS-On premise with https. I tried to clear credentials in the "Credentials Manager".
But I get this 
```
Source Link Error:
git-credential-manager.exe: Could not obtain credentials. Process failed with exit code -1.
ERROR: The request failed with code 401 : "Unauthorized".
```
The generated link works fine in browser (even if I get an certificate issue and I have to accept an unsecure website).
The link to force enter credentials prompts an authentication popup but after validating my credentials nothing appears.

My Visual Studio 2017 version is 15.8.1

**Comment by chuckries** [comment]
@axelheer is the port included in the sourcelink.json URLs that gets created at build time?

**Comment by axelheer** [comment]
@chuckries  our TFS Admin changed the default URL to use the default port on friday...

Now I just get:

```
You need to find ... to view the source for the current call stack frame

Source Link Error:
git-credential-manager.exe: Could not obtain credentials. Unexpected output: 'protocol=https

host=***
path=
username=

password=


'.
ERROR: The request failed with code 401 : "Unauthorized".

Source Link URL: ...
```

**Comment by chuckries** [comment]
Unless you have censored the output, it looks like GCM is outputting an empty username as well as password. This is an error condition for sourcelink auth as there are no creds to send. You may try wiping out the creds for your domain in the Windows Credential Manager and trying Source Link again.

**Comment by axelheer** [comment]
Wiping credential manager does not help.

Why is the the GCM necessary here anyway? The SourceLink URL is an ordinary http link, which works fine when pasting it into any browser (Integrated Windows Authentication)...

**Comment by zplan** [comment]
> @chuckries our TFS Admin changed the default URL to use the default port on friday...
> 
> Now I just get:
> 
> ```
> You need to find ... to view the source for the current call stack frame
> 
> Source Link Error:
> git-credential-manager.exe: Could not obtain credentials. Unexpected output: 'protocol=https
> 
> host=***
> path=
> username=
> 
> password=
> 
> 
> '.
> ERROR: The request failed with code 401 : "Unauthorized".
> 
> Source Link URL: ...
> ```

I have exactly the same issue with our tfs on prem.
Visual Studio Version 15.8.8

Any news?

**Comment by zplan** [comment]
@axelheer : thanks for the fast reply.

I hope someone of the repo members is working on it. It would already be ok to have a messagebox before downloading to enter the credentials.

**Comment by ohelin2** [comment]
I agree with @axelheer I don't understand why GCM is required while the links to source code files work in browser. Moreover I would like to know if someone is working on it.
Thanks

**Comment by tmat** [comment]
@chuckries Any updates?

**Comment by chuckries** [comment]
To anybody facing this issue, VS 16.1 Preview 2 now supports Windows Authentication for on prem TFS and other scenarios, please try it out. I am closing this issue as I believe it is fixed, please file a new issue for other authentication issues.
