### ISSUE TITLE
SourceLink .NET Framework

### ISSUE THREAD

**Issue by twann503** [dotnet/sourcelink#177]
I've been looking through all the documentation but cant really figure out how to make source link work with projects with target framework that are .net framework 4.x.x , I got the source link to work with .net standard.

How do I make it work with .net framework? I read this [post ](https://github.com/ctaggart/SourceLink/issues/155) but somewhat confused.

My current config on source link in the .csproj file are:

>   <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.Tfs.Git" Version="1.0.0-*" PrivateAssets="All" />
    <SourceLinkTfsGitHost Include="tfs.xx.xx.xx" VirtualDirectory="tfs" />
  </ItemGroup>
  <PropertyGroup>
    

> `<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>`

    <EmbedAllSources>true</EmbedAllSources>
  </PropertyGroup>

Again it works perfectly for .net standard but on my other projects with .net framework 4 it does not want to work.

**Comment by paulomorgado** [comment]
@twann503, do you really mean .NET Framework and .NET Standard or "traditional" .csproj and SDK .csproj?

**Comment by tmat** [comment]
@twann503 Source Link should work for both SDK-style projects (those that import Microsoft.NET.Sdk, e.g. like so: `<Project Sdk="Microsoft.NET.Sdk">`) and classic projects. Some features are only available to the former out-of-the box, but the basic debugging support should work for both regardless of what .NET do they target (.NET Core or desktop .NET Framework).

Can you be more specific about what does not work in your project?
