### ISSUE TITLE
EmbedUntrackedSources not honoured for F# projects on GitHub

### ISSUE THREAD

**Issue by SteveGilham** [dotnet/sourcelink#181]
I have a project that includes a build-time generated (and untracked) file of the form
```
namespace MyNameSpace
module SolutionRoot =
  let location = """some/file/path"""
```
which is located at `some\file\path\_Generated\SolutionRoot.fs`

If I build the project with SourceLink (`Microsoft.SourceLink.GitHub Version="1.0.0-beta-63127-02"`) and `<EmbedUntrackedSources>true</EmbedUntrackedSources>` the untracked file is not detected as such, but is linked by URL instead along with all the others that generate symbols.  So when I invoke the `sourcelink` global tool on the symbols with option `test`, I get  `error: url failed NotFound: Not Found` when it tries to locate this untracked file in GitHub at the url `_Generated\SolutionRoot.fs` relative to the current commit root.

Using `EmbedAllSources` instead does embed every file that generates symbols, including this one, and `sourcelink test` passes.

I am assuming that as the F# compiler is source-control agnostic, the issue lies somewhere on the SourceLink side.

**Comment by tmat** [comment]
Could you please run `msbuild /bl:log.binlog proj.fsproj` and share the resulting log file?

**Comment by tmat** [comment]
Also, what's the content of `.gitignore` file? SourceLink determines untracked files based on `.gitignore`.

**Comment by SteveGilham** [comment]
Zipped binlog -- [log.zip](https://github.com/dotnet/sourcelink/files/2431814/log.zip)
Zipped .gitignore -- [gitignore.zip](https://github.com/dotnet/sourcelink/files/2431816/gitignore.zip) : the appropriate line of the latter would be `_*/` 

A C# project in this solution happily processes a FAKE generated assembly version file with path `_Generated/AssemblyVersion.cs` as a file to embed under these circumstances (the equivalent  `_Generated/AssemblyVersion.fs`  is a total no-show because all the `[<Literal>]` values compile with the ` [DebuggerBrowsable(DebuggerBrowsableState.Never)]` attribute)

**Comment by tmat** [comment]
The log shows that SourceLink identifies correctly the files that need to be embedded:

![image](https://user-images.githubusercontent.com/41759/46261506-55097380-c4a9-11e8-8d7b-1342054c2c70.png)

It seems however that the F# build targets do not read the `EmbeddedFiles` items. I believe this has been fixed recently in F#: https://github.com/Microsoft/visualfsharp/issues/4075. Do you have the latest build?

**Comment by SteveGilham** [comment]
Just at the moment _all_ the d/l links from that page are giving me 404's like this
![untitled](https://user-images.githubusercontent.com/7460854/46275824-2c8b8300-c556-11e8-8194-f5fb2f489c7a.png)  I will try again in a few hours.

By running with EmbedAllSources, I see from the .binlog that this option works through a completely different channel, so it's not surprising that we have an inconsistency in behaviour.

**Comment by saul** [comment]
@tmat - completely unrelated but what tool are you using to produce the screenshot above? Looks very useful for MSBuild debugging

**Comment by bording** [comment]
@saul You can get it from http://msbuildlog.com/
