### ISSUE TITLE
Deterministic paths not generated for F# projects

### ISSUE THREAD

**Issue by SteveGilham** [dotnet/sourcelink#182]
Having set
```
    <ContinuousIntegrationBuild Condition="'$(APPVEYOR)'=='True'">true</ContinuousIntegrationBuild>
    <DeterministicSourcePaths Condition="'$(APPVEYOR)'=='True'">true</DeterministicSourcePaths>
```
in both .fsproj and .csproj projects in the same solution and performed a build on AppVeyor, the resulting .pdb files contain paths of the form `/_/path/to/file.cs` for C# projects, but `C:\projects\project-name\path\to\file.fs` for the F# projects

**Comment by tmat** [comment]
F# doesn't currently support deterministic source paths: https://github.com/Microsoft/visualfsharp/issues/3812

**Comment by tmat** [comment]
@KevinRansom FYI

**Comment by tmat** [comment]
CLosing as this feature is tracked in F# repository.

**Comment by saul** [comment]
PR for this: https://github.com/Microsoft/visualfsharp/pull/5801
