### ISSUE TITLE
If using CopyLocalLockFileAssemblies - sourcelink doesn't work

### ISSUE THREAD

**Issue by volak** [dotnet/sourcelink#186]
If you make a project that depends on a library using sourcelink - and enable this option in the csproj file

`<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`

The sourcelink'd nuget packages won't have sourcelink enabled, symbols won't be load, and breakpoints will not be set.

Seems to me that this is because the option is only copying the DLLs from the nuget package, not the PDB files.

Opening mainly for FYI - I don't know if this can be fixed but it took a while to figure out.

**Comment by tmat** [comment]
Looks like https://github.com/dotnet/sdk/issues/1458. Correct?

**Comment by volak** [comment]
@tmat Looks similar - but this project is targeting dotnet core 2.1.  And using the new project format

**Comment by tmat** [comment]
@nguerrera @dsplaisted

**Comment by dsplaisted** [comment]
I expect this will be fixed in 3.0, as we are planning to unify publish and build: https://github.com/dotnet/cli/issues/10041

`CopyLocalLockFileAssemblies` was kind of a way to unify build and publish, but didn't entirely work.

@peterhuene

**Comment by nguerrera** [comment]
This is effectively the same issue as dotnet/sdk#1458 

The reason that is more often associated with .NET Framework is that the default there is CopyLocal=true. But it would impact copy-local for any TFM.

**Comment by tmat** [comment]
Closing as external.
