### ISSUE TITLE
Sourcelink in Docker?

### ISSUE THREAD

**Issue by ChristianSauer** [dotnet/sourcelink#187]
We are building nearly everything in Docker containers, so we avoid copying everything and his dog into the container.
Therefore, building a project with Sourcelink fails because Sourcelink cannot locate the .git directory.

So two questions:
1. Can I avoid copying the .git directory into the container?
2. If not, where do I have to locate the directory?

**Comment by tmat** [comment]
This is a tricky one. We don't have an out-of-box support for this scenario currently. It's definitely an interesting scenario to support. 

A couple of options:
- You can copy part of `.git` - the minimum required for git to recognize the repository, and have information about head commit, remotes and submodules.
- If you use `EmbedUntrackedSources` you'll need to copy `.gitignore` files as well.
- If you don't use `EmbedUntrackedSources` then it should be possible to generate a .props file with `SourceRoot` item group initialized from git repo information outside of the container and then import that .props file to the build in the container. This is a bit tricky though as it requires knowledge of SourceLink targets. You'd want to override [InitializeSourceControlInformationFromSourceControlManager target])(https://github.com/dotnet/sourcelink/blob/master/src/Microsoft.Build.Tasks.Git.Operations/build/Microsoft.Build.Tasks.Git.targets#L13) to avoid reading from the repository and instead initialize the properties and items from pre-generated values.

**Comment by ChristianSauer** [comment]
Hi @tmat 
I think it would be a good idea to consider this feature - building procjts this way is inceasingly common since it neatly encapsulates all build steps into a single reproducible step. 

I will try to copy the git folder and the gitignore file but is not ideal at all.

As a suggestions: It would be great if EmbedUntrackedSources  is explained in more detail. I understand what it does, but I found no valid guidance as to the consequences.

**Comment by ChristianSauer** [comment]
Ok, now I am confused:
I am adding the .git and. gitignore Folder in my Dockerfile. Building it on my local machine does work fine. But building it on my build machine results in this error:
/root/.nuget/packages/microsoft.sourcelink.common/1.0.0-beta-63127-02/build/Microsoft.SourceLink.Common.targets(40,5): error : SourceRoot.SourceLinkUrl is empty: '/src/' 

I am not at alle sure that the build machine can access our internal TFS. Is this the root cause for this problem?
Otherweise, build arguments etc. are identical.

**Comment by tmat** [comment]
Re `EmbedUntrackedSources` (https://github.com/dotnet/sourcelink/tree/master/docs#embeduntrackedsources)

I'm not sure what you're looking for. What consequences do you mean?

**Comment by tmat** [comment]
> I am not at alle sure that the build machine can access our internal TFS. Is this the root cause for this problem?

No, access to the server isn't necessary. SourceLink does not access the network, it gets all information it needs from the local repository metadata.

**Comment by tmat** [comment]
Can you pass `/bl:log.binlog` to msbuild and share the `log.binlog` file. This log can be used to see what went wrong within the build.

**Comment by ChristianSauer** [comment]
@tmat I will try to, atm it is quite busy here

**Comment by eerhardt** [comment]
I've run into a similar issue with the [Apache Arrow NuGet package](https://www.nuget.org/packages/Apache.Arrow/).

In the non-.NET world, it seems to be quite popular to do release management from an individual's own computer, and not from an "official build machine".

In Apache Arrow, they write release scripts that the Release Manager runs during a release. You can see the [C# release script here](https://github.com/apache/arrow/blob/master/dev/release/post-06-csharp.sh). Here is the important part:

```sh
curl \
  --remote-name \
  --fail \
  https://www-us.apache.org/dist/arrow/arrow-${version}/${tar_gz}
rm -rf ${archive_name}
tar xf ${tar_gz}
pushd ${archive_name}/csharp
dotnet pack -c Release
for package in artifacts/Apache.Arrow/Release/*.{nupkg,snupkg}; do
  dotnet nuget push \
    ${package} \
    -k ${NUGET_API_KEY} \
    -s https://api.nuget.org/v3/index.json
```

Here, in this world, there is no `git` repo - they download the official released tarball and build it from source.

Maybe the tooling needs the ability to allow users to:

1. Set the commit SHA manually.
2. Set the git remote URL manually, and say what path maps to that URL.

**Comment by eerhardt** [comment]
@tmat - A question has come up on the [Arrow JIRA issue](https://issues.apache.org/jira/browse/ARROW-5092) associated with this issue:

>Can we specify the followings explicitly instead of auto detection?
> The commit hash (I hope that we can use tag name such as apache-arrow-0.13.0 for it)

Can you use tag names instead of commit hashes? I don't know if anyone has done this.

**Comment by tmat** [comment]
Yes, I'm thinking of allowing both of the following approaches:

1) Use minimal set of git data files that contain the necessary information
    One would just need the `.git/config`, `.git/HEAD`, `.git/refs/heads/{branch}`, `.gitmodules` and `.gitignore` (this one is only needed when `EmbedUntrackedSources` feature is used). No other files (e.g. objects, logs, etc.) would need to be present in the `.git` dir.

   This should work today. Currently some files might be required by libgit that are not strictly necessary.

2) Specify the required data in `.props` file.

> Can you use tag names instead of commit hashes?

No, we need a commit hash.

**Comment by tmat** [comment]
@eerhardt If we enable setting the data SourceLink needs manually, how's it gonna work end-to-end with the above release script?

Are you gonna run some commands to fetch the information from somewhere?

**Comment by eerhardt** [comment]
@kou had a solution in the JIRA issue above:

> We should get the commit hash from tag by curl https://api.github.com/repos/apache/arrow/tags | jq '.[] | select(.name=="apache-arrow-0.13.0") | .commit.sha'.

where the tag name can be built using `apache-arrow-${version}` in the script. That will get us the commit hash.  The git URL should always be https://github.com/apache/arrow.

I think the only thing that doesn't have a solid story yet is how to map the source root path. Maybe setting an MSBuild property to the directory that should be considered the "git repo root"?

**Comment by tmat** [comment]
Would it be reasonable for the release script to create directory `.git` in the root and in it 
1) file `HEAD` that contains the commit SHA
2) file `config` that contains `[remote "origin"] url = {URL}`.
3) empty directories `objects` and `refs`

**Comment by eerhardt** [comment]
Hopefully @kou will chime in with any opinions.

My personal thoughts are that I think it is reasonable, but it feels like these things should be able to be handled/overwritten using MSBuild properties. If there are extenuating circumstances that don't make using MSBuild properties possible, I would be willing to do whatever is necessary to make it work. It will be better than the situation we have today where it doesn't work.

**Comment by tmat** [comment]
@eerhardt Maybe we can pass these via MSBuild properties, but then if the repo had submodules we would also need to invent a way how to represent them as MSBuild items as well. So the question is, do we want to have a way how to represent all relevant git repo metadata as MSBuild properties? Maybe we do, but the same data can be easily represented in their original form, so why having multiple ways to represent them?

**Comment by eerhardt** [comment]
I forgot about submodules. Maybe that is a good enough reason to not allow MSBuild properties for this information...

**Comment by tmat** [comment]
Yeah, submodules always throw a wrench in simplicity...

**Comment by ChristianSauer** [comment]
How common are submodules? I do think they could be ignored in a lot of cases. I rather have an easy solution for 90%, than an non workable solution in 100% of the time like now. Getting the URLs, id's, branches etc. Is easy in most Ci tools today, so use that information. Ideally, read it from env variables, since we are discussing docker. 




Outlook für Android herunterladen







On Tue, Apr 9, 2019 at 8:58 PM +0200, "Tomáš Matoušek" <notifications@github.com> wrote:












Yeah, submodules always throw a wrench in simplicity...

**Comment by tmat** [comment]
We do have a design for reading the information from environment variables (not 100% implemented yet):
https://github.com/dotnet/designs/blob/master/accepted/build/standard-ci-env-variables.md

The problem is each CI system defines different variables, so we would first need to make sure the CI is setting standardized variable names.

**Comment by tmat** [comment]
It also has to support submodules. While I agree that repos without submodules should be simple to set up, we can't have completely different approach for repos with and without submodules. We don't want them to fall off a cliff once they add a submodule.

**Comment by tmat** [comment]
BTW, when creating a containing isn't it easy to copy in a few .git files?

**Comment by kou** [comment]
> Would it be reasonable for the release script to create directory `.git` in the root and in it
> 
>     1. file `HEAD` that contains the commit SHA
> 
>     2. file `config` that contains `[remote "origin"] url = {URL}`.
> 
>     3. empty directories `objects` and `refs`?

Yes.
We can create the dummy Git repository.

**Comment by tmat** [comment]
One change was needed in order to make the above work as I described:
https://github.com/dotnet/sourcelink/pull/266

The PR also adds a test and documentation of the minimal git metadata required for Source Link. 
In future we might be able to remove the requirement for `objects` and `refs` directories to be present. I believe it's a easy to use approach for the scenarios brought up in this issue. For repos without submodules it only requires to create 2 single line text files. Adding submodules is also trivial - just a couple more files must be present per submodule.
