### ISSUE TITLE
What are the extensibility points of these targets?

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/sourcelink#188]
I'd like to extend these targets and I'd like to know what can I rely on and what the extensibility points are.

**Comment by tmat** [comment]
Any target or property whose name does not start with `_` is considered public API. 
Note however that SourceLink packages are still pre-release and public API may change.

**Comment by paulomorgado** [comment]
Thanks, @tmat. I know these are still pre-release versions.

I'm trying to use the information collected by these targets to add them to the NuGet package information. For that, I need:

* `RepositoryUrl`
* `RepositoryType`
* `RepositoryBranch`
* `RepositoryCommit`

I guess that, apart from `RepositoryBranch`, all information is collected through these targets. But in which variables?

Shouldn't `RepositoryBranch` be available?

[This NuGet blog post](https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html "Introducing Source Code Link for NuGet packages") mentions these packages and links to the [Pack target documentation](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target/) which contains `RepositoryBranch`.

I'm also adding this information to assembly metadata and don't want to be collecting it again and risk being out of sync.

**Comment by tmat** [comment]
Except for `RepositoryBranch` this is all done by default in .NET SDK and Pack targets:

https://github.com/dotnet/sdk/blob/ab2176b3447e3e7820b5a340408110b6d498f907/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L52

https://github.com/NuGet/NuGet.Client/blob/839df088f48e1e9d87ab86e5b26b7431547fa820/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L258. 

Do you need it for scenarios where you can't use .NET SDK? If so you can see how the above targets do it.

**Comment by paulomorgado** [comment]
The .NET SDK would also fill the `RepositoryBranch` if it was available.

https://github.com/NuGet/NuGet.Client/blob/839df088f48e1e9d87ab86e5b26b7431547fa820/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L228

I think it's worth the effort. Don't you think? Can I help?

I'm also adding all this information to the assembly as `AssemblyMetadataAttribute` annotations.

And I'm fiddling with the repository URL and changing it to the commit URL. That way, on the NuGet site, the link goes directly to that commit.

**Comment by tmat** [comment]
I'm gonna close this issue. If you think we should add support for `RepositoryBranch` let's open a separate issue for that.

**Comment by mikeblakeuk** [comment]
Why doesn't **RepositoryBranch** get set? 
Why do i need to add `/p:RepositoryBranch=12345-branch`
