### ISSUE TITLE
What's the point of Sourcelink?

### ISSUE THREAD

**Issue by ChristianSauer** [dotnet/sourcelink#189]
I hope this does not sound passive-aggressive but I do wonder why SourceLink is the way to distribute debuggable Nuget packages?
It seems to add a lot of moving parts just to do something with could be solved by including the .cs files in the nuget?
I am working a lot with Python code, where there often a package really is only a collection of source files and that ecosystem is not the debugging hell the Nuget world currently is.
Sure, SourceLink will probably ease debugging, but setup and getting it to work seems to be non trivial.

**Comment by tmat** [comment]
You can embed all your sources to the PDB and include that in the NuGet package like so:

```xml
<PropertyGroup>
  <EmbedAllSources>true</EmbedAllSources>
  <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```

This does not require SourceLink. 

Although the sources are compressed in the PDB they still might grow the package significantly. If that isn't an issue for your project then I definitely recommend doing so. 

For some customers increasing size of their NuGet package is not acceptable, so they prefer to link the sources to the repository using SourceLink. 

Also, SourceLink allows you to easily stamp your NuGet package and assembly with the commit SHA.  

The only thing you need to use SourceLink is to add a PackageReference and set a couple of properties like so: https://github.com/dotnet/sourcelink#using-sourcelink. Do you consider that "non trivial"?

**Comment by chilakamarthi** [comment]
@tmat Well its clear how to embed all sources if I am using .csproj. But what if I am using .nuspec for packing? How we embed all source using .nuspec?
