### ISSUE TITLE
Adding the appropriate SourceLink Nuget causes build to fail

### ISSUE THREAD

**Issue by lhersman** [dotnet/sourcelink#193]
I've been following the documentation on this repo to enable SourceLink in an effort to be able to debug private nuget packages hosted on our Azure DevOps account, but have run into an issue.

The mere act of installing the appropriate nuget package (Microsoft.SourceLink.Vsts.Git) causes the build to fail with the following error:

`1>vbc : error BC2001: file 'C:\Users\USER\AppData\Local\Temp\.NETStandard' could not be found`
`1>vbc : error BC2001: file 'C:\Projects\TheApp\TheLibrary\TheLibrary\Version=v2.0.AssemblyAttributes.vb' could not be found`

This makes me think I'm missing some SDK or have the wrong version of VS2017, but it all seems ok: I'm on VS2017 15.8.7 (Pro), have the .NET Core SDK 2.1.403 installed and the project is a .NET Standard 2.0 library.

Removing the nuget package makes the build pass again, but obviously removes the SourceLink support as well.

**Comment by tmat** [comment]
Could you try to run `msbuild MyProj.vbproj /bl:log.binlog` and share the log?

**Comment by lhersman** [comment]
> Could you try to run `msbuild MyProj.vbproj /bl:log.binlog` and share the log?

Pretty big log, if you want the whole thing let me know.  Here's the last bit with the error, looks the same:

`Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Profession
  al\MSBuild\15.0\bin\Roslyn
vbc : error BC2001: file 'C:\Users\USER\AppData\Local\Temp\.NETStandard' could not be found [C:\Projects\TheApp\TheProject\TheProject\TheProject.vbproj]
vbc : error BC2001: file 'C:\Projects\TheApp\TheProject\TheProject\Version=v2.0.AssemblyAttributes.vb
' could not be found [C:\Projects\TheApp\TheProject\TheProject\TheProject.vbproj]
Done Building Project "C:\Projects\TheApp\TheProject\TheProject\TheProject.vbproj" (default targets) -- FAILED.`

**Comment by tmat** [comment]
Yes, the whole file is needed for investigation. Thanks.

**Comment by tmat** [comment]
Sorry, I meant the file `log.binlog`. It contains information about all properties and tasks executed during the build. If you don't want to share it publicly feel free to send me link to OneDrive or Google Drive to my email: tomat@microsoft.com

**Comment by lhersman** [comment]
> Sorry, I meant the file `log.binlog`. It contains information about all properties and tasks executed during the build. If you don't want to share it publicly feel free to send me link to OneDrive or Google Drive to my email: [tomat@microsoft.com](mailto:tomat@microsoft.com)

Ah, I see.  Emailed the file to you with the subject "Sourcelink Issue #193 binlog".  Thanks!

**Comment by tmat** [comment]
This is a bug in VB compiler: https://github.com/dotnet/roslyn/issues/30586

The workaround is to remove

```xml
<EmbedUntrackedSources>true</EmbedUntrackedSources>
```

That is, not use the SourceLink feature that embeds untracked files automatically.

**Comment by tmat** [comment]
Glad to hear that. Thanks for reporting the issue.

**Comment by tmat** [comment]
The compiler issue has been fixed: https://github.com/dotnet/roslyn/pull/32015
