### ISSUE TITLE
Unable to Step Into Third Party Code

### ISSUE THREAD

**Issue by JeremyTCD** [dotnet/sourcelink#198]
## Summary
Pdb generation works fine, but third party code can't be stepped into.

## System
Windows 10, VS 15.8.8.

## Description
I've got a simple class library with the following csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta-63127-02" PrivateAssets="All" />
    </ItemGroup>

</Project>
```
This works fine. A valid pdb is included when i generate a package. I've tested the pdb with the SourceLink command line tool:

```ps
sourcelink test .\Test.AzurePipelines.pdb
sourcelink test passed: .\Test.AzurePipelines.pdb

sourcelink print-json .\Test.AzurePipelines.pdb
{"documents":{"C:\\Projects\\Test.AzurePipelines\\*":"https://raw.githubusercontent.com/JeremyTCD/Test.AzurePipelines/74d8b24ebde6ec0d9e38ad1355bafae1356da993/*"}}

sourcelink print-urls .\Test.AzurePipelines.pdb
178770449866fd131ae2150699c6b8a494e566ce sha1 csharp C:\Projects\Test.AzurePipelines\src\Test.AzurePipelines\Class1.cs
https://raw.githubusercontent.com/JeremyTCD/Test.AzurePipelines/74d8b24ebde6ec0d9e38ad1355bafae1356da993/src/Test.AzurePipelines/Class1.cs
d19483e16d67ae4da6e044d3fdeb35dd87480282 sha1 csharp C:\Users\Jeremy\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.cs
embedded
```
The urls have been checked manually and they work fine.  

I've published the package to a local nuget feed:
```
dotnet pack -c Release
nuget push .\Test.AzurePipelines.2.0.0.nupkg -src "D://NugetLocalFeed"
```

And I've referenced it from a test console application with the following csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Test.AzurePipelines" Version="2.0.0" />
  </ItemGroup>

</Project>
```
I've disabled `Just My Code` and enabled `Source Link Support`:
![options](https://user-images.githubusercontent.com/11733898/47599944-8a8f7700-d9eb-11e8-9bd3-621cc89a92ae.jpg)

The pdb loads fine:

![modules](https://user-images.githubusercontent.com/11733898/47599892-81ea7100-d9ea-11e8-922d-f8d54a91df1b.jpg)

The SourceLink command line tool indicates that the pdb in the image is valid.  

Unfortunately, I still can't step into my class library's functions. F11 just steps over functions. Am I doing something wrong? I've gotten SourceLink to work before once, but it was using an older version of VS. Unfortunately I can't rollback my VS version. Anyone else having trouble with VS 15.8.8 and SourceLink?

Edit: Doesn't work on 15.9.0 Preview 4.0 either.

**Comment by JeremyTCD** [comment]
After some clicking around, I think VS might be the problem. F11 does not work, but "Step Into Specific" from the context menu works:

![stepinto](https://user-images.githubusercontent.com/11733898/47600972-114c5000-d9fc-11e8-8f3d-bf347562f05f.gif)

Whats happening in the gif:
- Start debugging.
- F11, skips right over line with `ToLower` invocation.
- Ctrl+Shift+F10 to set next line back to the line with `ToLower` invocation.
- Use "Step Into Specific" this time.
- Popup for source download appears, source downloads successfully.
- Steps into `ToLower`.

Not sure if my VS is just scuffed. If this is the case for everyone, might be a good idea to document that F11 doesn't step into third party sources.

**Comment by chuckries** [comment]
Do you have Just My Code enabled in Tools -> Options -> Debugging -> General?

From your Modules Window Screenshot, it appears you are loading an optimized version of Test.AzurePipelines.dll (optimized meaning built with Release configuration). The debugger treats all optimized dll's as Non-User Code, meaning it will not stop in it. Step Into Specific bypasses this. 

Please disable Just My Code and try F11 again.

**Comment by chuckries** [comment]
I am investigating further but I believe this is a .NET Core issue. If I build the .NET Core client app (FeedTest in your exmaple) for `net461` then I am able to step in correctly.

**Comment by chuckries** [comment]
For me, step in also worked when building the FeedTest against netcoreapp2.0 or netcoreapp3.0 (preview). This appears to be a regression in .NET Core 2.1.

**Comment by JeremyTCD** [comment]
@chuckries Thanks for looking into this issue. Unfortunately, I couldn't replicate your results:

TargetFramework | Step Into | Step Into Specific
--------|---------|-------
net461 | Doesn't work | Doesn't work
net462 | Doesn't work | Doesn't work
netcoreapp2.0 | Doesn't work | Works
netcoreapp2.1 | Doesn't work | Works

> In case this wasn't clear, the issue has nothing to do with Source Link

Yes I agree. Even with all sources embedded in my pdb, I couldn't step into functions using F11. That led me to think it was a VS problem so I opened [this](https://developercommunity.visualstudio.com/content/problem/368985/step-into-f11-does-not-work-for-third-party-code-i.html?childToView=370106#comment-370106) issue. I think it is better to track it there, or if it has something to do with CoreCLR we might have to open an issue in their repo. Closing this for now

**Comment by chuckries** [comment]
Thanks for the follow up. It's worth checking in the modules window to see what version of the coreclr runtime you are **actually** running on, as this is the version of the coreclr debugger you will be running with. Starting with 2.0, the shared framework/runtime is supposed to be forward compatible. That is, if you have only .NET Core 2.1 installed and you run a netcoreapp2.0 on the shared framework, it will happily run on the 2.1 runtime. 

I believe in my testing I looked at coreclr versions 2.0.9 and 2.1.5 (or something). 

This shouldn't matter for net461, so I'm surprised you are not seeing those work.
