### ISSUE TITLE
Using Source Link for "Go To Definition" and other non-step into cases

### ISSUE THREAD

**Issue by MisterJimson** [dotnet/sourcelink#200]
Source Link is great for when you have a chance to Step Into a method or class, but that is not always the case.

Often you will know where in the dependancy you want to set a breakpoint, but don't have an access point to Step Into it from.

Being able to navigate to a file/class/method before starting a debug session can be very helpful. You could set breakpoints in the third party code ahead of time.

This also greatly improves the value of the navigation features in Visual Studio (and other IDEs).

**Comment by PhilipDaniels** [comment]
I think this is more a problem with the Visual Studio IDE than Source Link per se. I have made a DLL with embedded PDB and embedded sources, and Go To Definition does not work there either, but Step In works perfectly. It looks like the part of the IDE that deals with navigating source code needs to be taught about other places it can get the source from.

**Comment by 24mu13** [comment]
It's very tricky, but it's already possible on VS2017.

**Comment by tmat** [comment]
This feature is tracked by https://github.com/dotnet/roslyn/issues/24349
