### ISSUE TITLE
VSTS build Error CS0016: Could not write to output file 

### ISSUE THREAD

**Issue by robbileifss** [dotnet/sourcelink#201]
2018-11-01T16:04:01.3567998Z ##[error]CSC(0,0): Error CS0016: Could not write to output file *.sourcelink.json' -- 'Could not find file *.Core.sourcelink.json'.'

I'm getting this error in VSTS build pipeline.  Known issue? I saw the same problem with Travis in anther issue.  Has anybody found out why?

I've tried using dotnet build only on the project where I have sourcelink. that builds fine in VSTS.

But when the main CI builds with visualstudio build, and builds the .sln which has about 60 projects in it. Then it fails with this error

**Comment by sturlath** [comment]
I´m also getting this error. Does´t anybody know what it means?

**Comment by mschellenger96** [comment]
Try updating your Visual Studio. For me, the solution built locally but would fail on our build machines. Turns out VS on our machines were a few versions behind. Updating to the latest did the trick.

**Comment by tmat** [comment]
@robbileifss Did updating VS resolved the issue? If not can you build with `/bl:log.binlog` and share the log.binlog file? Note that the log file contains details about your build. If you don't want to share it publicly you can send a link to some file share to my email: tomat@microsoft.com.

**Comment by Neil-p-Hughes** [comment]
How do you update the Visual studio version on the build machine? our build pipeline is using msbuild latest

**Comment by tmat** [comment]
Is this still an issue?

**Comment by jonantoine** [comment]
For myself I just wanted this turned off so for those like me, who would like to disable this all together you can find the Microsoft.Common.CurrentVersion.targets file in .dotnet\sdk\\{version}\ folder and set the following to false
```
<PropertyGroup>
   <SourceControlInformationFeatureSupported>true</SourceControlInformationFeatureSupported>
</PropertyGroup>
```

**Comment by robbileifss** [comment]
Hi,
Sorry for not giving more info on this one.  I had this problem at a workplace which I no longer work. I did some work around can't remember what it was.  So I'm going to close this one if anyone objects then we can open it up again.
