### ISSUE TITLE
SouceLink for SVN server

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/sourcelink#203]
Hi,
Is it possible to provide source link from SVN server installed locally.

Thanks and regards
Venkatesh

**Comment by tmat** [comment]
It should be possible to implement if anyone is interested in doing so.

**Comment by tmat** [comment]
Duplicate of https://github.com/dotnet/sourcelink/issues/184

**Comment by WenningQiu** [comment]
@VenkateshSrini We had the same issue, you might want to check out https://www.nuget.org/packages/SourceLink.VisualSVN/1.0.0
