### ISSUE TITLE
The url is garbled

### ISSUE THREAD

**Issue by Varorbc** [dotnet/sourcelink#205]
![image](https://user-images.githubusercontent.com/5714438/49192287-6261b200-f3b5-11e8-8daa-2c1568c57a20.png)

![image](https://user-images.githubusercontent.com/5714438/49192346-93da7d80-f3b5-11e8-9a23-10ad6ade581f.png)

![image](https://user-images.githubusercontent.com/5714438/49192389-c71d0c80-f3b5-11e8-8b5c-6af9f2d8472f.png)

**Comment by tmat** [comment]
What is the name of the repository supposed to be?

Could you build from command line `msbuild /bl:log.binlog` and share the log.binlog file? If you don't want to share it publicly you can send me an email to tomat@microsoft.com.

**Comment by Varorbc** [comment]
collection name is `实验`,  `实验` url encode is `%e5%ae%9e%e9%aa%8c`

repository name is `Test`

**Comment by Varorbc** [comment]
The message has been sent, please check

**Comment by tmat** [comment]
Fixed in version `1.0.0-beta2-18623-01`.
