### ISSUE TITLE
Mention requirements for symbol packages (.snupkg)

### ISSUE THREAD

**Issue by cremor** [dotnet/sourcelink#229]
The readme was [recently changed](https://github.com/dotnet/sourcelink/commit/dc3c8dc7f5af1b30e1fe74212dc904f01ffbb160#diff-04c6e90faac2675aa89e2176d2eec7d8) to use the new NuGet symbol packages (.snupkg) instead of embedding the PDB in the main NuGet package. While this new symbol server is nice, it has a few disadvantages:

1. It only supports portable PDBs (SourceLink itself supports all PDB formats)
2. It requires VS 2017 15.9 to build or to consume the symbol packages (SourceLink only requires 15.3)
3. It requires the user to manually add the NuGet symbol server in the VS settings (embedded symbols don't require any settings)

In my opinion these requirements should be listed in the readme, otherwise users (both library authors and consumers) might wonder why SourceLink isn't working for them.
Maybe even mention both ways - embedded PDB files and the NuGet symbol server - to give the library author the choice.

Note that the [official open source library-guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages) also still recommends embedded PDB files over the new NuGet symbol server.

**Comment by tmat** [comment]
> Note that the [official open source library-guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages) also still recommends embedded PDB files over the new NuGet symbol server.

The doc has been updated.
