### ISSUE TITLE
Source code is not in sync with nuget library

### ISSUE THREAD

**Issue by ts46235** [dotnet/sourcelink#240]
I have a 3rd party library, https://github.com/khellang/Middleware/tree/10d508e1071a86dd59360b0f15760aca0e7d43ba/src/ProblemDetails, that I can step into but it the source file is different so you don't hit all your breakpoints and the current execution step is not the actual one. 

Even after upgrading to the latest version it is still using the same old file. What can we do to force sync? I have deleted all folders in SourceServer to try to get it to pull it correctly but it wouldnt work. Correction, I just tried it and it pulled in at least one of the file's latest version but can't set breakpoint on some lines and is out of sync while stepping thru the code.

what is the prblem?

thanks!

**Comment by tmat** [comment]
Tested version 2.3.0 of Hellang.Middleware.ProblemDetails package and stepping works as expected. The library is optimized, so you won't be able place a breakpoint everywhere where you would if it was debug build.

> the source file is different

How did you determine that they are different?

**Comment by ts46235** [comment]
I referenced the content thru github to see the version of the code; there was part that was updated that I knew was different. 

As I said, the last time I wiped out SourceServer folders it did pull in the latest version of the file so I think I"m good. Thanks
