### ISSUE TITLE
How to ship a nuget package with embedded pdbs

### ISSUE THREAD

**Issue by enzian** [dotnet/sourcelink#244]
I was wondering, what kinds of hoops I'd have to jump through to make this work?

I have a .csproj file like this:
```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DebugType>Embedded</DebugType>
    <EmbedAllSources>True</EmbedAllSources>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Some.Sample.Package</PackageId>
    ...
  </PropertyGroup>
```
but when using the nuget package built from this csproj using `dotnet pack` and I try stepping into an API, VS asks me where to get the source file... Isn't that supposed to be embedded?

**Comment by tmat** [comment]
Yes, the sources should be embedded. What VS version do you use? Can you share the package?

**Comment by jjpepper** [comment]
Isn't it also necessary to include:

```<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>```

In the top `PropertyGroup`?

**Comment by enzian** [comment]
@tmat : I'm running VS 15.9.7 i do have a package on NuGet id is not sourcelinked yet. I was trying it out with a local package feed but that did not work so far! I'll drop a line here, when I have uploaded the package!

**Comment by enzian** [comment]
ok I published the [nuget package](https://www.nuget.org/packages/Kafka.Extensions.Hosting/1.1.1-alpha01) from [this repository](https://github.com/leuchterag/Microsoft.Extensions.Hosting.Kafka). [This](https://github.com/leuchterag/Microsoft.Extensions.Hosting.Kafka/releases/tag/v1.1.1-alpha01) is the release and there is an artifact for the nuget package as well!

**Comment by tmat** [comment]
> Isn't it also necessary to include:
> `<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>`
> In the top `PropertyGroup`?

It is not. The project sets `DebugType` to `embedded`, which means the PDB is going to be embedded to the DLL. Furthermore, the project also sets `EmbedAllSources` meaning the sources are going to be embedded into the PDB. This approach is the best when the resulting size of the DLL is not an issue, as the debugger doesn't need to find the PDB on a symbol server and the sources on the source server. Everything is embedded in a single file (the DLL).

**Comment by tmat** [comment]
@enzian 
>  I'm running VS 15.9.7 i do have a package on NuGet id is not sourcelinked yet. I was trying it out with a local package feed but that did not work so far! I'll drop a line here, when I have uploaded the package!

SourceLink is not needed as you're embedding sources into the PDB. SourceLink is only useful when linking the PDB to sources on a source server.

**Comment by tmat** [comment]
@enzian I tried to step into a method in your library and everything seems to work fine in VS 15.9.5. 

This is what I tried:

1. Create a console app targeting .NET Framework
```xml
  <ItemGroup>
    <Reference Include="c:\temp\Microsoft.Extensions.Hosting.Kafka.dll"/>
  </ItemGroup>
```

2. Place breakpoint to the Main of the app as indicated:
```c#
using Microsoft.Extensions.Hosting.Kafka;

class Program
{
    static void Main()
    {
        var s = new KafkaListenerSettings();
        s.DefaultTopicConfig = null; // breakpoint
    }
}
```

3. F5. When the breakpoint is hit, select from editor context menu:
![image](https://user-images.githubusercontent.com/41759/52989725-fbef9d00-33c1-11e9-9d87-db460b8f5688.png)

4. The debugger navigates to the source:
![image](https://user-images.githubusercontent.com/41759/52989760-17f33e80-33c2-11e9-9e30-7f5195dedc1c.png)

Note that "Just My Code" in the Debugger options must be enabled in order for the above to work.

**Comment by enzian** [comment]
Oh, actually, when I used "Step into specific" to step into the library methods then it asked me to disable "Just my Code" and then it worked! Cool!

**Comment by MikeBeaton** [comment]
I found this thread very helpful, but I'm confused - I don't know if anybody has time to help.

From my experience with trying to set up SourceLink on my own packages, I have found that:

 - `<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>` simply does not work: the consuming Visual Studio never finds the PDB and never loads the symbols, even though yes, the PDB is in there next to the DLL in the NuGet file (and if I copy out that PDB using a zip manager and shove it into the compiled directory, it works)

One the other hand:

 - `<DebugType>Embedded</DebugType>` (as used by `enzian` in his helpful tests above) works fine, straight away!

What am I missing? Why do all the tutorials use something which apparently doesn't work?!

**Comment by tmat** [comment]
That's right. The SDK unfortunately doesn't copy the PDB as detailed in https://github.com/dotnet/sdk/issues/1458.

**Comment by tmat** [comment]
@MikeBeaton Any reason not to publish PDB via symbol packages (snupkg)?

**Comment by MikeBeaton** [comment]
@tmat I'm trying to set this up on a private NuGet feed, and as far as I can make out neither the file system based feed nor the Microsoft NuGet.Server IIS package have symbol servers or support .snupkg files?

**Comment by tmat** [comment]
@anangaur @rrelyea

**Comment by anangaur** [comment]
@tmat Can you open a NuGet issue and link it?
