### ISSUE TITLE
TFS on-premise - empty virtual directory

### ISSUE THREAD

**Issue by cjlotz** [dotnet/sourcelink#249]
I'm trying to get SourceLink to work with our TFS on premise solution.  In our setup we do not have the TFS installed to a `tfs` virtual directory - it is installed directly on the root site.  The `SourceLinkTfsGitHost` task doesn't currently allow us to omit or specify an empty string for the `VirtualDirectory` task parameter.  Is there any way to work around this?

```xml
<Project>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.Tfs.Git" Version="1.0.0-beta2-18618-05" PrivateAssets="All"/>
    <SourceLinkTfsGitHost Include="prods-tfs:8080" VirtualDirectory="" />
  </ItemGroup>
</Project>
```

**Comment by tmat** [comment]
Have you tried `VirtualDirectory="/"`?

**Comment by cjlotz** [comment]
Thx, that seems to work
