### ISSUE TITLE
Which package should I use for projects hosted under Azure DevOps Server?

### ISSUE THREAD

**Issue by Varorbc** [dotnet/sourcelink#252]
Which package should I use for projects hosted under Azure DevOps Server?

**Comment by tmat** [comment]
https://github.com/dotnet/sourcelink#team-foundation-server should work. Let us know if you run into issues.

**Comment by Varorbc** [comment]
seems unable to work.

**Comment by Varorbc** [comment]
@tmat unable to debug access

**Comment by Varorbc** [comment]
@tmat Can you help me solve it?

**Comment by juanperezADD** [comment]
Any news? After migrating to Azure DevOps Server, we can not debug the NuGet packages using Source Link.

**Comment by juanperezADD** [comment]
The debug access is fixed with the 16.1 Preview 2 of Visual Studio. 

More information https://github.com/dotnet/sourcelink/issues/207 and https://github.com/dotnet/sourcelink/issues/176.

**Comment by Varorbc** [comment]
@juanperezADD I still don't seem to work.

**Comment by Varorbc** [comment]
@juanperezADD
