### ISSUE TITLE
Source control information is not available - the generated source link is empty.

### ISSUE THREAD

**Issue by wjvii** [dotnet/sourcelink#254]
When I build a NuGet package on my local system with right click on the project, pack, the resulting NuGet package has the Repository information as expected. However when I checkin to the Azure DevOps Git Repo and the automated build system builds the package I keep getting:

C:\Users\VssAdministrator\.nuget\packages\microsoft.sourcelink.common\1.0.0-beta2-18618-05\build\Microsoft.SourceLink.Common.targets(53,5): warning : Source control information is not available - the generated source link is empty.

I feel sure there must be an extra step I need to do for the CI build so it will work as expected but I have not been able to find out what it is.

Thank you in advance for any input.

**Comment by wjvii** [comment]
Well out of curiosity I rolled back one of the projects to 1.0.0-beta-63127-02 and it appears to work as expected. After the CI build the NuGet package lists the repository information and the pdb has the correct links to the Azure DevOps Git Repo. I also checked the build and it no longer shows the above error.

Still wondering if there is something else I needed to do with 1.0.0-beta2-18618-05 and would be curious if anyone else has this same experience.

**Comment by psibernetic** [comment]
I'm seeing this as well with the GitHub package.

**Comment by tmat** [comment]
Could you please try the latest varsion? 1.0.0-beta2-19351-01

**Comment by wjvii** [comment]
My initial testing indicates it has resolved the issue. Thank you very much. 

I will continue to do more testing as I update more projects and post details here anything is not working as expected.

Thank you again.

**Comment by tmat** [comment]
Thanks for reporting the issue.
