### ISSUE TITLE
Supports breaking into a source link package on exception in Visual Studio?

### ISSUE THREAD

**Issue by joshmouch** [dotnet/sourcelink#261]
I currently have an Azure app service which is using a nuget package called IdentityServer4, which has SourceLink set up.

I'm attaching to the Azure App Service remotely via Visual Studio 2019 (using the Cloud Explorer window) in order to try and debug an exception in IdentityServer4.  However, when the exception occurs it won't "break" into the IdentityServer4 source code.  It seems like the source code stepping only works if you start in your own code first and then "step into" a source-link enabled package.

Is what I'm trying to do a supported scenario?  Can you have Visual Studio break on an exception in a nuget package?

A second question is: is there any support for adding breakpoints inside a source-link enabled package?

**Comment by tmat** [comment]
Do you have "Just my code" setting disabled in Debug > Options > Debugging > General?

> is there any support for adding breakpoints inside a source-link enabled package

Yes, you can create a "Function breakpoint" - this is a breakpoint on a specific function name.
https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2019#BKMK_Set_a_breakpoint_in_a_source_file
