### ISSUE TITLE
Publish to dotnet-core blob feed

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sourcelink#262]
I couldn't find the build definition that handles publishing the packages therefore I open this question. Can switch/additionally publish to the dotnet-core azure blob feed (https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json)

cc @tmat

**Comment by tmat** [comment]
@JohnTortugo What needs to be done for the package to be published? 
The build is building it: https://dev.azure.com/dnceng/internal/_build/results?buildId=378015&view=results

**Comment by JohnTortugo** [comment]
From what I looked at the build-definition you just need to configure a default channel in Maestro for the repo+branch that you're building.

**Comment by tmat** [comment]
Added default channel.
