### ISSUE TITLE
Disable source link for development builds

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [dotnet/sourcelink#264]
Hello,

When publishing my packages to NuGet, SourceLink is awesome.

But when packaging local builds for development and testing purposes, I want to be able to step into my own code as normal.

These packages are prepared through a PS script calling dotnet build and then dotnet pack --no-build.

Can I disable SourceLink through a parameter to dotnet pack, perhaps?

**Comment by tmat** [comment]
Having SourceLink enabled does not affect local development experience. The PDBs include full paths to the local sources and the debugger attempts to find the source files using these paths before it uses SourceLink information.

Do you have a specific issue with local debugging when SourceLink is enabled?

**Comment by bjorn-ali-goransson** [comment]
Actually, I had removed the "include PDBs in nuget package" since I thought it would have been replaced by some intrinsic feature. Another thread.

This can be closed. Thanks!!
