### ISSUE TITLE
global tool requires 2.1

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/sourcelink#267]
I have only 3.0 preview4 installed.
```
C:\dotnet>dotnet tool install --global sourcelink
Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.
You can invoke the tool using the following command: sourcelink
Tool 'sourcelink' (version '3.0.0') was successfully installed.
…
```
```
C:\dotnet>sourcelink
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0-preview4-27615-11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```
Is there a way to make it work on 3.0 (without requiring 2.1)
@tmat

**Comment by tmat** [comment]
@danmosemsft That would be a question for @ctaggart.
The global tool is from https://github.com/ctaggart/sourcelink repo, not from dotnet/sourcelink

**Comment by danmosemsft** [comment]
Ah OK I'll move the issue there.

**Comment by tmat** [comment]
Thanks, I assume that the tool needs to allow roll forward.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/sourcelink/issues/267

**Comment by ctaggart** [comment]
How do you make it so that the tool allows roll forward? I thought you had to compile it for 3.0 too and double the size of the nupkg

**Comment by ctaggart** [comment]
@danmosemsft, you linked to this issue. A workaround is to set and environment variable. If using `docker run`, just add `-e DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2`

https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md
