### ISSUE TITLE
SourceLink generated for Bitbucket Enterprise is wrong

### ISSUE THREAD

**Issue by kvskranthikumar** [dotnet/sourcelink#268]
SourceLink generated in the PDB for Bitbucket is wrong.

Genarated Link -
https://company.com/scm/catman/dataaccesstest/raw/e979641cb570abd2f17d04683ba6a4add014a2dc/SqlDbParameters.cs

Expected Link -
https://company.com/projects/catman/repos/dataaccesstest/raw/SqlDbParameters.cs?at=e979641cb570abd2f17d04683ba6a4add014a2dc

Template -
http://yourserver.com/projects/{projectKey}/repos/{repositoryKey}/raw/{pathToFile}.extension?at={commitHash}

Environment details -
Visual Studio 2019
Bitbucket Enterprise v5.12.1 (Company Private Repo)

csproject -
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RepositoryUrl>https://company.com/scm/catman/dataaccesstest.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.Bitbucket.Git" Version="1.0.0-beta2-18618-05">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>

```
I am currently stuck, please help, how can I get the expected link as mentioned above.

**Comment by ctaggart** [comment]
Do you think https://github.com/dotnet/sourcelink/pull/246 may fix this?

**Comment by kvskranthikumar** [comment]
I think so but can't confirm till I test the fix.

**Comment by kvskranthikumar** [comment]
The issue is fixed - https://github.com/dotnet/sourcelink/pull/246#issuecomment-494270431
