### ISSUE TITLE
Still not supported by Azure DevOps?

### ISSUE THREAD

**Issue by joshmouch** [dotnet/sourcelink#274]
I'm seeing conflicting information on whether or not Azure DevOps supports snupkg artifacts for SourceLink debugging.

Your ReadMe.md says that it doesn't.  But other tickets (such as this one: https://github.com/MicrosoftDocs/vsts-docs/issues/3039) show that it does.

**Comment by tmat** [comment]
I believe you can push them to the NuGet feed but the PDBs they contain don't currently get published to symbol server, so the debugger won't be able to find them.

**Comment by joshmouch** [comment]
Is there some verbose logging I can enable that will show Visual Studio attempting to do this?  It's like a black box.

**Comment by phatcher** [comment]
@joshmouch Unless you really need the nuget packages to be skinny, you can include the pdbs in your normal package and it does work with private feeds/project - mine leapt into life about a month ago.

**Comment by hkusulja** [comment]
So, what is progress / status, about being able to consume .snupkg from Azure Artifacts?

**Comment by infin8x** [comment]
It doesn't look like `.snupkg` support will make it into our next quarter of planning but it remains near the top of the stack for consideration.

**Comment by blushingpenguin** [comment]
I get the following out of the task:

```##[section]Starting: Publish symbols path
==============================================================================
Task         : Index sources and publish symbols
Description  : Index your source code and publish symbols to a file share or Azure Artifacts symbol server
Version      : 2.0.16
Author       : Microsoft Corporation
Help         : See [more information](https://go.microsoft.com/fwlink/?LinkID=613722) on how to use this task.
==============================================================================
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
##[section]Finishing: Publish symbols path
```

not sure why it's been closed?

**Comment by richardgavel** [comment]
I think this issue might be confusing 2 different things as a single thing and calling them both SourceLink, which isn't true. If I have a DLL I want to debug inside it, the symbol files (PDB) are necessary. That PDB may contain references to get the originating code from a source code repository. That second part is SourceLink, and in the case of Azure DevOps is covered here: https://github.com/dotnet/sourcelink#azure-devops-visual-studio-team-services.

Now there is a second question, and that's "where do I get the symbols (PDB) from?". One option is to package them up alongside the DLLs inside the NuGet package. A second option is to package them up inside a sibling "symbol package" and publish them to a "Symbol Server" that you would reference inside Visual Studio as a source of symbols for when it doesn't find them alongside the DLLs. This has nothing to do with SourceLink itself and is purely an Azure DevOps feature.

**Comment by tmat** [comment]
Closing the issue since it's external to Source Link.
