### ISSUE TITLE
dotnet pack removes the "repository" element from nuspec

### ISSUE THREAD

**Issue by joshmouch** [dotnet/sourcelink#275]
I'm seeing weird behavior when I run `dotnet pack` on a csproj set up with SourceLink.

When I run the following command (I've tried with and without `--include-symbols --include-source`):
`dotnet pack ......\MyProject.sln --output .......\artifacts\packages /p:Configuration=debug /p:PackageVersion=2019.5.2.12`

Then the following happens, which is exactly what I expect:
1. In the project's `obj\Debug` folder, a Nuspec file is generated.  When you open that file, it has a `<repository>` element, which looks correct.
2. A nupkg file is generated and placed into the `artifacts\packages` folder.

The odd behavior is that the `repository` element gets removed somehow when the nuspec gets packed into the nupkg file.  I confirmed this by renaming the file with a `zip` extension, then opening it and opening the `nuspec` file inside.  Everything else is identical except that the `<repository>` element gets removed.

This, of course, makes it so that if you try to use these NuGet packages, you won't get SourceLink support.

**Comment by joshmouch** [comment]
I found the issue.  You have to include the Microsoft.SourceLink.Vsts.Git in each and every project, not just a common dependency.

**Comment by tmat** [comment]
BTW, you can include the Source Link PackageReference in a [`Directory.Build.props`](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets) file in the root of your repository. This will include it in all projects.
