### ISSUE TITLE
Get Repository Url (tested:gitlab) Unexpected behavior

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/sourcelink#278]
Hi!
Domain1=gitlab.com
1. 
**Repository Url**= https://**domain1**/....
Origin repo url = git@domain2
Got error - SourceControlInformationIsNotAvailableGeneratedSourceLinkEmpty

**Ideally, I want to see that there is no mapping for a specific host.
or get https://domain1/ and see url in output**

2. 
**Repository Url**= <empty>
Origin repo url  = git@domain2
Got source link https://domain2/
**Ideally, I want to see that there is no mapping for a specific host.**

3. All ok
**Ideally, I want to see url in output**

p.s. 
_I use separate hosts aliases for different repositories to set keys in .ssh / config (+ vs + git)
Or is there a more elegant way?_

What do you think about it?

**Comment by tmat** [comment]
I'm not sure I understand the issue. Can you share the sections of the repository configuration that specify the remotes? Do you specify `url` sections in your repo configuration file (or any other relevant git config)?

**Comment by lobster2012-user** [comment]
Repository URL is setting of project.(VS ui and .csproj) 
Origin repo URL is setting of. git

Did I answer your question?

**Comment by tmat** [comment]
You shouldn't need to set RepositoryUrl property in the project. It's automatically initialized from the origin remote URL by SourceLink if you set PublishRepositoryUrl. RepositoryUrl also has nothing to do with the URL in the generated SourceLink.json file. It's only used for NuGet packages.

Source Link currently doesn't resolve aliases in ssh config. It uses the remote URL specified in git config as is.

**Comment by lobster2012-user** [comment]
In general, everything is clear. 
As I wrote above, for some reason, the behavior depends on the assignment of the repository url.
I would like to see a detailed error and success report for a specific host anyway.

For discussion.

1. Having set the repository url, I assume that this is the link to the code (instead of the settings in .git)

2. I looked at libgit2, it is impossible to look at the host alias from the box. That would be the perfect solution. You can, of course, read .ssh / config via source link.
This eliminates the need to prescribe anything.
I do not know, it would fit all
can be enabled by setting true / false

**Comment by lobster2012-user** [comment]
It is most likely possible to do separate tasks. In the process...
