### ISSUE TITLE
How to step into source when debug?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sourcelink#280]
Hi, I'm using sourceLink  with Github project, but not able to step into a lib source when I debug in another project which has a reference for the lib with source link referenced.

I only reference the `Microsoft.SourceLink.GitHub` package,you can have a look at it [here](https://github.com/WeihanLi/WeihanLi.Common/blob/dev/build/analyzer.props)

```
<PackageReference Condition="'$(OS)' == 'Windows_NT'" Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta2-18618-05" PrivateAssets="All"/>
```

and I'm develop on Visual Studio 2019, and with `Just my code` disabled, source link enabeld

![image](https://user-images.githubusercontent.com/7604648/57577301-76522980-74a6-11e9-8896-2c8e57732aad.png)

I've some questions about using SourceLink, hope someone would like to help, thanks in advance.

1. what's more should I do after reference the source link package? Include symbols/source?
2. is there some options I need modify with the Visual Studio?
3. Is source link can be referenced windows only? It seemed can not build on *nix platform, failed to build on my *nix ci build.

**Comment by tmat** [comment]
> what's more should I do after reference the source link package? Include symbols/source?

You'll need to publish the PDB somehow. Where do you publish package with your library? NuGet.org?

> Is source link can be referenced windows only? It seemed can not build on *nix platform, failed to build on my *nix ci build.

What distro do you build on? What's the failure?

**Comment by WeihanLi** [comment]
Hi @tmat , Thanks for your reply.
Yeah, I'm publishing my library to NuGet.

My failed build with sourceLink is on `Ubuntu 14.04.5 LTS`, build details [here](https://travis-ci.org/WeihanLi/WeihanLi.Common/jobs/523366213), seemed to be a permission problem, fixed with 

```
<PackageReference Condition="'$(OS)' == 'Windows_NT'" Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta2-18618-05" PrivateAssets="All"/>
```

**Comment by WeihanLi** [comment]
Hi @tmat , I've push a package include symbols to nuget, but I can not load the symbols.

[packages here](https://www.nuget.org/packages/WeihanLi.Common/1.0.20-preview-20190517-144622)
symbols load info

```
C:\Program Files\dotnet\WeihanLi.Common.pdb: Cannot find or open the PDB file.
C:\Users\weihanli\.nuget\packages\weihanli.common\1.0.20-preview-20190517-144622\lib\netstandard2.0\WeihanLi.Common.pdb: Cannot find or open the PDB file.
D:\a\1\s\src\WeihanLi.Common\obj\Release\netstandard2.0\WeihanLi.Common.pdb: Cannot find or open the PDB file.
C:\WINDOWS\WeihanLi.Common.pdb: Cannot find or open the PDB file.
C:\WINDOWS\symbols\dll\WeihanLi.Common.pdb: Cannot find or open the PDB file.
C:\WINDOWS\dll\WeihanLi.Common.pdb: Cannot find or open the PDB file.
C:\Users\weihanli\AppData\Local\Temp\SymbolCache\WeihanLi.Common.pdb\85ec611c09bc4f71b5704dd7e3286969ffffffff\WeihanLi.Common.pdb: Cannot find or open the PDB file.
C:\Users\weihanli\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\WeihanLi.Common.pdb\85ec611c09bc4f71b5704dd7e3286969ffffffff\WeihanLi.Common.pdb: Cannot find or open the PDB file.
C:\Users\weihanli\AppData\Local\Temp\SymbolCache\WeihanLi.Common.pdb\85ec611c09bc4f71b5704dd7e32869691\WeihanLi.Common.pdb: Cannot find or open the PDB file.
C:\Users\weihanli\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\WeihanLi.Common.pdb\85ec611c09bc4f71b5704dd7e32869691\WeihanLi.Common.pdb: Cannot find or open the PDB file.
https://nuget.smbsrc.net: Skipped checking location. The symbol file was not found in this location before.
```

**Comment by WeihanLi** [comment]
It seemed to be wrong with the nuget symbols source address

use `https://symbols.nuget.org/download/symbols` instead of `https://nuget.smbsrc.net` is working fine.

refer to:<https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html>
