### ISSUE TITLE
Checksum doesn't match

### ISSUE THREAD

**Issue by darren4ten** [dotnet/sourcelink#284]
I have a problem using sourcelink. 
Source code repository: https://www.nuget.org/packages/SourceLinkTest/1.0.6

`Locating source for 'C:\Users\darren\source\repos\Tests\SLTest\SourceLinkTest\Speaker.cs'. 
Checksum: SHA1 {4d 59 58 6f 6b 74 23 db a7 c3 a7 6f 37 5f aa 1f 56 5b 45 a3}
The file 'C:\Users\darren\source\repos\Tests\SLTest\SourceLinkTest\Speaker.cs' does not exist.
Determining whether the checksum matches for the following locations:
1: C:\Users\darren\AppData\Local\SourceServer\556d13859eda8ad2fd664a22c971673564556c4e2666fa62908f5f257102ee09\SourceLinkTest\Speaker.cs 
Checksum: SHA1 {d 1b 68 14 21 c6 d7 92 9a c0 b6 3e 12 7c 92 cf 66 6c 91 f8} Checksum doesn't match.
Looking in script documents for 'C:\Users\darren\source\repos\Tests\SLTest\SourceLinkTest\Speaker.cs'...
Looking in the Edit-and-Continue directory 'C:\Users\darren\source\repos\TestSLCoreApp\enc_temp_folder\'...
The file with the matching checksum was not found in the Edit-and-Continue directory.
Looking in the projects for 'C:\Users\darren\source\repos\Tests\SLTest\SourceLinkTest\Speaker.cs'.
The file was not found in a project.
Looking in directory 'C:\'...
Looking in directory 'C:\Users\darren\AppData\Local\SourceServer\556d13859eda8ad2fd664a22c971673564556c4e2666fa62908f5f257102ee09\'...
Searching for documents embedded in the symbol file.
An embedded document was not found.
Looking for source using Source Link (https://raw.githubusercontent.com/darren4ten/Test_SLTest/88bb1b461a6ab9708cca9a86f97a8148a22d9d8e/SourceLinkTest/Speaker.cs)...
Looking for source using source server...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: C:\Users\darren\source\repos\Tests\SLTest\SourceLinkTest\Speaker.cs.
The debugger could not locate the source file 'C:\Users\darren\source\repos\Tests\SLTest\SourceLinkTest\Speaker.cs'.`

**Comment by tmat** [comment]
The SourceLink in the package maps paths `C:\Users\darren.teng\source\repos\Tests\SLTest\*` to `https://raw.githubusercontent.com/darren4ten/Test_SLTest/88bb1b461a6ab9708cca9a86f97a8148a22d9d8e/`. 

The path of the source file you are trying to find is `C:\Users\darren\source\repos\Tests\SLTest\SourceLinkTest\Speaker.cs`, which does not match the one the code was built from.
