### ISSUE TITLE
Microsoft.Build.Tasks.Git.dll should use unique assembly version for every release

### ISSUE THREAD

**Issue by AArnott** [dotnet/sourcelink#286]
I get the following errors with beta1 right after downgrading from beta2, building locally with Microsoft.SourceLink.GitHub package:

> C:\Users\andarno\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets(20,5): error MSB4062: The "Microsoft.Build.Tasks.Git.LocateRepository" task could not be loaded from the assembly C:\Users\andarno\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\..\tools\netcoreapp2.0\Microsoft.Build.Tasks.Git.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 
[D:\git\coverlet\test\coverlet.testsubject\coverlet.testsubject.csproj]

As discussed in https://github.com/dotnet/sourcelink/issues/236#issuecomment-472181552_

I tried building again with `/nr:false` and the error went away. So I'm pretty sure what happened is that an msbuild process was lingering from the prior beta2 build and tried to build for beta1 on the next build request. When the assembly version is not unique (or the assembly is not strong name signed) msbuild can't load them side-by-side and will complain with errors like this.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/sourcelink/pull/277. Assemblies in packages version `1.0.0-beta2-19270-01` should have unique versions.
