### ISSUE TITLE
Add support for Bitbucket Cloud

### ISSUE THREAD

**Issue by chris5287** [dotnet/sourcelink#31]
See:
- https://github.com/ctaggart/SourceLink/tree/master/SourceLink.Create.BitBucketServer
- https://github.com/ctaggart/SourceLink/tree/master/SourceLink.Create.BitBucket

**Comment by tmat** [comment]
So it seems that BitBucket uses the same URL pattern as GitLab. Although we would want to have a Microsoft.SourceLink.BitBucket package for convenience, you should be able to use Microsoft.SourceLink.GitLab package to generate SourceLink for BitBucket as well. I have just published the package on myget:

https://dotnet.myget.org/feed/sourcelink/package/nuget/Microsoft.SourceLink.GitLab

Could you please try it and confirm it works with BitBucket?

Apart from the package reference you'll need to specify host like so:

```xml
<ItemGroup>
   <PackageReference Include="Microsoft.SourceLink.GitLab" Version="1.0.0-beta-63001-01" PrivateAssets="all" />
 
   <SourceLinkGitLabHosts Include="{host-name}" />
</ItemGroup>
```

The `{host-name}` is a domain of your BitBucket instance, e.g. "bitbucket.org".

If it builds fine and produces *.sourcelink.json in `obj/{config}/{tfm}` directory of your project with the right content then it works.

**Comment by chris5287** [comment]
@tmat thanks for the head up. Just be aware that Bitbucket server and Bitbucket cloud use different URL patterns, so a change is required to support both types.

**Comment by tmat** [comment]
@chris5287 I see. Yes, we will need a specialized one for Server.

**Comment by tmat** [comment]
@chris5287 Do you know if there is a public documentation on the format of the URL?

**Comment by chris5287** [comment]
Example implementation fetching required details from git url: https://github.com/ctaggart/SourceLink/blob/master/SourceLink.Create.BitBucketServer/BitBucketServerUrlConverter.cs

Sorry couldn’t find public API documentation via a quick google search.

**Comment by ctaggart** [comment]
The second `b` is not capitalized in `Bitbucket`. In this repo, it should be called `Microsoft.SourceLink.Bitbucket`.

**Comment by tmat** [comment]
https://github.com/dotnet/sourcelink/issues/124

**Comment by tmat** [comment]
@ctaggart Bitbucket Enterprise has two options: Server and Data Center. Do you know if they use the same URL formats?

**Comment by ctaggart** [comment]
@tmat I do not. All Bitbucket stuff was contributed by others.
https://github.com/ctaggart/SourceLink/blob/master/SourceLink.Create.CommandLine/BitBucketUrlConverter.cs
https://github.com/ctaggart/SourceLink/blob/master/SourceLink.Create.CommandLine/BitBucketServerUrlConverter.cs

**Comment by ctaggart** [comment]
@chris5287 [contributed it](https://github.com/ctaggart/SourceLink/pull/249/files), and he opened the request here. Hopefully, he knows.

**Comment by ctaggart** [comment]
Hahaha, and they are different. That the first thing he mentioned in this thread.

> thanks for the head up. Just be aware that Bitbucket server and Bitbucket cloud use different URL patterns, so a change is required to support both types.
https://github.com/dotnet/sourcelink/issues/31#issuecomment-393989477

**Comment by chris5287** [comment]
Afraid I only have access to server at work and I have been unable to find any official documentation from atlassian.

**Comment by tmat** [comment]
To clarify: let's use this issue to track support for git repos on bitbucket.org. Microsoft.SourceLink.Bitbucket.Git will be available on myget shortly to support this scenario, so I consider this issue resolved.
I filed a new issue: https://github.com/dotnet/sourcelink/issues/128 to track support for bitbucket Enterprise (Server and Data Center versions).

**Comment by tmat** [comment]
The package is available on MyGet now: [Microsoft.SourceLink.Bitbucket.Git](https://dotnet.myget.org/feed/sourcelink/package/nuget/Microsoft.SourceLink.Bitbucket.Git)

**Comment by tmat** [comment]
@chuckries Does Bitbucket implement auth that the debugger currently supports?

**Comment by chuckries** [comment]
@tmat @JonCubed Yes, BitBucket support is provided via Git Credential Manager for Windows. Source Link Auth for BitBucket is on by default starting in 15.8 Preview. Making BitBucket work in 15.7 requires a hack.

**Comment by ctaggart** [comment]
> Source Link Auth for BitBucket is on by default starting in 15.8 Preview

@chuckries That isn't out yet though, right?

**Comment by chuckries** [comment]
@ctaggart It is out in the latest preview: https://visualstudio.microsoft.com/vs/preview/. BitBucket is enabled by default and requires no configuration. There is a new checkbox under Tools -> Options -> Debugging that will allow GCM to be used for any Source Link request.

**Comment by JonCubed** [comment]
@chuckries that great to hear, looking forward to trying it out
