### ISSUE TITLE
Build error when using mixed Azure DevOps URLs

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/sourcelink#311]
Getting build errors related to SourceLinkUrl is empty when using mixed Azure DevOps URLs and building locally.

This may be related to either of the following issues but I'm unable to work around it either way. 
#190 #79

Repro Steps:
1. From an Azure DevOps site that is using `https://<company>.visualstudio.com/<project>/_git/<repo>` as the default repo URL clone the repo.
2. Ensure Microsoft.SourceLink.Vsts.Git is included as a package.
3. Build the solution and ensure no errors occur.
4. In a new directory git clone the new URL for Azure (`https://dev.azure.com/<company>/<project>/_git/<repo>`.
5. Ensure Microsoft.SourceLink.Vsts.Git is included as a package.
6. Build the solution and errors will occur about the SourceLinkUrl being empty.
7. Following #190 add the `SourceLinkVstsGitHost` attribute to the project.
8. Rebuild and the error still occurs.

Actual Behavior:

Local builds fail with the `SourceLinkUrl is empty` error.

Expected Behavior:

Should be able to build with SourceLink irrelevant of whether the Git repo was cloned via the old or new Azure DevOps URL.

**Comment by tmat** [comment]
Could you share the output of `git remote -vv`? If you can't share publicly feel free to send me an email to tomat@microsoft.com.

**Comment by CoolDadTx** [comment]
@tmat I had git cloned using the `dev.azure.com` link so that is what `git remote -v` returns for the origin. 

```shell
origin  https://dev.azure.com/xxx/xxx/_git/library-configuration (fetch)
origin  https://dev.azure.com/xxx/xxx/_git/library-configuration (push)
```

I get the error when building. However if I git clone using the `visualstudio.com` link then it shows that origin and the build error does not exist.

```shell
origin  https://xxx.visualstudio.com/xxx/_git/library-configuration (fetch)
origin  https://xxx.visualstudio.com/xxx/_git/library-configuration (push)
```

**Comment by tmat** [comment]
Not sure why this doesn't work. Would you mind sharing binlog file privately with me (tomat@microsoft.com)? You can produce one by running `msbuild /bl:log.binlog` on your project.

**Comment by CoolDadTx** [comment]
@tmat, sent you an email

**Comment by tmat** [comment]
@CoolDadTx Thanks. Got it.

**Comment by CoolDadTx** [comment]
Issue was with an older version of the package. Forgot to enable pre-release packages in VS before checking for NuGet updates in order to get the newer package installed. Updating to the newer package resolved the issue.
