### ISSUE TITLE
Using SourceLink with Docker [solved]

### ISSUE THREAD

**Issue by skolima** [dotnet/sourcelink#327]
Following #187  and #159 , SourceLink now nicely works inside Docker container - yay! Thanks.

I had minor issues with the current documentation, though, so I'm posting this as a note. So: I'm using a `.dockerignore` with:

```
# ignore hidden files at root level
.*
```

to not copy `.git` and a few other miscellaneous files into the container. For SourceLink, I've had to modify this to:

```
# ignore hidden files at root level
.*
# keep minimal git info for SourceLink
!.git/HEAD
!.git/config
!.git/refs/heads/master
```

The only unexpected thing was the last line: seems like the default content for `.git/HEAD` is a branch reference, not a raw SHA, so without the last line, I kept getting `warning : Repository has no commit.`.

Having this in `.dockerignore` means `COPY . .` (or anything similarly lazy) JustWorks™ in the `Dockerfile`.

**Comment by tmat** [comment]
That's correct. git allows `HEAD` file to have commit SHA directly in it or a symbolic reference (`refs/heads/master` e.g.). 
If you're using the files as is then it will likely have symbolic reference. You could also have a script that creates the file and puts SHA in it.
The doc should be clearer on this. I'll update and include your `.dockerignore` sample. Thanks for feedback!
