### ISSUE TITLE
.git postfix in RepositoryUrl on some environment

### ISSUE THREAD

**Issue by KoVaLL** [dotnet/sourcelink#328]
I'm using Microsoft.Build.Tasks.Git to get RepositoryUrl at build time and noticed inconsistent behaviour:
$(RepositoryUrl) MSBuild Property, on some environments, get`s resolved with or without .git postfix.
Examples:
https://github.com/nemesissoft/Nemesis.Essentials (on Win10 + VS2019)
https://github.com/nemesissoft/Nemesis.Essentials.git (on AppVeyour Visual Studio 2019 docker image)

It makes creating urls to commits on github harder. 
Example:
This package was built from the source at $(RepositoryUrl)/commit/$(SourceRevisionId)
Will result in incorrect url if .git postfix is there.

Unfortunately I do not have repro project yet.
Version affected: 1.0.0-beta2-19351-01

**Comment by tmat** [comment]
`RepositoryUrl` gets set based on the value of the `origin` remote (unless other remote is specified). If the remote URL includes `.git` suffix it will be included in the `RepositoryUrl`. You can, of course, trim it if you need to.
