### ISSUE TITLE
[Question] SourceLink with classic projects 

### ISSUE THREAD

**Issue by jremien** [dotnet/sourcelink#331]
I have successfully setup sourcelink with non-classic projects to debug library code in nuget packages with source files in an on-prem Bitbucket. I am now trying to figure how to setup sourcelink with classic projects that don't use `<Project` `Sdk="Microsoft.NET.Sdk">` as the readme says: 

> Source Link supports classic .NET Framework projects as well as .NET SDK projects, that is projects that import Microsoft.NET.Sdk (e.g. like so: <Project Sdk="Microsoft.NET.Sdk">). The project may target any .NET Framework or .NET Core App/Standard version. 
> 

The readme also says:

> The following features are not available in projects that do not import Microsoft.NET.Sdk:
- Automatic inclusion of commit SHA in AssemblyInformationalVersionAttribute.
- Automatic inclusion of commit SHA and repository URL in NuSpec.
These features can be added via custom msbuild targets.
> 
So if I'm understanding correctly I should be able to use sourcelink with .NET Framework 4.X (old .csproj format), include the .pdb's in a nuget package and sourcelink to the .cs files in the bitbucket HOWEVER I need to use custom msbuild targets to achieve this (repo url and commit hash in .nuspec). Is my understanding correct? If so, how would I set that up?

**Comment by jremien** [comment]
"These features can be added via custom msbuild targets." So I guess my question is: How can these be added via custom msbuild targets?

**Comment by wjvii** [comment]
I have the same question, is there an example for doing this?

**Comment by tmat** [comment]
> So if I'm understanding correctly I should be able to use sourcelink with .NET Framework 4.X (old .csproj format), include the .pdb's in a nuget package and sourcelink to the .cs files in the bitbucket 

Correct. The above should work without custom target.

> HOWEVER I need to use custom msbuild targets to achieve this (repo url and commit hash in .nuspec). 
Is my understanding correct? If so, how would I set that up?

That depends on how you build nuget packages.

**Comment by wjvii** [comment]
We tried using nuget, dotnet and msbuild to include the sourcelink information in the nuget package and the only one we got to work was msbuild. We use Azure Dev Ops for our automated builds and we configured the classic xxproj files to automatically build the nuget package on each compile and then created a task that copied the resulting nuget packages to the artifactsstaging directory. Below are the snippets from the project file and yaml build file we used for these two steps. So far working great and all the developers can use them and step into the source code from the nuget packages.

  <PropertyGroup>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageOutputPath>bin/$(Configuration)</PackageOutputPath>
  </PropertyGroup>

- task: CopyFiles@2
  displayName: 'copy files'
  inputs:
    contents: '**\bin\**\*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

**Comment by tmat** [comment]
@jremien You're essentially asking how to port Microsoft.NET.Sdk features to classic projects.
Here are some pointers to the feature implementation in the SDK:

> Automatic inclusion of commit SHA in AssemblyInformationalVersionAttribute.

https://github.com/dotnet/sdk/blob/2eb6c546931b5bcb92cd3128b93932a980553ea1/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L51-L62

> Automatic inclusion of commit SHA and repository URL in NuSpec.

https://github.com/NuGet/NuGet.Client/blob/c05f9afa9c2fcee7fbe10754521b3f6424bee128/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L260-L271
