### ISSUE TITLE
 [loc][Query][sourcelink] Localizability of 0; "SourceCodeWontBeAvailableViaSourceLink"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/sourcelink#334]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
{0} The source code won't be available via Source Link.

File Name:
Microsoft.Build.Tasks.Git\xlf\Resources.xlf

==========================================
Query:
Please, define placeholder. We need to know what it will be replaced by for a right translation and format of this sentence.

**Comment by tmat** [comment]
The placeholder is for another error message. E.g. "The path of submodule 'mysubmodule' is missing or invalid: 'invalid character in path'. The source code won't be available via Source Link."

**Comment by PDostalek** [comment]
Thanks for clarification
