### ISSUE TITLE
Microsoft.SourceLink.Vsts.Git does not add the sourcelink JSON

### ISSUE THREAD

**Issue by mangeg** [dotnet/sourcelink#34]
To get it to work I had to manually add a package reference to Microsoft.Build.Tasks.SourceControl. Once that was added it worked.

Comparing to the Github package the difference is that the nuspec for the Github package directly references Microsoft.Build.Tasks.SourceControl as a dependancy, while the VSTS Git/Tfs does not.

**Comment by tmat** [comment]
Yes, there is a bug in the nuspec. Fix is comin soon...
