### ISSUE TITLE
Fails to resolve git packed-refs

### ISSUE THREAD

**Issue by KevinCathcart** [dotnet/sourcelink#343]
When the codebase was changed to use direct Git file reading, instead of libgitsharp, a regression was introduced.

The regression is that when resolving refs, the new code fails to take into account existence of the `packed-refs` file. Therefore, if HEAD points to a packed ref, sourcelink will not be able to find the commit hash, and will fail with the message "Repository has no commit."

This especially impacts TeamCity, since it appears to be writing the packed-refs file directly, instead using the normal `git fetch` workflow, which means that unlike most build scenarios, HEAD will be pointing to a packed ref, rather than a loose one.

**Comment by tmat** [comment]
Thanks for pointing this out. 

https://git-scm.com/docs/git-pack-refs for reference.
