### ISSUE TITLE
Not working any more on .NET 4.6.1

### ISSUE THREAD

**Issue by ravenpride** [dotnet/sourcelink#360]
We have set up a GOCD build server with .NET 4.6.1 to build "older" applications and SourceLink seems to have a problem with that framework version. It exits with the following message (redacted to remove sensitive information):

```
Microsoft.Build.Tasks.Git.targets(24,5): error : Error reading git repository information: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory 'C:\xxx\yyy'.
```

On my development machine it works quite well with .NET 4.7.2.

Any help is appreciated.

Thank you in advance.

**Comment by tmat** [comment]
Could you capture a binary log (`/bl:log.binlog` command line argument to msbuild) and share it? Note that the log contains detailed information about your project and build environment. If you don't want to share it publicly you can send me an email to tomat@microsoft.com

**Comment by ravenpride** [comment]
Sorry, I guess that was my fault. I integrated the SourceLink files from the Nuget packages into our build system and didn't notice that the `System.Collections.Immutable.dll` was hidden by `.gitignore`.  

Ergo, everything is working again.

Many thanks for the help offer!

**Comment by tmat** [comment]
Glad it works!
