### ISSUE TITLE
The value passed to task parameter RepositoryUrl is not a valid host

### ISSUE THREAD

**Issue by JamesNK** [dotnet/sourcelink#381]
CI build using Source Link fails after updating version from `1.0.0-beta2-18618-05` to `1.0.0-beta2-19367-01`

> /root/.nuget/packages/microsoft.sourcelink.github/1.0.0-beta2-19367-01/build/Microsoft.SourceLink.GitHub.targets(36,5): error : The value passed to task parameter RepositoryUrl is not a valid host URI: 'file:///var/local/jenkins/grpc-dotnet' [/var/local/git/grpc-dotnet/src/Grpc.Net.Common/Grpc.Net.Common.csproj]

https://source.cloud.google.com/results/invocations/014c0694-0b01-47ff-984f-0807d46fcbb4/targets/github%2Fgrpc%2Finterop_docker_build/tests

**Comment by tmat** [comment]
How does the CI check out the repository? What are the remote URLs?
Can you produce and share a binlog from the build?

**Comment by JamesNK** [comment]
I think this is it: https://raw.githubusercontent.com/grpc/grpc/master/templates/tools/dockerfile/interoptest/grpc_interop_aspnetcore/build_interop.sh.template

```
git clone /var/local/jenkins/grpc-dotnet /var/local/git/grpc-dotnet
```

I don't own this repository so I'm not sure exact what is going on.

**Comment by tmat** [comment]
This is the problem:
```
git clone /var/local/jenkins/grpc-dotnet /var/local/git/grpc-dotnet
```

The repo remote points to a local directory. It doesn't have a URL. Perhaps we could try to open a repo in the target directory and see if it itself has any remote URLs.

**Comment by JamesNK** [comment]
It is a CI server.

Will this fix it?

```
dotnet pack -p:RepositoryUrl=https://localhost
```

**Comment by tmat** [comment]
Yes, that should do.

**Comment by tmat** [comment]
But not with `localhost` - it needs to be a github.com URL.

**Comment by tmat** [comment]
https://github.com/dotnet/sourcelink/issues/381 is the same issue.
