### ISSUE TITLE
Add support for TFS hosted repositories

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/sourcelink#39]
Do we have support for on-prem TFS scenarios? If not, is it on the roadmap?

**Comment by tmat** [comment]
Support for TFVC repositories in VSTS is on the roadmap.

**Comment by ipjohnson** [comment]
@tmat I'm very interested in this option for on premise TFS. Is there any time frame for this feature?

**Comment by tmat** [comment]
@ipjohnson You can actually try it now. Use the latest version of Microsoft.SourceLink.Vsts.Git package from [MyGet feed](https://dotnet.myget.org/Gallery/sourcelink).
Then set property `SourceLinkVstsGitDomain` in your project file to the name of the domain you host TFS on.

Don't forget that SourceLink requires .NET SDK RC1. If you are building using msbuild (as opposed to `dotnet build`) you'll need version 15.7.

**Comment by ipjohnson** [comment]
@tmat very cool, thanks.

**Comment by ipjohnson** [comment]
@tmat I ran into a couple issue 

1) Error	MSB4062	The "Microsoft.Build.Tasks.Tfvc.LocateRepository" task could not be loaded from the assembly C:\Users\[username]\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta-62915-03\build\..\tools\net461\Microsoft.Build.Tasks.Tfvc.dll. Could not load file or assembly 

I only have a directory for net46. So I renamed it and I got a little further to this error

2) Error	MSB4131	The "Roots" parameter is not supported by the "Microsoft.Build.Tasks.Tfvc.GetSourceRoots" task. Verify the parameter exists on the task, and it is a gettable public instance property.	Ascend.IntegrationServices.MVC	C:\Users\johnsoni\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta-62915-03\build\Microsoft.Build.Tasks.Tfvc.targets

**Comment by tmat** [comment]
@ipjohnson Oh, you're using TFVC, not git? SourceLink for TFVC isn't quite ready yet. We've been focusing on git.

**Comment by ipjohnson** [comment]
@tmat Yeah I've actually got the git version working for my open source projects but we use TFVC at work and I was hoping to get it working their as well. 

Anyways very cool stuff. When you get the TFVC version squared away I'll give it a whirl.

**Comment by kendrahavens** [comment]
I'll go ahead and close this issue since [TFVC is on the roadmap](https://github.com/dotnet/sourcelink/tree/master/src/SourceLink.Vsts.Tfvc) and on-prem TFS with Git is working. Let me know if there are any objections. :)

**Comment by ipjohnson** [comment]
@tmat @kendrahavens Can we open this issue back up? I know TFVC is not the cool thing these days but many, many shops pay for and use TFVC and it feels like it's no longer a first class citizen in Microsoft.

**Comment by tmat** [comment]
@ipjohnson Let's file a new issue specifically tracking support for TFVC (as opposed to TFS).

**Comment by ipjohnson** [comment]
@tmat that works for me. Do you want me to open it or you and I can just subscribe? Also I'd be willing to help test this in the wild as I'm eager to get this working so we can debug internal nuget packages.

**Comment by tmat** [comment]
@ipjohnson Please open it. It'd be clear there is an interest from your side and other folks can vote on it.

**Comment by ipjohnson** [comment]
@tmat I opened issue #122 for this.
