### ISSUE TITLE
Is it possible for this to work at compile time (eg. on go-to-definition) instead of only when running code?

### ISSUE THREAD

**Issue by ProductiveRage** [dotnet/sourcelink#397]
I've been experimenting with this library, it seemed like it would be particularly useful to me after a big solution that I work on was split up into multiple repos and multiple NuGet packages (because this meant that it was no longer as easy to jump around the source code, when references spanned different solutions / repos / packages). And it seems to work great in the debugger, as advertised!

However, I was wondering there is any way for it to work within Visual Studio when navigating code when _not_ actually executing the code? For example, in the "Experience in Visual Studio" screenshot in the README here you have shown the debugger stepping into a method "Foo" in the assembly "RichTestLibrary" - would it be possible to view that source code by using "go to definition" on the method call in the "ConsoleApp20" project without having a debugger attached to a running process? This would be even more useful for exploring code when the code is split across multiple packages!

(Currently, using "go to definition" at compile time goes to the metadata view of the referenced class, rather than going to the source code that is available via SourceLink - and this is what I'd love to see changed!)

I'm using Visual Studio Community 2019 Preview 16.3.0 Preview 2.0.

**Comment by tmat** [comment]
This feature request is tracked by https://github.com/dotnet/roslyn/issues/24349
