### ISSUE TITLE
Instructions do not produce .snupkg, but .symbols.nupkg that is identical to the .nupkg

### ISSUE THREAD

**Issue by cmeeren** [dotnet/sourcelink#398]
Check out [this repo at this commit](https://github.com/cmeeren/FSharp.JsonApi/tree/54019549d186e2bb99633453102f697fcd09ca46) (have disabled SourceLink in later commits). Building (e.g. `dotnet build` from root folder) produces no `.snupkg`, but a `.symbols.nupkg` that is identical to the `.nupkg`.

(It's using paket and not nuget, but I don't think that's relevant.)

`dotnet --version` outputs `2.2.401`, and the behavior is the same when building with VS 16.2.

**Comment by tmat** [comment]
> It's using paket and not nuget, but I don't think that's relevant.

Why do you think it's not relevant? NuGet is the tool that produces the symbol packages, so if you're using paket for packaging then it seems that it would be an issue with paket.

**Comment by cmeeren** [comment]
Sorry, I was unclear. The package is created on `dotnet build` due to the `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` in the fsproj. Paket is only used for the project's dependencies; AFAIK it's not relevant for the packaging done by `dotnet build`. Please correct me if I'm wrong.

**Comment by tmat** [comment]
@nkolev92

**Comment by nkolev92** [comment]
As far as I know, paket also has support for the pack command: https://fsprojects.github.io/Paket/paket-and-dotnet-cli.html#Creating-packages

So I think you might be using paket pack, we'd be happy  to take a look on NuGet side if that's not the case.

**Comment by cmeeren** [comment]
Sorry, my bad, seems like I still have a lot to learn about how the various tools work together.
