### ISSUE TITLE
SourceLink package for TFS (git) produces incorrect path in PDB

### ISSUE THREAD

**Issue by xen22** [dotnet/sourcelink#414]
Using Microsoft Visual Studio Team Foundation Server, Version 16.131.28106.2 (on-prem)

Nuget package version: Microsoft.SourceLink.Tfs.Git 1.0.0-beta2-19367-01

When adding support for SourceLink to a project using the above package, with the following entry in the csproj file:
``` csproj
    <!-- Source Link -->
    <PackageReference Include="Microsoft.SourceLink.Tfs.Git" Version="1.0.0-beta2-19367-01">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <SourceLinkTfsGitHost Include="tfs-server.localdomain.com" VirtualDirectory="DefaultCollection" />
    <!-- Source Link -->

```

After generating the nuget package, the nuspec file contains correct path to the TFS repo:
```
    <repository type="git" url="https://tfs-server.localdomain.com/DefaultCollection/TestProject_git/_git/TestRepo" commit="1b9de839e28ad01332d7d213ec571cfaa6fe6693" />
```

However, the path generated and embedded inside the PDB (in the document entry) is incorrect:
```
https:///tfs-server.localdomain.com/DefaultCollection/TestProject_git/TestRepo/_apis/git/repositories/TestRepo/items?api-version=1.0&versionType=commit&version=1b9de839e28ad01332d7d213ec571cfaa6fe6693&path=/*"
```

This is then passed to Visual Studio, which is unable to find the source file:
```
https://tfs-server.localdomain.com/DefaultCollection/TestProject_git/TestRepo/_apis/git/repositories/TestRepo/items?api-version=1.0&versionType=commit&version=1b9de839e28ad01332d7d213ec571cfaa6fe6693&path=/Core.Api/Helpers/AuthTokenHelper.cs
```

The above path should not have a "TestRepo" before "/_apis/git/...". The correct path is:
```
https://tfs-server.localdomain.com/DefaultCollection/TestProject_git/_apis/git/repositories/TestRepo/items?api-version=1.0&versionType=commit&version=1b9de839e28ad01332d7d213ec571cfaa6fe6693&path=/Core.Api/Helpers/AuthTokenHelper.cs
```

**Comment by xen22** [comment]
Related issue: #156 (not the authentication part but the invalid path resulting in 404)

**Comment by tmat** [comment]
I think VirtualDirectory should be set to `/`, not `DefaultCollection`.

**Comment by tmat** [comment]
Here is the schema of the TFS URL: https://github.com/dotnet/sourcelink/blob/master/docs/Implementation/TeamFoundationUrlParser.md#tfs-url-format

**Comment by xen22** [comment]
Confirming that changing the VirtualDirectory to `/` (from `DefaultCollection`) fixed the issue.
Thanks very much @tmat!

Closing now.

**Comment by tmat** [comment]
@xen22 Is there anything we should add to the docs to clarify what the value should be?

**Comment by xen22** [comment]
An example would be great, for people who are not familiar with the URI and path structure in TFS (probably also worth mentioning that "DefaultCollection" is not part of the virtual directory)
