### ISSUE TITLE
How to set git repository URL when building from a local repository

### ISSUE THREAD

**Issue by pepone** [dotnet/sourcelink#418]
```
<PropertyGroup>
    <RepositoryUrl>https://github.com/zeroc-ice/ice</RepositoryUrl>
</PropertyGroup>
```

Build is emitting this warning
```
"D:\3.7\dist-utils\build\ice\builds\ice-v141\csharp\src\Ice\msbuild\netstandard2.0\ice.csproj" (default target) (13:15) ->
(_GenerateSourceLinkFile target) ->
  C:\Users\ppgut\.nuget\packages\microsoft.sourcelink.common\1.0.0-beta2-19367-01\build\Microsoft.SourceLink.Common.targets(50,5): warning : Source control information is not available - the generated sourc
e link is empty. [D:\3.7\dist-utils\build\ice\builds\ice-v141\csharp\src\Ice\msbuild\netstandard2.0\ice.csproj]
```

I setting `RepositoryUrl` because my repository is a clone of a local version

```
[remote "origin"]
        url = D:\\3.7\\dist-utils\\build\\ice\\downloads\\ice
        fetch = +refs/heads/*:refs/remotes/origin/*
```

How is the correct way to set the repository URL when origin doesn't point to the public URL?

**Comment by tmat** [comment]
Does the repo at `D:\\3.7\\dist-utils\\build\\ice\\downloads\\ice` have `origin` remote that points to a URL?

**Comment by tmat** [comment]
To work around you can add a remote `public` with the public URL to your repo configuration and then set `<GitRepositoryRemoteName>public</GitRepositoryRemoteName>` in your project. Source Link will then use the `public` remote URL.
