### ISSUE TITLE
Add support for GitLab hosted repositories

### ISSUE THREAD

**Issue by tmat** [dotnet/sourcelink#42]
Support for GitLab hosted repositories.

**Comment by paulomorgado** [comment]
What's delaying this? Can I help?

**Comment by tmat** [comment]
Working on it.

**Comment by tmat** [comment]
I've just published a Microsoft.SourceLink.GitLab package for GitLab:

https://dotnet.myget.org/feed/sourcelink/package/nuget/Microsoft.SourceLink.GitLab

Could you please try it and confirm it works in your environment?

Apart from the package reference you'll need to specify host like so:

```xml
<ItemGroup>
   <PackageReference Include="Microsoft.SourceLink.GitLab" Version="1.0.0-beta-63001-01" />
 
   <SourceLinkGitLabHosts Include="{host-name}" />
</ItemGroup>
```

The `{host-name}` is a domain of your GitLab instance, e.g. "mygitlab.com".

If it builds fine and produces *.sourcelink.json in `obj/{config}/{tfm}` directory of your project with the right content then it works.

**Comment by tmat** [comment]
Package https://www.nuget.org/packages/Microsoft.SourceLink.GitLab will soon be available.
