### ISSUE TITLE
Can't get Visual Studio to debug a SourceLink'd nuget package

### ISSUE THREAD

**Issue by joshmouch** [dotnet/sourcelink#423]
I'm having problems debugging a particular NuGet package from Visual Studio that claims to have SourceLink enabled.

When I right-click on the module in VS and click "Load Module", it eventually pops up and asks me for the PDB file (which I don't have).

If I create a new BreakPoint with one of the method names from the nuget package, nothing happens.

Here is the NUSPEC from the package.  I see a `<repository>` element, which I think means that it should work:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>IdentityServer4</id>
    <version>3.0.1</version>
    <authors>Brock Allen,Dominick Baier</authors>
    <owners>Brock Allen,Dominick Baier</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">Apache-2.0</license>
    <licenseUrl>https://licenses.nuget.org/Apache-2.0</licenseUrl>
    <projectUrl>https://github.com/IdentityServer/IdentityServer4</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/IdentityServer/Artwork/master/Logos/IDserver_icon128.jpg</iconUrl>
    <description>OpenID Connect and OAuth 2.0 Framework for ASP.NET Core</description>
    <releaseNotes>https://github.com/IdentityServer/IdentityServer4/releases</releaseNotes>
    <tags>OAuth2 OAuth 2.0 OpenID Connect Security Identity IdentityServer</tags>
    <repository type="git" url="https://github.com/IdentityServer/IdentityServer4.git" commit="e31ddc9906fa295c50e6191bda3326882b78d91f" />
    <dependencies>
      <group targetFramework=".NETCoreApp3.0">
        <dependency id="IdentityModel" version="4.0.0" exclude="Build,Analyzers" />
        <dependency id="IdentityServer4.Storage" version="3.0.1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.Authentication.OpenIdConnect" version="3.0.0" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="12.0.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkReferences>
      <group targetFramework=".NETCoreApp3.0">
        <frameworkReference name="Microsoft.AspNetCore.App" />
      </group>
    </frameworkReferences>
  </metadata>
</package>
```

**Comment by tmat** [comment]
The debugger can't find the PDB. Do you have symbol servers configured (see https://github.com/dotnet/sourcelink/issues/422#issuecomment-535571668)?

**Comment by joshmouch** [comment]
I've tried with symbol servers on and off.
The two servers that are checked in the screenshot you have linked are checked.

**Comment by tmat** [comment]
There is a log on the page that debugger displays when it can't find the PDB. What does it say?

**Comment by joshmouch** [comment]
I pointed the dialog to:
C:\Users\josh\.nuget\packages\identityserver4\3.0.1\lib\netcoreapp3.0\IdentityServer4.pdb
and now it's working.
Isn't this supposed to be automatic?

**Comment by tmat** [comment]
I see. So it seems that the package does not publish symbols to NuGet symbol server (snupkg). 
Instead it has them in the main package itself. These PDBs are supposed to be copied to the output directory, where they'd be found by the debugger next to the .dll. Chan you double check that the PDBs are not in the output dir?

If so, could you clean and run `dotnet rebuild /bl:build.binlog`? Then share `build.binlog`. Note: the log contains detailed information about your environment, so if you don't want to share it publicly you can send me email to tomat@microsoft.com

**Comment by joshmouch** [comment]
They are not copied to the output directory.  The PDB's for my own code exists, but there are no PDBs for any nuget packages.

![image](https://user-images.githubusercontent.com/3098820/65713335-f8fb1000-e066-11e9-8545-2c3b0e981b44.png)

![image](https://user-images.githubusercontent.com/3098820/65713392-17f9a200-e067-11e9-9522-5f1d93e007c8.png)

**Comment by tmat** [comment]
@nguerrera Did copying PDBs from nuget dir to output dir break?

**Comment by tmat** [comment]
Turns out the PDBs were never copied, but previous versions of .NET Core were loading dependencies directly from NuGet cache, so the debugger found the PDBs there. .NET Core 3.0 does not do that anymore, resulting in a break.

Issue tracked by https://github.com/dotnet/sdk/issues/1458
