### ISSUE TITLE
Using SourceLink without source control?

### ISSUE THREAD

**Issue by bradwilson** [dotnet/sourcelink#426]
(Yes, I do have source control, but let's pretend I don't.)

I would like to use SourceLink to embed all my source files into the PDB file, without having any visible source control system. I am confronted with this warning:

```
/home/dotnet/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19367-01/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory '/app/src'. [/app/src/<project>.csproj]
/home/dotnet/.nuget/packages/microsoft.sourcelink.common/1.0.0-beta2-19367-01/build/Microsoft.SourceLink.Common.targets(50,5): warning : Source control information is not available - the generated source link is empty. [/app/src/<project>.csproj]
```

(a) Is that warning important?
(b) Is there a way to suppress it?

**Comment by tmat** [comment]
You don't need Source Link then. Just set [`EmbedAllSources`](https://github.com/dotnet/sourcelink/tree/master/docs#embedallsources) to `true` in your project and the compiler will include all sources in the PDB.

**Comment by bradwilson** [comment]
Ah, thanks! I thought that EmbedAllSources happened via SourceLink. It's good to know that that behavior comes from the compiler!
