### ISSUE TITLE
Possible to relay repository information to containerized build?

### ISSUE THREAD

**Issue by ugumba** [dotnet/sourcelink#429]
We're investigating containerized builds, i.e. encapsulating the build/publish in Dockerfile (as provided by the standard Dockerfile provided by Visual Studio for a .net core project).

Within the container, .git is not available - is there a way to capture and relay the needed information into the container for the SourceLink packaging to work?

Including the .git folder in the Docker context is not an option - it is simply too large.  Furthermore the repo may be a submodule, where ".git" is simply a symbolic link to within the parent repository's .git.

**Comment by tmat** [comment]
See https://github.com/dotnet/sourcelink/tree/master/docs#minimal-git-repository-metadata

**Comment by ugumba** [comment]
Thanks! All I needed to know!
