### ISSUE TITLE
Add support for GitHub Enterprise hosted repositories.

### ISSUE THREAD

**Issue by tmat** [dotnet/sourcelink#43]
Support for GitHub Enterprise hosted repositories.

**Comment by ctaggart** [comment]
This is the one I need, so let me know if I can help out here. I created [a VS User Voice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/34328269-debugger-should-support-generic-authentication-wit) for the the necessary debugger support @gregg-miskelly. Ideally VS Code debugger too. I've added a request for [Rider as well](https://youtrack.jetbrains.com/issue/RIDER-16260).

**Comment by Chase-Dickerson** [comment]
Would love to have this! I currently get "error : unable to convert OriginUrl" when building with the commnad `dotnet build /p:SourceLinkCreate=true /v:n`.

**Comment by tmat** [comment]
@Chase-Dickerson Note that Microsoft.SourceLink packages have different implementation and use different settings than previous versions of SourceLink packages, so `/p:SourceLinkCreate=true` is not applicable. See https://github.com/dotnet/sourcelink#using-sourcelink

**Comment by tmat** [comment]
@ctaggart So in general, for each host provider (GitLab, GitHub Enterprise, etc.) we need to find out how they map URLs stored in git remote/submodule link to raw content URLs. 

If GitHub Enterprise uses the same pattern for raw URLs as public GitHub we can use the existing Microsoft.SourceLink.GitHub package -- the task can now be be parameterized by domain: https://github.com/dotnet/sourcelink/blob/master/src/SourceLink.GitHub/build/Microsoft.SourceLink.GitHub.targets#L20-L29

Would you mind checking if this works?

**Comment by tmat** [comment]
Cool. `ContentUrl` is a base URL, so this should work then:

````
<SourceLinkGitHubHosts Include="github.ecorp.test" ContentUrl="https://github.ecorp.test/raw" />
````

Please try and let me know. Maybe this issue can be closed right away! :)

**Comment by ctaggart** [comment]
How are you expecting me to test it? Using `dotnet sourcelink test` or something else?

**Comment by tmat** [comment]
Use Microsoft.SourceLink.GitHub package in a project hosted in GitHub Enterprise and add 
```
<ItemGroup>
   <SourceLinkGitHubHosts Include="github.ecorp.test" ContentUrl="https://github.ecorp.test/raw" />
</ItemGroup>
```

If it builds fine and produces *.sourcelink.json in `obj/{config}/{tfm}` directory with the right content then it works.

**Comment by TDabasinskas** [comment]
Hi, @tmat,

Unfortunately, this does not work, duo to the following validation in https://github.com/dotnet/sourcelink/blob/master/src/SourceLink.GitHub/GetSourceLinkUrl.cs#L110:

```csharp
bool isHostUri(Uri uri) => uri.PathAndQuery == "/" && uri.UserInfo == "";
```

It prevents the `ContentUrl` from containing anything in the path (i.e. `raw`), resulting in the following error:

```
The value passed to task parameter Hosts is not a valid host URI: https://github.ecorp.test/raw
```

Would it be possible to update `isHostUri` to allow having `/raw/` inside the path?

**Comment by tmat** [comment]
I see. I'll take a look.

**Comment by tmat** [comment]
I have made some changes that should fix this problem.

Could you please try version 1.0.0-beta-63001-01 from [myget feed](https://dotnet.myget.org/Gallery/sourcelink)?

You can now omit the `ContentUrl` - it defaults to `https://{host}/raw`, so this should be sufficient:

```xml
<ItemGroup>
   <SourceLinkGitHubHosts Include="github.ecorp.test" />
</ItemGroup>
```

**Comment by TDabasinskas** [comment]
Thanks, @tmat.

On my local Windows machine it seems to be working and correct `*.sourcelink.json` file is generated.

Anyhow, using both `microsoft/dotnet:2.1-sdk-alpine` or `microsoft/dotnet:2.1-sdk` docker images, the build fails during CI job. It seems that both Alpine and Debian Stretch images are missing some dependencies (`libcurl-gnutls.so.4`, `libssl.so.1.0.0`) required by this package, resulting into build failures. I tried adding these packages to the images manually, yet I still couldn't get this working.

Do you have a way to test the package inside a Linux docker container?

**Comment by tmat** [comment]
@TDabasinskas We need [libgit2](https://github.com/libgit2/libgit2) to provide binaries for these distros. Currently we only test Ubuntu. A similar [issue](https://github.com/dotnet/sourcelink/issues/66) is filed for Fedora distro.

@bording FYI

**Comment by TDabasinskas** [comment]
Thanks, @tmat.

I'll subscribe to the issue you mentioned, so I could test it once it's available.

**Comment by ctaggart** [comment]
Confirming that I get the same problem as @TDabasinskas  with `1.0.0-beta-62925-02` and that it is fixed in `1.0.0-beta-63001-01`. It would be nice to have an updated beta pushed to nuget.org.

**Comment by ctaggart** [comment]
Oh yeah, also confirming @tmat, that it worked as you described:
``` xml
<ItemGroup>
   <SourceLinkGitHubHosts Include="github.ecorp.test" />
</ItemGroup>
```

**Comment by tmat** [comment]
@ctaggart Thanks for testing it out. I'm working on another change that will allow to infer the host from the origin remote automatically, so that if you have just a single host domain (the common case) you won't need to specify it.

https://github.com/dotnet/sourcelink/pull/80

**Comment by tmat** [comment]
Done.

**Comment by cdonnellytx** [comment]
@tmat One thing I found is that  `SourceLinkGitHubHosts` is also needed if you need to override the `ContentUrl`.  The GHE my company uses is hosting raw files at `raw.ghe.ecorp.test` and not `ghe.ecorp.test/raw`.

**Comment by tmat** [comment]
@cdonnellytx That's right. Thanks for pointing it out.
