### ISSUE TITLE
Where are the sources cached?

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/sourcelink#440]
For testing purposes I want to force sourcelink pull the sources from the server. I tried to find the cache, but I was not able to delete it. Can you tell me how to clear the cache, so that a http request is performed again, when i debug into a remote source?

**Comment by tmat** [comment]
VS debugger stores sources downloaded from source server in 
`%UserPprofile%\AppData\Local\SourceServer` directory.

**Comment by wsy** [comment]
> VS debugger stores sources downloaded from source server in
> `%UserPprofile%\AppData\Local\SourceServer` directory.

@tmat 
Execuse me. Can I move this folder in settings of Visual Studio 2019?

**Comment by tmat** [comment]
@chuckries

**Comment by chuckries** [comment]
@wsy unfortunately this folder can't be changed today, I will log a bug on VS to allow this to be changed in a future release.

**Comment by chuckries** [comment]
@wsy here is the Visual Studio issue: https://developercommunity.visualstudio.com/t/source-link-download-locationcache-cannot-be-chang/1429430?from=email

**Comment by wsy** [comment]
Thanks!

**Comment by calgagi** [comment]
@wsy This will be out in Dev17 preview 2. You will be able to add a new registry string value to a VS instance's private registry at `Software\Microsoft\VisualStudio\17.0_<instance_number>\Debugger` called `SourceLinkExtractToDirectory`. The string will be the full path to the folder you would like SourceLink to download files to.

**Comment by wsy** [comment]
That's great!
