### ISSUE TITLE
 [loc][Query][sourcelink] Localizability of 0; "RepositoryDoesNotHaveSpecifiedRemote"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/sourcelink#449]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Repository '{0}' does not have the specified remote '{1}'; using '{2}' instead.

File Name:
Microsoft.Build.Tasks.Git\xlf\Resources.xlf

==========================================
Query:
What does "remote" refer to here? We understood as "remote connection" for now, please confirm or advise.

Similar string:
Repository '{0}' has no remote.
0; "RepositoryHasNoRemote"

**Comment by tmat** [comment]
`remote` is short hand for "remote repository" - a term Git uses for a specification of a remote repository location: https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes

**Comment by PDostalek** [comment]
Many thanks
