### ISSUE TITLE
Is a stable version coming?

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/sourcelink#455]
I've been using SourceLink for a while now, and as far as I can tell, it works fine. So why are all the packages still in beta?
It doesn't keep me from using it, but I'm curious...

**Comment by tmat** [comment]
It is coming soon.

**Comment by tmat** [comment]
SourceLink 1.0.0 is now available

https://www.nuget.org/packages/Microsoft.SourceLink.GitHub/1.0.0
https://www.nuget.org/packages/Microsoft.SourceLink.GitLab/1.0.0
https://www.nuget.org/packages/Microsoft.SourceLink.Bitbucket.Git/1.0.0
https://www.nuget.org/packages/Microsoft.SourceLink.AzureRepos.Git/1.0.0
https://www.nuget.org/packages/Microsoft.SourceLink.AzureDevOpsServer.Git/1.0.0

**Comment by thomaslevesque** [comment]
Awesome, thanks!
