### ISSUE TITLE
dotnet pack Doubles SourceRoot Include Folder

### ISSUE THREAD

**Issue by wjvii** [dotnet/sourcelink#458]
Everything appears to work fine when building in Azure DevOps Build Pipeline but if I want to run a dotnet pack locally and I have a Directory.Builds.props file that defines the Source Root include as follows I get:

<SourceRoot Include="D:\Git\Test\"

error MSB4094: "D:\Git\Test\;D:\Git\test\" is an invalid value for the "SourceRoot" parameter of the "Microsoft.SourceLink.Vsts.Git.GetSourceLinkUrl" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem".

Not sure why it shows the my root Git folder twice but I am guessing that is what it is complaining about.

**Comment by tmat** [comment]
>  I have a Directory.Builds.props file that defines the Source Root include as follows 

Why do you manually add a SourceRoot? The SourceLink package adds one automatically for the repo.

**Comment by wjvii** [comment]
I tried removing it from the props file and now I get:

The value of SourceRoot.RepositoryUrl with identity 'D:\Git\Test\' is invalid: 'https://dev.azure.com/xyz/_git/xyz' 

Where does it get it from when building locally dotnet pack

**Comment by tmat** [comment]
Can you run with `/bl:build.binlog` and share the log file with me? Since the log captures the build environment of your machine you might not want to share it publicly. You can send it to tomat@microsoft.com.

**Comment by tmat** [comment]
@wjvii Have you had a chance to send the log? Checking as it might have ended up in spam.

**Comment by wjvii** [comment]
@tmat, my apologies it took so long. I emailed it to you today. Please feel free to contact me via the email or continue the conversation here. I did find a package that appears it packs fine, would you like those logs too to see the difference? I can provide more non-working examples as well.

**Comment by tmat** [comment]
I can still see in the binlog that file `D:\git\hwc\Directory.Build.props` adds a SourceRoot:

```xml
  <ItemGroup>
    <SourceRoot Include="D:\Git\HWC\" RepositoryUrl="https://dev.azure.com/..." />
  </ItemGroup>
```

Could you try to remove it?

**Comment by tmat** [comment]
Also, you don't need to specify `RepositoryUrl` (in the same file)

**Comment by tmat** [comment]
Looks like Soruce Link for Azure Repos is not handling certain URLs correctly:

**Comment by SJMakin** [comment]
For posterity, just seen this error when someone had duplicate submodules with the different casing. Only workaround was to change the paths.
