### ISSUE TITLE
BitBucket Server URL Generated Can Be Wrong

### ISSUE THREAD

**Issue by nickdalt** [dotnet/sourcelink#461]
The way the SourceLink.Bitbucket.Git package generates the URL is incorrect for some configurations of BitBucket server.

The code [GetSourceLinkUrl.cs](https://github.com/dotnet/sourcelink/blob/master/src/SourceLink.Bitbucket.Git/GetSourceLinkUrl.cs)

```
            var splits = relativeUrl.Split(new[] {'/'}, StringSplitOptions.RemoveEmptyEntries);
            var isSshRepoUri = !(splits.Length == 3 && splits[0] == "scm");
            var projectName = isSshRepoUri ? splits[0] : splits[1];
            var repositoryName = isSshRepoUri ? splits[1] : splits[2];
```
Splits the relative URL calculated from the repository and then looks at fixed positions for the project key and repository name. This only works where there are no additional path elements at the start of the git url. So for example if the BitBucket base URL is:-

https://server.com/bitbucket

It then incorrectly calculates the project key as scm and the repository name as bitbucket.

I think what if needs to do is calculate the relative URL by removing the common parts of the git URL and the content URL.

**Comment by tmat** [comment]
/cc @adam-sajdak

@nickdalt Is there a specification of the URL format we can use?

> I think what if needs to do is calculate the relative URL by removing the common parts of the git URL and the content URL.

Are you saying that the URI calculation does not work correctly if the project specifies `ContentUrl` attirbute in `SourceLinkBitbucketGitHost` item like so?

```
 <SourceLinkBitbucketGitHost Include="server.com" ContentUrl="http://server.com/bitbucket"/>
```

**Comment by nickdalt** [comment]
There is no specification for the base URL since that is a choice made by the server administrator. In my case all the Atlassian tools are hosted off the same domain so we have:-

https://server.com/bitbucket
https://server.com/jira
https://server.com/confluence

If the bitbucket part is removed from the `relativeUrl` the rest of the algorithm is correct.
 
The URI calculation does not currently work on my server setup no matter what `ContentUrl` is. If `ContentUrl` is not specified then the next few lines 

```
            var relativeUrlForBitbucketEnterprise =
                GetRelativeUrlForBitbucketEnterprise(projectName, repositoryName, revisionId,
                    bitbucketEnterpriseVersion);
            var result = UriUtilities.Combine(contentUri.ToString(), relativeUrlForBitbucketEnterprise);
```
will result in the final URL being generated incorrectly even if the `relativeUrlForBitbucketEnterprise` was corrects since it will use the Include value.

https://server.com/relativeUrlForBitbucketEnterprise

instead of the correct value

https://server.com/bitbucket/relativeUrlForBitbucketEnterprise

**Comment by tmat** [comment]
I see. The relative URL can have two forms:

HTTP: `{baseUrl}/scm/{projectName}/{repositoryName}`
SSH: `{baseUrl}/{projectName}/{repositoryName}`

and currently the logic only supports empty `baseUrl`.
