### ISSUE TITLE
SourceLink fails in git worktree and emits many build warnings

### ISSUE THREAD

**Issue by AArnott** [dotnet/sourcelink#473]
When building in a worktree, all projects emit this warning:

> ...\microsoft.build.tasks.git\1.0.0-beta2-19367-01\build\Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory 'D:\git\MessagePack-CSharp.v1.8\src\MessagePack.ReactiveProperty'.

Using Microsoft.SourceLink.GitHub v1.0.0-beta2-19367-01.
Similar to #347

**Comment by tmat** [comment]
The problem is with `commondir` file containing a relative path that we don't normalize.
