### ISSUE TITLE
1.0 of Microsoft.SourceLink.Tfs.Git?

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/sourcelink#513]
The 1.0 milestone is complete, Microsoft.SourceLink.GitHub is 1.0, and the repo was tagged 1.0. Just wondering a 1.0 of Microsoft.SourceLink.Tfs.Git will also be released?

**Comment by tmat** [comment]
Microsoft.SourceLink.Tfs.Git has been renamed to Microsoft.SourceLink.AzureDevOpsServer.Git.
See https://github.com/dotnet/sourcelink#azure-devops-server-former-team-foundation-server

**Comment by SimonCropp** [comment]
given there are likely a significant number of people on that old package, who will no no way discover the rename as it currently stands. perhaps it should be marked as deprecated in nuget with a forward to Microsoft.SourceLink.AzureDevOpsServer.Git  ?

**Comment by SimonCropp** [comment]
also, moving forward, will `Microsoft.SourceLink.AzureDevOpsServer.Git` continue to be compat with on prem TFS?

**Comment by tmat** [comment]
> perhaps it should be marked as deprecated in nuget 

Yes, I plan to do that.

> also, moving forward, will Microsoft.SourceLink.AzureDevOpsServer.Git continue to be compat with on prem TFS?

Yes, the package is dedicated to on-prem TFS, whose official name is now Azure DevOps Server.
