### ISSUE TITLE
Bitbucket bad links in pdb

### ISSUE THREAD

**Issue by pmaslan** [dotnet/sourcelink#581]
Hi,

we are using self-hosted Bitbucket. When we build a package we have in pdb file wrong links:
`https://<mydomain>/projects/<myproject>/repos/<myrepository>/raw/*?at=f7d9b9c158195820c702192be37120bffa51481Repository/<pathToFile>`
instead of
`https://<mydomain>/projects/<myproject>/repos/<myrepository>/raw/Repository/<pathToFile>?at=f7d9b9c158195820c702192be37120bffa514811`

csproj:
```<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.Bitbucket.Git" Version="1.0.0" PrivateAssets="all" />
    
    <SourceLinkBitbucketGitHost Include="mydomain" EnterpriseEdition="true" />
  </ItemGroup>
</Project>```

**Comment by tmat** [comment]
What version of the server do you use?

**Comment by pmaslan** [comment]
Atlassian Bitbucket v5.16.1

**Comment by pmaslan** [comment]
It looks like replace of "*" by a path to a source file doesn't work well. A path to source file is added to the end and in a commit id missing the last character,

**Comment by mjirhage** [comment]
What is the status of this bug? I am having the same issue, except that the commit id is correct.

**Comment by tmat** [comment]
@mjirhage 
I'm not seeing where the bad URL is coming from:
```
https://<mydomain>/projects/<myproject>/repos/<myrepository>/raw/*?at=f7d9b9c158195820c702192be37120bffa51481Repository/<pathToFile>
```

Would you mind sharing the binlog of your build (`dotnet build /bl:log.binlog`)? You can send it to tomat@microsoft.com if you don't want to share it publicly.

**Comment by mjirhage** [comment]
Thank you for your quick response. I have just sent it to you.

**Comment by tmat** [comment]
@mjirhage Based on the info you provided I believe the bug is actually in NuGet Package Explorer.

@pmaslan How did you find out that the URL is wrong? Any chance you used NuGet Package Explorer as well?

**Comment by pmaslan** [comment]
@tmat Yes, I found out it in NuGet Package Explorer.

**Comment by tmat** [comment]
Closing in favor of https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/1201.
