### ISSUE TITLE
Prevent changing assembly version

### ISSUE THREAD

**Issue by josh-endries** [dotnet/sourcelink#582]
Is there a way to prevent SourceLink from messing with the assembly version? If I have this in my project file:

`<Version>1.0</Version>`

This is what happens when you specify it in the VS GUI. I would expect the resulting DLL to use that version, but it doesn't, it includes the hash in the product version.

I don't recall this happening previously with SourceLink,, but this is a new Core app and I think previously I've only used Framework libraries, or maybe something else changed, or I just never noticed...

My understanding was that the source info was embedded somewhere, this change seems much more public (and IMHO ugly). The URL needs to be somewhere else, so I don't feel like this info is even useful, really, and if the URL is elsewhere why can't it contain the hash? I feel like this is how it used to work, I remember VS asking about downloading source from a URL that contained the hash/commit... I'm using Azure Repos (Git).

Is it possible to disable this behavior?

This is my project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Version>1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.KeyVault" Version="3.0.5" />
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="4.1.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.2" />
    <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="app-settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

**Comment by tmat** [comment]
Do you actually mean the `AssemblyInformationalVersion`? The SDK does not change the AssemblyVersion itself.
You can remove the commit hash from `AssemblyInformationalVersion` by setting `IncludeSourceRevisionInInformationalVersion` to `false`.

The commit hash is useful to be able to quickly find the commit corresponding to the version.
