### ISSUE TITLE
Is there a requirement that each class/interface is in their own file for SourceLink to work?

### ISSUE THREAD

**Issue by woodne** [dotnet/sourcelink#590]
If I have a class or interface like below:

```C#
public interface IMyInterface {
}

public class MyClass : IMyInterface {
}
```

in a file called MyStuff.cs, will sourcelink work? The behavior I think I am seeing, if I try to load `IMyInterface`, it tries to load a file called `IMyInterface.cs`, which doesn't exist.

**Comment by tmat** [comment]
No, there is no such requirement.

**Comment by woodne** [comment]
Ok. Thanks. Guess this is a weirdness in the way that Rider/Resharper pull the source files.
