### ISSUE TITLE
VSCode/Omnisharp Meaningless Warnings

### ISSUE THREAD

**Issue by JustinKaffenberger** [dotnet/sourcelink#595]
# Issue Summary

In an otherwise healthy repository that loads and builds in Visual Studio 2019 and MSBuild, when trying to load that same repository in Visual Studio Code, a bunch of negligible warnings pop up for all projects that implement Source Link. For example:

> [warn]: OmniSharp.MSBuild.ProjectLoader Source control information is not available - the generated source link is empty.

However, the project subsequently loads just fine:

> [info]: OmniSharp.MSBuild.ProjectManager Successfully loaded project file 'c:\dev\git\Foo\src\Bar\Bar.csproj'.
c:\dev\git\Foo\src\Bar\Bar.csproj
C:\Users\Me\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\Microsoft.SourceLink.Common.targets(52,5): Error: Source control information is not available - the generated source link is empty.

While this issue doesn't block development, it adds significant overhead in that the whole Omnisharp log needs to be validated to ensure there aren't any _real_ issues with the projects.

An example of how Source Link is configured in all of our projects:

```xml
    <PropertyGroup>
      <PublishRepositoryUrl>true</PublishRepositoryUrl>
      <EmbedUntrackedSources>true</EmbedUntrackedSources>
      <EnableSourceLink>true</EnableSourceLink>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="1.0.0" PrivateAssets="All"/>
    </ItemGroup>
```

Any ideas? Thanks in advance. 

# Environment
- OS: Windows 10
- VS Code: 1.43.2
- Omnisharp: 1.34.14
- Microsoft.SourceLink.AzureRepos.Git: 1.0.0

**Comment by tmat** [comment]
Can you share a build log? Run `dotnet build /bl:log.binlog` on the project from command line. You can send the binlog to tomat@microsoft.com to avoid disclosing private environment info.

**Comment by JustinKaffenberger** [comment]
I've created a minimal reproduction repository here: https://github.com/JustinKaffenberger/sourcelink_595

I've attached the .binlog, and below is the Omnisharp output:

```
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\dev\git\sourcelink_595\src\Foo\Foo.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\dev\git\sourcelink_595\src\Foo\Foo.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        Source control information is not available - the generated source link is empty.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\dev\git\sourcelink_595\src\Foo\Foo.csproj'.
c:\dev\git\sourcelink_595\src\Foo\Foo.csproj
C:\Users\jkaffenberger\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\Microsoft.SourceLink.Common.targets(52,5): Error: Source control information is not available - the generated source link is empty.

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Foo

```

[log.zip](https://github.com/dotnet/sourcelink/files/4383149/log.zip)

**Comment by tmat** [comment]
The logs show that Source Link works correctly when invoked from command line build. 
The problem seems to be in how OmniSharp loads the project. All Source Link targets are disabled during design-time-builds (when `DesignTimeBuild` is `true`). I wonder if OmniSharp does not set `DesignTimeBuild` properly.

**Comment by JustinKaffenberger** [comment]
Thanks @tmat , I'll see if I can open an issue with Omnisharp.
