### ISSUE TITLE
VS 2019 fails to authenticate git credentials against Bitbucket cloud repo

### ISSUE THREAD

**Issue by gonzaloluna** [dotnet/sourcelink#597]
I can't get this to work. Tried removing credentials from Windows Credential Manager. Reinstalling GCM. What am I doing wrong??

I have a private repo in a Bitbucket cloud account.
Visual Studio 2019 16.3.10 
git-credential-manager (v1.18.4)
My library csproj:

   ```
   ....
<PublishRepositoryUrl>true</PublishRepositoryUrl>
   <EmbedUntrackedSources>true</EmbedUntrackedSources>
   <IncludeSymbols>true</IncludeSymbols>
   <SymbolPackageFormat>snupkg</SymbolPackageFormat>
</PropertyGroup>  
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.Bitbucket.Git" Version="1.0.0" PrivateAssets="All" />
....
```

In VS this is the error log I'm getting when trying to step into the source code.
> Looking for source using Source Link (https://api.bitbucket.org/2.0/repositories/etixxxxxxxxam/exxxxxxxxest/src/1d8f896c416670ef54e4d27250d744883aebcab0/Providers/AuthorizationServerProvider.cs)...
> Source Link errors:
> git-credential-manager.exe: Could not obtain credentials. Process failed with exit code -1.
> ERROR: The request failed with code 403 : "Forbidden".
> The file was not found with Source Link.

GIT log
   ```
18:14:36.832261 ...\Common.cs:744       trace: [Main] git-credential-manager (v1.18.4) 'get'
18:14:36.922020 ...\Git\Where.cs:348    trace: [FindGitInstallations] found 1 Git installation(s).
18:14:36.936986 ...Configuration.cs:222 trace: [LoadGitConfiguration] git All config read, 22 entries.
18:14:36.941966 ...\Common.cs:479       trace: [LoadOperationArguments] interactive = 'false'.
18:14:36.942964 ...\Common.cs:505       trace: [LoadOperationArguments] writeLog = 'True'.
18:14:36.942964 ...\Common.cs:543       trace: [LoadOperationArguments] useHttpPath = ''.
18:14:36.944959 ...\Common.cs:318       trace: [EnableTraceLogging] trace logging enabled.
18:14:36.953934 ...\Common.cs:334       trace: [EnableTraceLogging] git global config found at 'C:\Users\Gonzalo\.gitconfig'.
18:14:36.955938 ...\Common.cs:378       trace: [EnableTraceLoggingFile] trace log destination is 'C:\Users\Gonzalo'.
18:14:37.017274 ...\Common.cs:85        trace: [CreateAuthentication] detecting authority type for 'https://api.bitbucket.org/'.
18:14:37.035229 ...uthentication.cs:313 trace: [GetAuthentication] authentication for Bitbucket created
18:14:37.035229 ...\Common.cs:192       trace: [CreateAuthentication] authority for 'https://api.bitbucket.org/'  is Bitbucket.
18:14:37.035229 ...\Common.cs:765       trace: [QueryCredentials] querying 'Bitbucket' for credentials.
18:14:37.046198 ...\Common.cs:709       trace: [LogEvent] Failed to retrieve Bitbucket credentials for 'https://api.bitbucket.org/'.
18:14:37.048191 ...\Program.cs:414      trace: [Get] Logon failed, use ctrl+c to cancel basic credential prompt.
   ```

Thanks!

**Comment by gonzaloluna** [comment]
is there anybody out there?

**Comment by tmat** [comment]
@chuckries

**Comment by chuckries** [comment]
@gonzaloluna do you have 2FA enabled for your bitbucket account?

**Comment by gonzaloluna** [comment]
@chuckries I don't have 2FA enabled. I was aware of that issue tho, I've read all the tickets in the repo.

**Comment by chuckries** [comment]
@gonzaloluna I forget every detail of BitBucket off the top of my head, but I believe they allow signing in both by username and by email address. GCM didn't like one of the methods. Can you try the opposite of whatever you have been using? i.e. username instead of email or email instead of username.

Also, is this a Source Link scenario that worked for you before and is now broken? Or is this something that has never worked?

**Comment by gonzaloluna** [comment]
The source link is from a nuget I created following all the directions from the documentation.
I can try the username/email, how do I change that?

**Comment by gonzaloluna** [comment]
Ok, I changed the username format in the .gitconfig which seems to be making effect since I can see it in the git log.

[credential]
	interactive = true
	useHttpPath = true
	writelog = true
	username = gonxxxxxxxxxxxx   <--also tried email format but doesn't work either and looks wrong. 
https://email@address.com@api.bitbucket.org/ vs https://gonxxxxxxxxxxxx@api.bitbucket.org/

The bitbucket endpoint shouldn't be in the form 'https://username@bitbucket.org/project/repo.git ? That format is something I'm seeing in the logs when running regular git commands.

```14:19:06.804894 ...\Common.cs:479       trace: [LoadOperationArguments] interactive = 'false'.
14:19:06.804894 ...\Common.cs:505       trace: [LoadOperationArguments] writeLog = 'True'.
14:19:06.804894 ...\Common.cs:543       trace: [LoadOperationArguments] useHttpPath = ''.
14:19:06.804894 ...\Common.cs:657       trace: [LoadOperationArguments] username = 'gonxxxxxxxxxxxx'.
14:19:06.807879 ...\Common.cs:318       trace: [EnableTraceLogging] trace logging enabled.
14:19:06.815856 ...\Common.cs:334       trace: [EnableTraceLogging] git global config found at 'C:\Users\Gonzalo\.gitconfig'.
14:19:06.817850 ...\Common.cs:378       trace: [EnableTraceLoggingFile] trace log destination is 'C:\Users\Gonzalo'.
14:19:06.879686 ...\Common.cs:85        trace: [CreateAuthentication] detecting authority type for 'https://gonxxxxxxxxxxxx@api.bitbucket.org/'.
14:19:06.897638 ...uthentication.cs:313 trace: [GetAuthentication] authentication for Bitbucket created
14:19:06.898635 ...\Common.cs:192       trace: [CreateAuthentication] authority for 'https://gonxxxxxxxxxxxx@api.bitbucket.org/'  is Bitbucket.
14:19:06.898635 ...\Common.cs:765       trace: [QueryCredentials] querying 'Bitbucket' for credentials.
14:19:06.916587 ...\Common.cs:709       trace: [LogEvent] Failed to retrieve Bitbucket credentials for 'https://gonxxxxxxxxxxxx@api.bitbucket.org/'.
14:19:06.918584 ...\Program.cs:414      trace: [Get] Logon failed, use ctrl+c to cancel basic credential prompt.

**Comment by chuckries** [comment]
@gonzaloluna thanks for the info, I am continuing to investigate on our side.

**Comment by gonzaloluna** [comment]
> @gonzaloluna thanks for the info, I am continuing to investigate on our side.

Thanks

**Comment by chuckries** [comment]
@gonzaloluna Can you describe your experience within VS? What I would expect is this:
1. You try to obtain a source file from BitBucket via sourcelink, either by navigating to a specific stack from or hitting an exception. Somehow you stop in the debugger and Source Link is invoked.
2. Authentication fails and you see the "No Source Page"

Once you see that "No Source Page" with the Source Link error info, is there a Hyperlink that says Try Again with Authentication? Have you clicked this? Does it have the same failure?

**Comment by gonzaloluna** [comment]
There's no link in the "Source Not Found" tab. 

![image](https://user-images.githubusercontent.com/7874811/79487223-4da7ad80-7fee-11ea-815d-fef9ac899eed.png)

**Comment by chuckries** [comment]
I see. This issue was fixed in Visual Studio 2019 16.4. Is is possible to update your version of Visual Studio to the latest?

**Comment by gonzaloluna** [comment]
wow, sure I'll try it and let you know!

**Comment by gonzaloluna** [comment]
I see the bitbucket login link after updating visual studio, however the source link feature doesn't seem to be very stable either. Sometimes it almost works, sometimes it doesn't at all. I've created a new nuget which looks good but VS is not even trying to step into the breakpoint. I've tried tons of things but this is taking me too much time. I'll wait until the next releaso or so.

Thank your for your help!

**Comment by chuckries** [comment]
1. Just to be clear, once you see the BitBucket sign in UI, you are successfully able to retrieve the file from Source Link? The issue you originally opened is fixed, correct?

2. There are a few scenarios that can make it look as though Source Link is not working but it is likely never getting invoked in the first place. Here are some potential scenarios:
- Do you have symbols loaded for the assemblies in the NuGet package? If you do not have symbols loaded, Source Link will never be triggered.
- Do you have Just My Code enabled? If JMC is enabled, stepping into non-JMC code (any code that is optimized/built release configuration) will not actually stop in the non-JMC code. If the debugger doesn't stop, Source Link will not be triggered.
- Even with JMC turned off, debugging optimized code can be very tricky. For some methods, it is optimized in such a way that the debugger does not have a valid place to stop, and the step in becomes a step over. In this case Source Link will not be triggered.

I believe you are only seeing a Source Link issue if you try to step in and actually see the No Source Page. If you are doing a step in and you just stop at the next line of code (it becomes a step over), you are running into one of the scenarios listed above.

**Comment by gonzaloluna** [comment]
I found the issue, it seems that even though the nuget package was properly built with the PDB and source link information, the PDF file is not being copied under the bin\ folder in the consumer application, just the DLL.
Seems to be a bug 
https://github.com/dotnet/sdk/issues/1458

Placing the pdb file manually works.

Thanks

**Comment by chuckries** [comment]
@tmat can you close this issue? apparently I don't have permissions.
