### ISSUE TITLE
Can't get SSH with different domain to work with Bitbucket

### ISSUE THREAD

**Issue by bencyoung** [dotnet/sourcelink#599]
We have an issue where we can't get SourceLink to generate the correct urls in the PDBs as our CI system has to use a different domain for SSH connections. 

The clone is done via ssh://git@git-ssh.domain.com/project/repo.git (note the -ssh), but the files are only available via https://git.domain.com/...

Currently I have 

` <SourceLinkBitbucketGitHost Include="git-ssh.domain.com" Version="4.13" />`

but

```
    <RepositoryUrl>https://git.domain.com/scm/project/repo.git</RepositoryUrl>
    <ScmRepositoryUrl>https://git.domain.com/scm/project/repo.git</ScmRepositoryUrl>
```

but I can't find a combination that works, the urls are always:

`https://git-ssh.domain.com/projects/...`

is there any way to override SourceLink here? We only have one source...

**Comment by bencyoung** [comment]
Ah, It's ContentUrl I think I need, although there's no docs for this property!

**Comment by tmat** [comment]
Here: https://github.com/dotnet/sourcelink/tree/master/docs#custom-content-urls
