### ISSUE TITLE
Debug session exits with code -2146233082

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/sourcelink#608]
Pardon me if I am posting the question to the wrong forum as I am not sure if the issue is relevant to SourceLink or just Visual Studio in general.

My debug session exits with the following error message:
![image](https://user-images.githubusercontent.com/4291622/80425345-12886280-88a9-11ea-81bb-15afce453743.png)

When I try to step into the line in the read box:
![image](https://user-images.githubusercontent.com/4291622/80425305-03a1b000-88a9-11ea-9473-9747a8ebb879.png)

However I am able to step into the the boxed line after moving typeof out of the way:
![image](https://user-images.githubusercontent.com/4291622/80425794-fafda980-88a9-11ea-83b6-e28c459d97a5.png)

The suggestion in the error message was not helpful as that option was already enabled:
![image](https://user-images.githubusercontent.com/4291622/80425916-516ae800-88aa-11ea-8bf5-b0d7c9651e88.png)

**Comment by tmat** [comment]
This is unrelated to SourceLink. Reporting similar issues via VS Feedback would be better.

Note that the error message is asking to _disable_ the option. If the option is enabled the debugger attempts to automatically execute the code that implements properties, which might not always work well and the program being debugged might get terminated.

**Comment by WenningQiu** [comment]
Good catch, but disabling that options does not help.
