### ISSUE TITLE
SourceLink breaks SonarQube Code Coverage

### ISSUE THREAD

**Issue by iamwyza** [dotnet/sourcelink#615]
I don't know if this should go under this project or under SonarQube's analysis engine, feel free to reject it if it should go over there instead.

When using SonarQube to analyze a dotnet core project for Code Coverage, adding the SourceLink nuget package causes it to consider resulting tests to not match up to the coverage files generated by dotnet test.  I'm not sure exactly what is happening, but I'm guessing that whatever postfixing that sourcelink does, it is making the results "seem" different.  

In the short term I added a Condition to the PackageReference that I can set to false during the dotnet test step which gets around this issue.  Long term it'd be nice to not have to do this.

**Comment by tmat** [comment]
Do you have [`DeterministicSourcePaths`](https://github.com/dotnet/roslyn/blob/7b27ca3b7722c5e56910a6cfba837e6a9d352d4f/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L131-L141) switched on?

**Comment by iamwyza** [comment]
We do.  Reading the details on this, I'm guessing then your suggesting we turn that off (at the very least for the CI/Test builds) and that would resolve our issue.

**Comment by tmat** [comment]
That's likely the source of the problem. We have recently worked with Coverlet to support deterministic source paths. I'd recommend filing and issue on SonarQube so that they can add support as well. 

See https://github.com/dotnet/roslyn/issues/43476.

**Comment by iamwyza** [comment]
Thanks, I'll go ahead and close this since really this isn't the problem of SourceLink.
