### ISSUE TITLE
XAML project fails to build in CI when building with Deterministic=true

### ISSUE THREAD

**Issue by tmat** [dotnet/sourcelink#62]
Source control info targets not executed in tmp_proj projects.

```
Microsoft.Managed.Core.targets(90,5): SourceRoot items must include at least one top-level (not nested) item when DeterministicSourcePaths is true [fjslegn5.tmp_proj]
```

**Comment by ctaggart** [comment]
@tmat, @JamesNK  hit an error when `DeterministicSourcePaths` evaluated to `true`. He set `/p:ContinuousIntegrationBuild=true`, which led to that. https://github.com/JamesNK/Newtonsoft.Json/pull/1746

**Comment by tmat** [comment]
Dup of https://github.com/dotnet/sourcelink/issues/91. A workaround is described in the other issue.
