### ISSUE TITLE
Linking NuGets with souce code included

### ISSUE THREAD

**Issue by lukas-lansky** [dotnet/sourcelink#63]
This might be either uninformed, or out of scope of what you are trying to do, so feel free to close immediately.

[I noticed that `dotnet pack` has `--include-source` option.](https://stackoverflow.com/questions/50462494/how-visual-studio-discover-nugets-with-source-symbols) I then spent some time trying to find out how to use such source code inclussion for debugging... and the only thing I have found is your project. You, as far as I can see, do not allow to take the source (for, let's say, `MyOrg.MyLib 1.2.3`) from another NuGet (`MyOrg.MyLib.symbols 1.2.3`). You just ask network locations file-by-file.

Now I wonder whether generic NuGet source code provider could be done for SourceLink. It would solve problems with attempting to support every authentication scheme every repo browser has on a case-by-case basis -- it would be NuGet's issue now to handle obtaining the symbol nuget based on local package source settings. And it would have a chance to work offline thanks to local NuGet caches.

**Comment by tmat** [comment]
That option includes source into a symbol package, not to the main package. Symbol packages are not downloaded to the client, so the source code is not available there. You can upload symbol package with source to a server that exposes the sources in some way via public URL. If there was such a service you could then craft SourceLink such that it points to these URLs. Now if that source is private then you'd still need to authenticate to the service.

There is an alternative. You can include a Portable PDB in your main nuget package and embed all sources in that PDB. Your main package will be larger but the debugger will have an immediate access to all sources without accessing network. For private repos you wouldn't include the PDB in your package but rather publish it to a private symbol server. The debugger would authenticate to that symbol server when looking for the PDB.

**Comment by lukas-lansky** [comment]
Thanks for the answer! I hoped I would be able to do without running internal symbol server... and the ability to include sources into PDBs is not that bad after all. They are already part of our packages so we can get stack traces with line information. I would just need to check what that does with the memory utilization.

Alternatively, I can see that you already have a ticket for adding support for Bitbucket Server auth -- and that would help me too. Thanks again for your response.
