### ISSUE TITLE
Build Fails on Linux

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/sourcelink#64]
I get the following error:

> /home/travis/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-62909-01/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly. [/home/travis/build/Dotnet-Boxed/Framework/Source/Boxed.Mapping/Boxed.Mapping.csproj]
> /home/travis/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-62909-01/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-6311e88': The specified module or one of its dependencies could not be found. [/home/travis/build/Dotnet-Boxed/Framework/Source/Boxed.Mapping/Boxed.Mapping.csproj]

You can see the full build log [here](https://travis-ci.org/Dotnet-Boxed/Framework/jobs/383716947) and the code [here](https://github.com/Dotnet-Boxed/Framework).

**Comment by RehanSaeed** [comment]
This suggests that I need Git installed which makes sense. I updated my Travis CI build to run `apt-get install git` but I still got this error:

> /home/travis/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-62909-01/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly. [/home/travis/build/Dotnet-Boxed/Framework/Source/Boxed.Mapping/Boxed.Mapping.csproj]
/home/travis/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-62909-01/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-6311e88': The specified module or one of its dependencies could not be found. [/home/travis/build/Dotnet-Boxed/Framework/Source/Boxed.Mapping/Boxed.Mapping.csproj]

**Comment by tmat** [comment]
@RehanSaeed You shouldn't need git. I have fixed some issues around loading the dll mentioned in the error message recently. Can you try the latest build from [myget feed](https://dotnet.myget.org/feed/sourcelink/package/nuget/Microsoft.SourceLink.GitHub/1.0.0-beta-62925-02)?

**Comment by tmat** [comment]
Should be fixed now with the latest version on MyGet.
