### ISSUE TITLE
Add support for Gitea servers

### ISSUE THREAD

**Issue by SuNNjek** [dotnet/sourcelink#647]
There currently is no support for [Gitea](https://github.com/go-gitea/gitea/) servers according to the README. It would be awesome if support for those could be added.

**Comment by Mik4sa** [comment]
I was also looking for this. Actually it's straight forward.
I will make a pull request tomorrow.

**Comment by Mik4sa** [comment]
Until there is an official nuget package you can use mine: https://www.nuget.org/packages/LinusTuring.SourceLink.Gitea/1.0.1
It's based on this: https://github.com/LinusTuring/sourcelink/tree/release/1.0.0

**Comment by tmat** [comment]
Implemented by https://github.com/dotnet/sourcelink/pull/674
