### ISSUE TITLE
VSTS SSH Git Remote does not work?

### ISSUE THREAD

**Issue by Tadimsky** [dotnet/sourcelink#65]
I'm getting the following error:
```
C:\Users\joschm\.nuget\packages\microsoft.sourcelink.common\1.0.0-beta-62909-01\build\Microsoft.SourceLink.Common.targets(59,5): error : SourceRoot.SourceLinkUrl is empty: 'C:\Users\joschm\Intentional\services-utilities\' [C:\Users\joschm\Intentional\services-utilities\Authentication\Authentication.csproj]
```

I'm guessing it's because I use ssh as my Git remote.

```
λ git remote -v
origin  ssh://intentional@vs-ssh.visualstudio.com:22/intent/_ssh/services-utilities (fetch)
origin  ssh://intentional@vs-ssh.visualstudio.com:22/intent/_ssh/services-utilities (push)
```

Is this not supported yet?

**Comment by tmat** [comment]
It should be...

**Comment by tmat** [comment]
Oh, I think the problem is that the format of the URL is different than what is expected (`intent/_ssh/services-utilities`).

**Comment by tmat** [comment]
Will fix.

**Comment by tmat** [comment]
@rlvandaveer How do you set up this alias? Does this alias apply also to the HTTP URL that you can use for clone?

**Comment by rlvandaveer** [comment]
You set up git host alias in your .ssh/config file. This is necessary because if you have multiple VSTS accounts with different credentials like me. This alias only applies to SSH based connections. It does not affect HTTP.

```
Host company-vsts
	Hostname vs-ssh.visualstudio.com
	User company
	IdentityFile ~/.ssh/id_company_vsts
	AddKeysToAgent yes
	UpdateHostKeys yes

Host company2-vsts
	Hostname vs-ssh.visualstudio.com
	User company2
	IdentityFile ~/.ssh/id_company2_vsts
	AddKeysToAgent yes
	UpdateHostKeys yes
```
