### ISSUE TITLE
SourceLink doesn't support incremental building

### ISSUE THREAD

**Issue by llongley** [dotnet/sourcelink#652]
When I add SourceLink to a project, the Link task always executes even if nothing has changed, because the sourcelink.json file is always written to, so the Link task always thinks that something has changed.  I've worked around this locally by replacing this:

```
    <Microsoft.SourceLink.Common.GenerateSourceLinkFile SourceRoots="@(SourceRoot)" OutputFile="$(SourceLink)" />

    <ItemGroup>
      <FileWrites Include="$(SourceLink)" />
    </ItemGroup>
```

with this:

```
    <PropertyGroup>
      <_SourceLinkTestFile>$(TEMP)\$(MSBuildProjectName).sourcelink.json</_SourceLinkTestFile>
    </PropertyGroup>
    <Microsoft.SourceLink.Common.GenerateSourceLinkFile SourceRoots="@(SourceRoot)" OutputFile="$(_SourceLinkTestFile)" />
    <Exec Command="fc $(_SourceLinkTestFile) $(SourceLink) >nul" IgnoreExitCode="true">
      <Output TaskParameter="ExitCode" PropertyName="FileCompareResult" />
    </Exec>
    <Copy SourceFiles="$(_SourceLinkTestFile)" DestinationFiles="$(SourceLink)" Condition="'$(FileCompareResult)' != '0'" />
    <ItemGroup>
      <FileWrites Include="$(_SourceLinkTestFile)" />
      <FileWrites Include="$(SourceLink)" />
    </ItemGroup>
```

This writes to a temp file first and then uses the FileCompare tool to only overwrite the sourcelink.json file if its contents have changed.

**Comment by tmat** [comment]
I believe the implementation is correct. The task `Microsoft.SourceLink.Common.GenerateSourceLinkFile` is executed but it does not write to the file if the file content is unchanged. See https://github.com/dotnet/sourcelink/blob/f61f34798be0641e4bbfa3a50174c8ee1f4f7ee5/src/SourceLink.Common/GenerateSourceLinkFile.cs#L112
