### ISSUE TITLE
Specify what happens with multiple libraries with the same base mapping

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/sourcelink#656]
I'm working on adding SourceLink to a few native projects of mine, and I've run into something that might be a problem. All of our builds build on Azure Pipelines, which by default build in a path like `D:\a\1\s`. This means all of our libraries would have the same root mapping. What happens if multiple libraries with the same root mapping are loaded into a process. The docs are not really clear on this. Does the debugger (both native, managed, and windbg) keep a separate mapping for each pdb, or does it join them all together into 1 big mapping. I'd assume the former, but I just want to make sure, and I think that should be documented.

**Comment by tmat** [comment]
I believe this is covered here: https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/source-link.md#source-link-file-specification

>  A debugger would retrieve the original file path of *the current location from the PDB*, look this path up in the Source Link map, and use the resulting URL to download the source file.
