### ISSUE TITLE
Provide support for Azure Devops Artifacts (GIT)

### ISSUE THREAD

**Issue by mdesalvo** [dotnet/sourcelink#658]
Within a Git-based DevOps environment there's actually no way to have automatic publishing and loading of sourcelink symbols for our project artifacts.

**Comment by tmat** [comment]
What do you mean by "sourcelink symbols"? If you have questions about Azure DevOps task for publishing PDBs to Symbol Servers then that's outside of the scope of this repository.

**Comment by mdesalvo** [comment]
Hi Tomáš,
I mean a Nuget package like "Microsoft.SourceLink.AzureDevOps.Artifacts" which would make it possible to fetch symbols of artifacts deployed as *.snupkg in a Azure DevOps Artifacts feed. This is a missing provider at the moment.

**Comment by tmat** [comment]
Downloading symbols from symbol servers is not a functionality that Source Link provides. I don't think Azure DevOps currently supports publishing .snupkg but I might be wrong. This would be an ask for Azure DevOps, not Source Link. You can also check out https://github.com/dotnet/symstore project that provides APIs for working with symbol servers in general.
