### ISSUE TITLE
PublishRepositoryUrl vs RepositoryUrl settings?

### ISSUE THREAD

**Issue by PureKrome** [dotnet/sourcelink#659]
Hi 👋🏻 

I'm trying to determine the reason why we have both of these settings. The [Source Link docs (for `PublishRepositoryUrl`)](https://github.com/dotnet/sourcelink/blob/master/docs/README.md#publishrepositoryurl) say:

(emphasis, mine)

> PublishRepositoryUrl _needs to be set by the project_ in order to publish the URL into RepositoryUrl property, which is used e.g. in the nuspec file generated for NuGet package produced by the project.

So this means that we need to provide a `true` setting, if we want the `RepositoryUrl` to get set. Hmm, okay ...

but I can just MANUALLY set the `RepositoryUrl` in the `.csproj` anyways! And these two settings are right near each other, in the .csproj (usually).

AND .. if i manually set the value for `RepositoryUrl` ... then this `PublishRepositoryUrl` doesn't do anything.

So what's the use of this setting, then?

**Comment by tmat** [comment]
If you manually set `RepositoryUrl` then you don't need this setting. It's only useful when you don't want to set the value and want it to be automatically determined by Source Link.

**Comment by PureKrome** [comment]
Thanks @tmat for the clarification!
