### ISSUE TITLE
GitLab raw URLs are broken with recent GitLab installs

### ISSUE THREAD

**Issue by rgl** [dotnet/sourcelink#670]
The current GitLab generates raw URLs alike:

```
https://gitlab.example.com/raw/example/example-dotnet-source-link/538b7a2b0d086146a6534bfe6f98a379191ea529/ExampleApplication/Program.cs
```

But in GitLab 13.5 (at least; didn't test with earlier version) they are broken. GitLab now needs this:

```
https://gitlab.example.com/example/example-dotnet-source-link/-/raw/538b7a2b0d086146a6534bfe6f98a379191ea529/ExampleApplication/Program.cs
```

I'm not really sure how to deal with older/newer URLs... would it be enough to submit a PR for changing the URL by changing the code at https://github.com/dotnet/sourcelink/blob/f61f34798be0641e4bbfa3a50174c8ee1f4f7ee5/src/SourceLink.GitLab/GetSourceLinkUrl.cs#L20?

**Comment by tmat** [comment]
If the URL changed in a specific version forward we will need to do two things:
1) default to the new format in the new Source Link package
2) allow users to switch to the old behavior by specifying version of GitLab their repository is hosted on

The implementation for BitBucket already does this, so we would want to use a similar approach.

**Comment by rgl** [comment]
@tmat, finally got a chance to take a jab at this. Can you look at the TODOs in #713 and discuss how to address them?
