### ISSUE TITLE
Display error or warning if GitHub remote is misconfigured

### ISSUE THREAD

**Issue by ap0llo** [dotnet/sourcelink#68]
I tried out source link with code hosted on GitHub, but the url for the remote was misconfigured like this (note the `www` and the double slash in the url):
```
https://www.github.com//USERNAME/REPOSITORY
```

This made SourceLink embed an invalid url into the pdb:
`https://USERNAME//REPOSITORY/COMMITHASH/*`

Of course the error was the misconfigured remote url, but it would be great if SourceLink could produce an error or a warning is such cases.

**Comment by tmat** [comment]
I'm not sure how would we detect misconfigured remote URL without sending HTTP GET request to it - the above URL is a valid URL. It just happens to not be the right URL. Source Link on purpose does not access network during build.
