### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/sourcelink#683]
> Source Link is a language- and source-control agnostic system for providing first-class source debugging experiences for binaries. The goal of the project is to enable anyone building NuGet libraries to provide source debugging for their users with almost no effort. Microsoft libraries, such as .NET Core and Roslyn have enabled Source Link. Source Link is supported by Microsoft.

The link for "NuGet libraries to provide source debugging" is broken.

**Comment by tmat** [comment]
Fixes by https://github.com/dotnet/sourcelink/pull/592.
