### ISSUE TITLE
New version for NuGet dependencies

### ISSUE THREAD

**Issue by Mik4sa** [dotnet/sourcelink#687]
Can you please publish a new version for the two NuGet dependencies? Otherwise we can't use/test the official gitea package.

Currently the gitea package has dependencies for _Microsoft.Build.Tasks.Git (>= 1.1.0-beta-21055-01)_ and _Microsoft.SourceLink.Common (>= 1.1.0-beta-21055-01)_

But the last version for both is _1.1.0-beta-20204-02_

**Comment by tmat** [comment]
Sure, forgot about these.

**Comment by tmat** [comment]
Done.
