### ISSUE TITLE
How to build with github source link support from private project with different origin

### ISSUE THREAD

**Issue by davidroth** [dotnet/sourcelink#689]
Hey,

I have open sourced a project which original source is still maintained in a private gitlab project.
Currently the development takes place at gitlab, and the source is only mirrored to github.
CI pipeline is also on gitlab.

Now I want to enable source link support in the published nuget. Because the source is publicly available on github, I want to build source link for github, but in the gitlab pipeline. This doesnt seem to work because when building on gitlab, the git origin is set to gitlab.

I tried to manually configure the property and set it to github:

```<RepositoryUrl>https://github.com/my_project</RepositoryUrl>```

But as soon as i set this, I get the following warning when building:

`Microsoft.SourceLink.Common.targets(52,5): warning : Source control information is not available - the generated source link is empty.`

I looks lik this url must match the url of the "origin" in the repository config. However, I cannot change this when building on gitlab.

Is there a way to build a package with GitHub SourceLink support, when building on Gitlab where the gits origin is obviously set to gitlab because thats where it gets fetched in the pipeline?

**Comment by tmat** [comment]
Yes, there are a couple of ways to do this. Let's start with [`insteadOf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf). Can you configure your GitLab CI to set up `insteadOf` URL mapping in git config of the repo?

**Comment by davidroth** [comment]
@tmat 

Thanks for your answer!
I tried `insteadOf` locally and it works in theory.
However, there is no official way to set `insteadOf` in the gitlab pipeline. I'd have the manually patch ".git/config" (in the build container, I dont have git installed, so cannot use the git config command) and then revert it after the build to avoid issues in subsequent builds. The url is also dynamic, because it contains a CI_BUILD_TOKEN for authentication etc. 
Altogether this feels a bit hacky :-/
I'd love to hear the other ways first :-) Can you share them please? Thanks!
