### ISSUE TITLE
How to troubleshoot?   Not working for NuGet.Client

### ISSUE THREAD

**Issue by zivkan** [dotnet/sourcelink#696]
I work on the NuGet.Client team: https://github.com/NuGet/NuGet.Client

Using pdb2xml, I don't see "https" or "github" anywhere in the generated xml file, but looking at a binlong, I see that projectname.sourcelink.json was created, and it's passed to csc via the `/sourcelink:` parameter.

How can I troubleshoot this?

Steps to reproduce:

```text
git clone https://github.com/NuGet/NuGet.Client
cd NuGet.Client
dotnet build src\NuGet.Core\NuGet.Versioning\NuGet.Versioning.csproj -bl
pdb2xml artifacts\NuGet.Versioning\16.0\bin\Debug\netstandard2.0\NuGet.Versioning.dll
type artifacts\NuGet.Versioning\16.0\obj\Debug\netstandard2.0\NuGet.Versioning.sourcelink.json
```

**Comment by tmat** [comment]
pdb2xml does not print source server info (Source Link or legacy srcsvr) by default. Need to pass `/srcsvr`.

Once I do that this is what I see (cloned with `--recurse-submodules`):
```xml
<sourceLink><![CDATA[{"documents":{"D:\\NuGet.Client\\*":"https://raw.githubusercontent.com/NuGet/NuGet.Client/c21ea53349800e7da0749a9591b623a33d976ab4/*","D:\\NuGet.Client\\submodules\\Common\\*":"https://raw.githubusercontent.com/aspnet/Common/e6fac8061686c18531e2621ccef97dd5e0687a65/*","D:\\NuGet.Client\\submodules\\FileSystem\\*":"https://raw.githubusercontent.com/NuGet/FileSystem/f1f3f0820a573b96b2faaf5b7e6be9a036e4c7aa/*","D:\\NuGet.Client\\submodules\\NuGet.Build.Localization\\*":"https://raw.githubusercontent.com/NuGet/NuGet.Build.Localization/f15db7b7c6f5affbea268632ef8333d2687c8031/*"}}]]></sourceLink>
```

**Comment by tmat** [comment]
You should be able to validate your package using [NuGet Package Explorer](https://www.microsoft.com/en-us/p/nuget-package-explorer/9wzdncrdmdm3?activetab=pivot:overviewtab).

We are building a command line tool that does full validation as well, but it's not ready yet.

**Comment by zivkan** [comment]
Thank you, this helps track down our problem is symbols publishing.
