### ISSUE TITLE
TFS git repository configuration

### ISSUE THREAD

**Issue by biiiipy** [dotnet/sourcelink#71]
How do we configure this for git repos that live in TFS? According to this issue -  https://github.com/dotnet/sourcelink/issues/39 - I added ``Microsoft.SourceLink.Vsts.Git`` and set ``<SourceLinkVstsGitDomain>mydomain:8080</SourceLinkVstsGitDomain>``, but I get an error:

``......nuget\packages\microsoft.sourcelink.common\1.0.0-beta-62925-02\build\Microsoft.SourceLink.Common.targets(60,5): error : SourceRoot.SourceLinkUrl is empty: 'C:\git\MyProjectName\'``

Our git repo lives under ``http://mydomain:8080/tfs/MyCollection/_git/MyProjectName``

Also, how do we specify https? It's weird that http is the default (according to code)

**Comment by tmat** [comment]
Could you please build with `msbuild /bl:log.binlog` and share the `log.binlog` file?

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/sourcelink/pull/130
