### ISSUE TITLE
`dotnet sourcelink test` equivalent?

### ISSUE THREAD

**Issue by TheAngryByrd** [dotnet/sourcelink#717]
Hey there!  So I've used the older [sourcelink CLI](https://github.com/ctaggart/sourcelink) tool.  One particular part of it has been `dotnet sourcelink test` to ensure SourceLinking has worked.  However, now the repository has been archived.  Is there any equivalent way to check at build/package time that Sourcelinking was properly configured on a nuget package?

Thanks!

**Comment by tmat** [comment]
It's WIP: https://github.com/dotnet/sourcelink/pull/678

**Comment by TheAngryByrd** [comment]
Thanks!
