### ISSUE TITLE
The value of SourceRoot.RepositoryUrl ... is invalid

### ISSUE THREAD

**Issue by mc0re** [dotnet/sourcelink#718]
I'm using on-prem _Azure DevOps_.
Repo address shown by `git remote show origin` (redacted): 

> ssh://azuredevops.company-name.net:22/Main/Project%20Name/_git/repo-name

`csproj` file includes:

```xml
    <PackageReference Include="Microsoft.SourceLink.AzureDevOpsServer.Git" Version="1.0.0" PrivateAssets="All"/>
    <SourceLinkAzureDevOpsServerGitHost Include="azuredevops.company-name.net"
                                        VirtualDirectory="Main/Project%20Name"/>
```

Running `dotnet build` on that `csproj` yields the following error (shown twice):

> The value of SourceRoot.RepositoryUrl with identity 'C:\Projects\repo-name\' is invalid: 'ssh://azuredevops.company-name.net:22/Main/Project Name/_git/repo-name' [C:\Projects\....csproj]

Replacing SSH _origin_ with HTTPS doesn't change a thing, except for `https` is shown in the error message.

What is the cause? What am I missing?

**Comment by tmat** [comment]
The expected SSH URL is of this form: `ssh://server:22/tfs/DefaultCollection/project/_ssh/repo`.

Notice there is `_ssh`, not `_git` in the path. I'm surprised the git repo works with the above URL. What version of Azure DevOps are you on?

**Comment by mc0re** [comment]
Server version is `Dev18.M170.8`.

**Comment by mc0re** [comment]
Apparently, the solution is to remove the `VirtualDirectory` attribute.
