### ISSUE TITLE
How to read Source Link JSON data from PDBs

### ISSUE THREAD

**Issue by gregwb** [dotnet/sourcelink#723]
Is there a supported way for retrieving Source Link URLs from PDB files?

For writing tools that use Source Link data, there's a useful `SourceLinkMap` for parsing the JSON, but how can the JSON be read from a PDB in the first place?

I note that the [symreader-converter](https://github.com/dotnet/symreader-converter) project has code for reading Source Link data, but from my experimentation, I believe the APIs used there do not support PDBs for native C++ projects. I would like in particular to be able to read Source Link data embedded in native PDBs by the [C++ linker](https://docs.microsoft.com/en-us/cpp/build/reference/sourcelink).

From this [comment](https://github.com/dotnet/sourcelink/pull/605#issuecomment-619402118) it appears at a pinch I may be able to use [pdbstr.exe](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/the-pdbstr-tool) to extract streams `sourcelink$1`, `sourcelink$2`, ... etc. But I was hoping for a more convenient API than a command-line tool.

**Comment by tmat** [comment]
The debugger reads the data using `IDiaDataSource3` from [DIA APIs](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2019) which are unfortunately not public currently.

We'll use https://developercommunity.visualstudio.com/t/Is-there-an-API-for-reading-Source-Link-/1468642 to track the feature request to make these APIs public.
