### ISSUE TITLE
Update ArPow build to build net6.0 TFM

### ISSUE THREAD

**Issue by dseefeld** [dotnet/sourcelink#724]
When building source-build, all sources are built with the current TFM.  Because of this, patches were introduced to build sourcelink with the net6.0 TFM.  The patches are:
- https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/patches/sourcelink/0001-Update-TFMs-to-net6.0.patch
- https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/patches/sourcelink/0002-Update-Task-paths-to-include-net6.0.patch

These patches should be included in the sourcelink source so they are built in the SourceBuild leg.

**Comment by tmat** [comment]
A couple of questions.

Why not just send PRs instead of patches? It'd be easier to apply/comment on.

Why is this needed?
`<UsingToolNetFrameworkReferenceAssemblies Condition=" '$(DotNetBuildFromSource)' == 'true' ">false</UsingToolNetFrameworkReferenceAssemblies>`

**Comment by tmat** [comment]
It seems wrong to switch TFM conditionally for source build. Source build should build the same product as regular build.

**Comment by dseefeld** [comment]
> It seems wrong to switch TFM conditionally for source build. Source build should build the same product as regular build.

Ideally, we wouldn't have to condition this, but pragmatically, all repos have not been updated to build other TFMs, so we're continuing to build the current TFM only.
