### ISSUE TITLE
Suspected bug - fails to pull from Github if file is already locally present at original disk location.

### ISSUE THREAD

**Issue by Korporal** [dotnet/sourcelink#747]
I'm seeing a suspected bug.

If I author a new library package and uses sourcelink, then publish the package. The I create an app locally on the same machine where the package's original source is situated and then add a ref to the published package and debug my app, the debugger sees that local source file not the specific one that it should have pulled from GitHub.

So if a package author is debugging apps that use their package, on the same machine that they wrote their package on then at debug time it always uses the current source file from the project's folder and not the one that it should use, which must be pulled from Github.

If I temporarily delete the source from my local machine and debug it does pull the (correct) source from Github.

FYI, here are the project settings I have for this test:
```xml
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <DebugType>embedded</DebugType>
    <Version>8.0.0</Version>
  </PropertyGroup>
```

This might be similar to this issue too:

https://github.com/dotnet/sourcelink/issues/603

**Comment by Korporal** [comment]
FYI, here are the project settings I have for this test:
```xml
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <DebugType>embedded</DebugType>
    <Version>8.0.0</Version>
  </PropertyGroup>
```

**Comment by Korporal** [comment]
This might be similar to this issue too:

https://github.com/dotnet/sourcelink/issues/603

**Comment by Korporal** [comment]
OK you can close this (I'll leave it here just as a record).

This is all my fault, a few days ago I temporarily unset this debug option:

![image](https://user-images.githubusercontent.com/12262952/133939213-bf30e6ea-7a68-4ae8-a00b-fcad32746180.png)

this was for some unrelated testing I was doingm re-checking that fixes my issue!

**Comment by Korporal** [comment]
I'll close this, there's no point in burdening anyone, but having it recorded may help someone else who did what I did!

**Comment by KalleOlaviNiemitalo** [comment]
IIRC, `<Deterministic>true</Deterministic>` makes the build system pass `-pathmap` to the compiler so that it does not save the original paths to the debug info; then the debugger should ignore your source file in your worktree and instead download the correct version.
