### ISSUE TITLE
Sourcelink embeds url to my fork rather than the main repo

### ISSUE THREAD

**Issue by Korporal** [dotnet/sourcelink#749]
Is there a way to have sourcelink embed the URL to the main repo rather than the fork of the developer who does the build?

**Comment by KalleOlaviNiemitalo** [comment]
I'd try running `git remote add` to set the URL of the main repo and then setting the MSBuild property [GitRepositoryRemoteName](https://github.com/dotnet/sourcelink/blob/31c76aec0522034f2a9b79a2b306222dc17a3e93/src/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.targets#L26).

**Comment by Korporal** [comment]
@KalleOlaviNiemitalo - I work in SmartGit, we have two remotes defined, our fork is always named "fork" and the main repo (that we forked from) is always named "principal" these are conventions we always follow for our corporate private repos.

From your answer we can just embed "principal" somewhere/somehow into the project file, is that right?

**Comment by KalleOlaviNiemitalo** [comment]
Directory.Build.props seems the obvious place, if you want to store this info in a version-controlled file. I would hesitate to do that though, if the repo can be cloned by someone who does not use those names for remotes.

**Comment by Korporal** [comment]
@KalleOlaviNiemitalo - Thanks.

We do not (yet) do any kind of automatic builds, all builds are done by a developer sitting at Visual Studio (this is something we will eventually change). So there's no Directory.Build.props file as such.

Is there something we could embed within the project files themselves? at least for the short term?

**Comment by KalleOlaviNiemitalo** [comment]
I suggested Directory.Build.props because you could easily make it apply to all projects in the repository. I don't see why you couldn't create such a file and keep building in the Visual Studio IDE.

**Comment by Korporal** [comment]
> I suggested Directory.Build.props because you could easily make it apply to all projects in the repository. I don't see why you couldn't create such a file and keep building in the Visual Studio IDE.

OK, sorry I have simply never used Directory.Build.props, I assumed it was somehow associated with tools that build within a repo automatically.

Thanks

**Comment by KalleOlaviNiemitalo** [comment]
PackageReference in Directory.Build.props works OK for restoring and building, but I'm not sure how well the "Manage NuGet Packages" feature of Visual Studio supports it.

**Comment by Korporal** [comment]
@KalleOlaviNiemitalo - Hi,

I created a minimal `Directory.Build.props` file that does include the sourcelink stuff for anything we build now:

```xml
<Project>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
  </ItemGroup>
 </Project>
```

But I'm not clear in what to actually add next in order to leverage your suggestion for setting the `RemoteName`, this is no doubt due to me having zero experience with these build related files!

Any help appreciated.
