### ISSUE TITLE
1.1.0 seems to depend on .NET 6

### ISSUE THREAD

**Issue by adamralph** [dotnet/sourcelink#765]
See https://github.com/adamralph/minver/runs/4149908950?check_suite_focus=true

If this is the case, it seems like a breaking change, so shouldn't it be 2.0.0?

**Comment by tmat** [comment]
I feel like we should reserve the major version bump to a change in Source Link protocol (the info written to the PDB). 1.1.0 does not make any changes in the protocol.

**Comment by adamralph** [comment]
But 1.1.0 does break most projects which are currently using 1.0.0.

**Comment by jimmym715** [comment]
From [semver.org](https://semver.org/#spec-item-8):

8.  Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY also include minor and patch level changes. Patch and minor versions MUST be reset to 0 when major version is incremented.

**Comment by tmat** [comment]
Will publish 1.1.1 that targets netcoreapp3.1.
