### ISSUE TITLE
Publish Releasenotes/Changelog

### ISSUE THREAD

**Issue by litetex** [dotnet/sourcelink#766]
At first, thank you for the great work!
Now to the issue:

It would be great if users know what changed in the recent version (by looking at the repo).

Currently I can't find any releasenotes, changelog, etc. for 1.1.0 and I have to read through all commits/files ([_just_ >300 changed files](https://github.com/dotnet/sourcelink/compare/1.0.0...1.1.0)) to know what was changed.

Also would likely prevent issues like #765 rising up in the first place.

**Comment by tmat** [comment]
Done: https://github.com/dotnet/sourcelink/releases/tag/1.1.1
