### ISSUE TITLE
Build Pipeline Error MSB4062: Microsoft.Build.Tasks.Git.LocateRepository

### ISSUE THREAD

**Issue by MooVC** [dotnet/sourcelink#768]
Starting November 9th, 2021, all MooVC pipelines on Azure DevOps began to fail with the following error:

`##[error]C:\Users\VssAdministrator\.nuget\packages\microsoft.build.tasks.git\1.1.0\build\Microsoft.Build.Tasks.Git.targets(25,5): Error MSB4062: The "Microsoft.Build.Tasks.Git.LocateRepository" task could not be loaded from the assembly C:\Users\VssAdministrator\.nuget\packages\microsoft.build.tasks.git\1.1.0\build\..\tools\net6.0\Microsoft.Build.Tasks.Git.dll. Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

Changing the project file from:

`<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.*" PrivateAssets="All" />`

To:

`<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />`

Addresses the issue, indicating that the change in v1.1.0 was an unintentional breaking change.

The build history is available here: https://dev.azure.com/vmartinspaul/MooVC/_build?definitionId=2

Sample Failure:

https://dev.azure.com/vmartinspaul/MooVC/_build/results?buildId=2993

Success Following Switch to 1.0.0:

https://dev.azure.com/vmartinspaul/MooVC/_build/results?buildId=2994

**Comment by tmat** [comment]
Fixed, version 1.1.1 published.
