### ISSUE TITLE
What does Visual Studio do when you select "Don't Ask Again"?

### ISSUE THREAD

**Issue by sthames42** [dotnet/sourcelink#803]
When Visual Studio is about to download using a Source Link URL from a remote repo, a dialog pops up with three options.
Option 2 (Don't Ask Again) appears only to display if the repo is secured by TLS:

> Download Source and Continue Debugging
> Download Source and Continue Debugging (Don't Ask Again)
> Disable Source Link and Continue Debugging

I selected option 2 and now never see this dialog again. I'm trying to get it to show so I can demo it for my staff.

Does anyone know what Visual Studio does to prevent this dialog from opening and how I can get it to open, again?

This is VS 2019 Version 16.11.10.

**Comment by tmat** [comment]
@chuckries

**Comment by chuckries** [comment]
The option is controlled by a registry key, you can get the dialog to come back using the following steps:

1. Close all VS instances.
2. Open a Developer Command Prompt for Visual Studio 2019
3. `vsregedit set local HKCU Debugger DisableSourceLinkPrompt dword 0`

The dialog should be shown again the next time Source Link is invoked. 

**NOTE**: The dialog is not shown if the Source Link file is in the Source Link cache and does not need to be downloaded. The Source Link cache is located at `%LOCALAPPDATA%\SourceServer\`. Files may need to be removed from the cache before the dialog will be shown again.

**Comment by sthames42** [comment]
Awesome! Thank you. Registry, eh? Wouldn't have thought that. Can't find much in the way of vsregedit docs.
Thanks, again.
