### ISSUE TITLE
Target GitHub repository when building in Azure DevOps

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/sourcelink#820]
Our official builds are created by a private Azure DevOps CI server, but we want SourceLink to point to our public GitHub repository (https://github.com/dotnet/orleans). It is not clear to me how we can configure that: I assume we should pull in the Microsoft.SourceLink.GitHub package, but I'm not sure what properties to set to make it work.

I believe these are the relevant files:
* https://github.com/dotnet/orleans/blob/main/Directory.Build.props
* https://github.com/dotnet/orleans/blob/main/src/Directory.Build.props
* https://github.com/dotnet/orleans/blob/main/src/Directory.Build.targets << currently, we're pulling in the AzDO SourceLink package as well. I've tried removing that, to no avail.

**Comment by tmat** [comment]
See
https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L7-L10
and
https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L43-L82

The former adds both GitHub and AzDO Source Link packages and the latter sets up mapping between them.

Alternatively, your AzDO official build could set [`insteadOf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf) git config option to map URI prefixes.

**Comment by ReubenBond** [comment]
Thank you, @tmat! I have applied the magic incantations to dotnet/orleans here: https://github.com/dotnet/orleans/pull/7673
My tests in CI show that it is working, so I'll close this.
