### ISSUE TITLE
SourceLink doesn't work well with WPF projects

### ISSUE THREAD

**Issue by tmat** [dotnet/sourcelink#91]
Error

```
Microsoft.Managed.Core.targets(90,5): SourceRoot items must include at least one top-level (not nested) item when DeterministicSourcePaths is true [C:\Temp\WpfApp1\WpfApp1\WpfApp1_3qoc4wf0_wpftmp.csproj]
```

is reported when building with `/p:ContinuousIntegrationBuild=true`.

Due to https://github.com/NuGet/Home/issues/5894 - WPF projects do not import .props and .targets files from NuGet packages.

**Comment by tmat** [comment]
The workaround is to add 

```xml
```

**Comment by JamesNK** [comment]
I get this in `Newtonsoft.Json.Tests` and `Newtonsoft.Json.TestConsole` when I build. I'm guessing because `IsPackable` is false?

**Comment by JamesNK** [comment]
Or is the issue that I am building an entire solution and source link doesn't like multiple `csproj`s?

I've fixed the error by adding the code above to the two test projects - https://github.com/JamesNK/Newtonsoft.Json/pull/1746/files#diff-9d91529ee3797584a27061bbad1d49ceR16

**Comment by tmat** [comment]
The issue in Newtonsoft.Json is related but different than the WPF issue.

When `DeterministicSourcePaths` is enabled the compiler needs to know the set of directories that all source code resides under. This set is specified by `SourceRoot` items.
In projects that reference SourceLink package `SourceRoot` items are populated by SourceLink since it knows where the repository root is.

In projects that do not reference Sourcelink package this `SourceRoot` is undefined and hence the compiler doesn’t know how to normalize the paths and reports the error.

The recommendation is to include the SourceLink package reference to all projects in the repo (even to test projects). This can be easily accomplished via adding `Directory.Build.props` file in the root of the repository that includes the SoruceLink package:

```xml
<Project>
  <PackageReference Include="Microsoft.SourceLink.GitHub" Version="..." PrivateAssets="all"/>
</Project>
```

**Comment by xied75** [comment]
In my case I have a src project with .NET Framework and a test project, building and packaging in a Jenkins. So that I need to turn on __DeterministicSourcePaths__ for the msbuild.exe. (Turn on __ContinuousIntegrationBuild__ has no effects at all.)

Then the work around suggested above won't work anymore, as the Property value supplied at command line to msbuild.exe overrides csproj settings. In order to "remove" the test project from sourcelink process, I need to add this to the test csproj file:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" TreatAsLocalProperty="DeterministicSourcePaths" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
...
  <DeterministicSourcePaths>false</DeterministicSourcePaths>
  </PropertyGroup>
```

**Comment by tmat** [comment]
> Turn on ContinuousIntegrationBuild has no effects at all.

Does your project set `Deterministic` property to true? 

> in order to "remove" the test project from sourcelink process

Why do you need to remove it?

**Comment by tmat** [comment]
Since you do not import Microsoft.Net.Sdk and do not set Deterministic then ContinuousIntegrationBuild has no effect since only affects deterministic builds.

> the compile would error out.

What error does it report?

**Comment by xied75** [comment]
```
(InitializeSourceRootMappedPaths target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\Roslyn\Microsoft.Managed.Core.targets(90,5): error : SourceRoot items must include at least one top-level (
not nested) item when DeterministicSourcePaths is true [C:\github\xxx\src\Shared.Utilities\tests\Shared.Utilities.Test.csproj]

    0 Warning(s)
    1 Error(s)
```

**Comment by tmat** [comment]
Right, so that's because you don't have SourceLink and you switch DeterministicSourcePaths to true. I guess I do not understand why you don't want SourceLink in your testing project.

**Comment by xied75** [comment]
@tmat The reason to use SourceLink is because I'm nuget packaging my library code into nupkg, but I'm not packaging my tests, at least in my case, test project was run to verify the library project then the lib nupkg is produced on Jenkins.

**Comment by Dunge** [comment]
The workaround above by @shuebner stopped working in VS 17.8.0 Preview 4.0:

```
Directory.Build.props(28,92): error MSB4100: Expected "$(DeterministicSourcePaths)" to evaluate to a boolean instead of "", in condition "'$(UseWPF)' == 'true' And $(DeterministicSourcePaths)".
```

**Comment by tmat** [comment]
@Dunge looks good to me. Does the issue (without workaround) reproduce when using .NET 8 SDK?

**Comment by Dunge** [comment]
@tmat you are right, I do not remember the error that forced me to add this workaround a few years ago, but it doesn't seem necessary anymore.
