### ISSUE TITLE
Update to the latest TFM: net8.0

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/sourcelink#938]
When source-building the product, only the latest versions of packages and their dependencies are used. With this in mind, it would be great for source-link to also target the latest TFM (net8.0) and not net7.0 as it does now

This would also allow the usage of latest runtime package dependencies, such as `System.Text.JSON`, which would otherwise require an undesirable warning suppression due to TFM miss-match

**Comment by MichaelSimons** [comment]
When doing this work, it is preferred that a new [`NetCurrent` Arcade property](https://github.com/dotnet/arcade/pull/12161) be utilized as it eliminates this type of maintenance work for every release.

**Comment by MichaelSimons** [comment]
Looks like this can be closed now as fixed with #936.
