### ISSUE TITLE
Not download source code from VSTS Git repo

### ISSUE THREAD

**Issue by sla1k** [dotnet/sourcelink#94]
Can't get source code of my nuget package from vsts feed when debugging my application.

Use this configuration of sourcelink for Vsts.Git implementation:
```
 <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Doctis.Common</AssemblyName>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources
  
  <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>
```

In pdb file from package I see some information about my repo:
```
{
    "documents": {
        "D:\\a\\1\\s\\*": "https://#####.visualstudio.com/Doctis/_apis/git/repositories/Doctis.Common/items?api-version=1.0&versionType=commit&version=ae3398cc9eef7adeb7d2b397c151a6d861175b3c&path=/*"
    }
}
```

When start debug I see in modules my package with symbols from package, but I can't step into my source code from nuget package.

**Comment by sla1k** [comment]
And get this answer from vsts, when try to go to link from pdb.

```
{
  "$id": "1",
  "innerException": null,
  "message": "TF401174: The item '*' could not be found in the repository 'Doctis.Common' at the version specified by '<Commit: ae3398cc9eef7adeb7d2b397c151a6d861175b3c >' (resolved to commit 'ae3398cc9eef7adeb7d2b397c151a6d861175b3c')",
  "typeName": "Microsoft.TeamFoundation.Git.Server.GitItemNotFoundException, Microsoft.TeamFoundation.Git.Server, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
  "typeKey": "GitItemNotFoundException",
  "errorCode": 0,
  "eventId": 3000
}
```

**Comment by tmat** [comment]
@sla1k Did you try to go directly to `https://#####.visualstudio.com/Doctis/_apis/git/repositories/Doctis.Common/items?api-version=1.0&versionType=commit&version=ae3398cc9eef7adeb7d2b397c151a6d861175b3c&path=/*`?

Can you try replacing `*` at the end of the query with relative path to some source file in your repository. E.g. if you have `README.txt` in the root, replace `*` with `README.txt`.

**Comment by ppumkin** [comment]
> F401174: The item '*' 

Its not a bug its a feature. No seriously.. 

Well, the * gets replaced with the file that needs to be downloaded. My link is the same and if i open it i get the same message. But in Visual Studio it will actually download the file.

The message is pretty self explanatory to be honest.
