### ISSUE TITLE
Build fails after including a library built with SourceLink

### ISSUE THREAD

**Issue by crackalak** [dotnet/sourcelink#95]
I have a .NET Framework 4.7 project with a NuGet package reference of a .NET Standard 2.0 library I built with SourceLink.
The build fails with:
> C:\mysolution\packages\Microsoft.Build.Tasks.Git.1.0.0-beta-62925-02\build\Microsoft.Build.Tasks.Git.targets(20,5): error : Unable to locate repository containing directory 'C:\mysolution\myproject'

This is due to the project I am trying to build not being under git source control.

To make this build I had to include the following in my project file:
```
<PropertyGroup>
    <RepositoryType>hg</RepositoryType>
</PropertyGroup>
```

This means that for anyone using my NuGet package, they would either need to be using git or make the manual change to their project file.

Here is where it defaults to git: https://github.com/dotnet/sourcelink/blob/74fc354e81dc6b7b33596c4f20a926c71ed41a68/src/Microsoft.Build.Tasks.Git.Operations/build/Microsoft.Build.Tasks.Git.targets#L24-L26

**Comment by tmat** [comment]
When you built your library did you use `PrivateAssets="all"` when referencing SourceLink package?

**Comment by crackalak** [comment]
I would have to check when back at a computer, but it would be set to whatever the default is after running:
    Install-Package Microsoft.SourceLink.Vsts.Git -Version 1.0.0-beta-62925-02

**Comment by tmat** [comment]
I don't think `Install-Package` sets the `PrivateAssets` metadata.

**Comment by crackalak** [comment]
I added ```PrivateAssets="All"``` to the package reference and it solved the problem, thanks! 😃

**Comment by appcoreopc** [comment]
Despite adding PrivateAssets="All", i am still getting "Unable to locate repository". 

The configuration i had in my csproj are as follows :- 


<PackageReference Include="Microsoft.SourceLink.GitLab" Version="1.0.0-beta-63127-02">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
 </PackageReference>
