### ISSUE TITLE
VSTS Git repo build in environment without Git installed

### ISSUE THREAD

**Issue by Yahangz** [dotnet/sourcelink#96]
Hi,

I am working on onboarding sourcelink to our project and it is working properly when I build in my local machine.

However, when I build this project in buildreq system (which publishes our nuget package) and cloudbuild (which validates my pull request), it hits below error:

> 1>VerifyGitInstalled:
1>  Verifying Git is installed
1>  where /q git.exe
1>  The command "where /q git.exe" exited with code 1.
1>  Git is not installed.

> d:\dbs\Cx\iri\.cbt\microsoft.build.tasks.git\1.0.0-beta-62925-02\build\Microsoft.Build.Tasks.Git.targets(20,5): error : Unable to locate repository containing directory 'd:\dbs\sh\iri\0622_113742\cmd\3\src\libraries\microsoft.servicefabric.aspnetcore.configuration\source'.

And this error was due to Git not installed in buildreq and cloudbuild image, I wonder how I can resolve this issue? I am thinking include git.exe in my project and have the targets 'know' the path of git. Do you think this might work or any other ways?

Any suggestion would be appreciated!

**Comment by tmat** [comment]
SourceLink doesn't require git.exe to be present on the machine. 
What is required is that the repository has `.git` directory on the machine. How does the build machine clone the repository before the build starts?

**Comment by Yahangz** [comment]
In our build environment, the machine has a few non-standard things: the .git directory is in $(EnlistmentRoot)\.git which is different than $(InetRoot)\.git, is this the reason I got above error and any workaround I can resolve it?

**Comment by tmat** [comment]
You can either change the configuration of your build machine to use standard repo clone, or create a symbolic link of the `.git` directory in the enlistment root.

**Comment by Yahangz** [comment]
I dont have the control of the configuration so I think option #1 does not work for me. Working on option #2, do you mean like having this in my target file: <Exec Command="mklink /d $(EnlistmentRoot)\bin $(InetRoot)\bin" />

**Comment by tmat** [comment]
Yes. I'd also add a condition that skips it if the .git directory already exists.

**Comment by Yahangz** [comment]
I am still hitting this `error:` d:\dbs\cx\iri\.cbt\microsoft.build.tasks.git\1.0.0-beta-62925-02\build\microsoft.build.tasks.git.targets(20,5) : error : Unable to locate repository containing directory` even with the symbolic link change, any idea what else I could try?

**Comment by tmat** [comment]
What project reports this error? Is that project located in a directory under the `$(EnlistmentRoot)` directory?

**Comment by tmat** [comment]
@Yahangz Have you been able to make it work?

**Comment by Yahangz** [comment]
Thanks @tmat! It is working fine for me. Will close this post.
