### ISSUE TITLE
runtime sourcelink file missing with latest sourcelink version

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sourcelink#993]
The [darc dependency flow PR into installer](https://github.com/dotnet/installer/pull/15999) is failing to build runtime in source build with the following error:

```
/vmr/src/runtime/artifacts/source-build/self/src/eng/versioning.targets(194,5): error MSB3030: Could not copy the file "/vmr/src/runtime/artifacts/source-build/self/src/artifacts/obj/coreclr/runtime-prereqs/x64/Release/runtime-prereqs.sourcelink.json" because it was not found. [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/runtime-prereqs.proj]
```

This appears to be released to the changes made in https://github.com/dotnet/sourcelink/pull/989.  cc @tmat

The _GenerateSourceLinkFile task is not writing the runtime-prereqs.sourcelink.json file.

binglog: https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzIzMjE1NS9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOF9PbmxpbmVfTXNmdFNka194NjRfQnVpbGRMb2dzX0F0dGVtcHQx0/content?format=file&subPath=%2Fsrc%2Fruntime%2Fartifacts%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog

**Comment by MichaelSimons** [comment]
The sourcelink PR intends to avoid writing the json file in certain situations.  Is this runtime situation one of those or not?  If it is, then it seems there is downstream targets that need updating react to the json file not being created.

**Comment by tmat** [comment]
The change doesn't write the file instead of writing a file that has empty mapping. This is necessary for bundling Source Link to SDK.

**Comment by tmat** [comment]
Actually, might be a bug in Source Link. I updated the task to log message when it decides not to write the file that includes the reason. The binlog doesn't show the message, so maybe it's not using the latest version yet. Would be good to see binlog using the latest version.

![image](https://user-images.githubusercontent.com/41759/230985984-44044f48-d18a-48cc-9ff7-1a874e99f7ba.png)

**Comment by tmat** [comment]
Oh, here is the issue:

![image](https://user-images.githubusercontent.com/41759/230988145-fd79e754-7289-4c14-8e7f-29dd40bf1b1a.png)

**Comment by tmat** [comment]
Ok, I think this is a bug in sourcelink target
